### ISSUE TITLE
Structual changes to make the interface more consistent/intuitive

### ISSUE THREAD

**Issue by flobernd** [zyantific/zydis#109]
Some structural changes should be made to make the interface more consistent/intuitive:

- [ ] The `ZydisDecodedInstruction` struct should be split in two separate structs - one that contains only the information provided in minimal-mode and one that (additionally?) contains the information provided in full-mode
- [ ] The API should be adjusted to mirror the above changes (switch to a 2-step decoding process - minimal/length decoding and full/semantical decoding). The minimal decoding function should take a buffer as input (like the `ZydisDecoderDecodeBuffer` function does) and the full decoding function should be able to extract all needed information from the struct returned by the minimal decoding function
- [ ] Create an additional function that takes a buffer as input (like the `ZydisDecoderDecodeBuffer` function does) and directly performs a full decoding (for convenience reasons)
- [ ] Move all meta-data to a separate struct and only use a pointer to that in the `ZydisDecodedInstruction` (similar to `accessed_flags`)

First task would be to provide a proper concept and to evaluate if there is a good way to minimize breaking changes.

**Comment by athre0z** [comment]
This issue is partially outdated and generally not very precise. Let's close this for the moment and discuss more concrete design proposals in new issues.
