### ISSUE TITLE
A Place to ask questions

### ISSUE THREAD

**Issue by secrary** [zyantific/zydis#114]
I can't find a place where I can ask Qs related to `Zydis`.

What is the best way to decode unknown size of code?
`ZydisDecoderDecodeBuffer` requires size of a code buffer.

**Comment by athre0z** [comment]
For asking questions, you can either join our Discord or just open issues like you just did. :) We also have a Gitter, but we don't check it insanely frequently.

For unknown size buffers, you can just pass the remaining length of your buffer. Zydis doesn't require you to pass the correct size, the length parameter is merely a protection against buffer overreads.
