### ISSUE TITLE
c problem

### ISSUE THREAD

**Issue by HenriettaSoldOut** [zyantific/zydis#117]
when compiling the code example raising the following errors

```
~/Desktop$ sudo gcc disasem.c -o disasembler
/tmp/ccfExQHn.o: In function `main':
disasem.c:(.text+0xde): undefined reference to `ZydisDecoderInit'
disasem.c:(.text+0xf2): undefined reference to `ZydisFormatterInit'
disasem.c:(.text+0x162): undefined reference to `ZydisFormatterFormatInstruction'
disasem.c:(.text+0x1cc): undefined reference to `ZydisDecoderDecodeBuffer'
collect2: error: ld returned 1 exit status
```

thanks

**Comment by athre0z** [comment]
In C, when using libraries, adding the include files is not sufficient. First, you have to build Zydis itself. Then, you have to tell GCC where to find the libraries and which one specifically you want to link, changing your invocation to something along the lines of:

```gcc disasem.c -L/path/to/zydis/build/directory -lZydis -o disasembler```

**Comment by HenriettaSoldOut** [comment]
thank you but still not working for me
i did the following exactly:
https://github.com/zyantific/zydis/issues/76#issuecomment-471368048

> git clone --recursive 'https://github.com/zyantific/zydis.git'
> cd zydis
> mkdir build && cd build
> cmake ..
> make
> make install
> 
> then go to the directory: "zydis/dependencies/zycore" and do the same:
> mkdir build && cd build
> cmake ..
> make
> make install

then in desktop copied your first example and run:

>  gcc /zydis/build/libZydis.a disasem.c -o disasembl

**Comment by turol** [comment]
Order matters. `libZydis.a` must come after `disasem.c` on the command line.

**Comment by SourceCodeDeleted** [comment]
I am just adding here.  `.a ` libs don't require the link `-l ` flag.

If you used the sudo make install you can simply 

`gcc test.c -o test /usr/local/lib/libZydis.a`

otherwise just use
`gcc test.c -o test libZydis.a`
