### ISSUE TITLE
movbe fails to decode

### ISSUE THREAD

**Issue by idc** [zyantific/zydis#119]
The following fails to decode as of 93eba10:

`66 0F 38 F0 45 E4` `movbe       ax,word ptr [rbp-1Ch]`

It seems zydis does not support word sized movbe, at least in `ZYDIS_MACHINE_MODE_LONG_64` / `ZYDIS_ADDRESS_WIDTH_64`.

If there is more information needed, please let me know. I have not tested with any other version of zydis.

**Comment by flobernd** [comment]
Thanks for reporting, I'll have a look in the next few days!

**Comment by flobernd** [comment]
I found the problem that is causing this issue and already found a solution as well. Will take me a few more days to implement tho.

**Comment by flobernd** [comment]
The `movbe` instruction should be fixed now.
