### ISSUE TITLE
Invalid use of ZYAN_FALLTHROUGH in ZydisGetInstructionSegments

### ISSUE THREAD

**Issue by raptorfactor** [zyantific/zydis#120]
Should be self-explanatory once you see it:

https://github.com/zyantific/zydis/blob/2052dcbe2c679944571b5bb2b9d6c27642340d76/src/Utils.c#L304

Causes a warning ("attribute 'fallthrough' not preceding a case label or default label") under GCC (and probably Clang but I hadn't gotten to that yet).

**Comment by flobernd** [comment]
Thanks for reporting!
