### ISSUE TITLE
Write an instruction simulator using zydis ?

### ISSUE THREAD

**Issue by wonderzdh** [zyantific/zydis#121]
Using zydis seems to be very convenient to complete the work of the instruction simulator. Has anyone tried this?

**Comment by stevemk14ebr** [comment]
This is also known as 'symbolic execution'. Afaik the answer is no. And to anyone who decides to do this PLEASE respect reserved bits and weird side effects of instructions. Most cases where emulation is useful is in heavily obfuscated routines that abuse weird/improperly emulated side effects to cause execution to go wrong.

**Comment by athre0z** [comment]
There is [this project](https://github.com/Coldzer0/Cmulator) and I believe there was another one I once stumbled across which I'm unable to find again.
