### ISSUE TITLE
The Visual Studio 2017 project can not build!

### ISSUE THREAD

**Issue by bahuwang** [zyantific/zydis#122]
When I build the Visual Studio 2017 project with windows 10 (1903), I encounter some problems.
The ZydisInfo project :
1. `Error LNK2019 unresolved external symbol ZyanTerminalEnableVT100 referenced in function main`
2. `Error	LNK2019	unresolved external symbol ZyanTerminalIsTTY referenced in function main`

Then I look for the code of Terminal.c in the Zycore project, because `#ifndef ZYAN_NO_LIBC`, I find the function  `ZyanTerminalEnableVT100` and `ZyanTerminalIsTTY `at the inactive preprocessor block. 
But I don not know why? And if I cut the error code, it can build, but when used ZydisInfo tool example, it only show white text.

**Comment by flobernd** [comment]
The `msvc` project ships with different build configurations. Please make sure to not use the `Kernel` profile as this one sets the `ZYAN_NO_LIBC` environment variable.

**Comment by bahuwang** [comment]
@flobernd Thank you.
