### ISSUE TITLE
Support instruction encoding / assembling

### ISSUE THREAD

**Issue by taodaqiao** [zyantific/zydis#129]
I hope to support the conversion between assembly code and hex code, which can be used a lot

**Comment by flobernd** [comment]
I'm not sure if I understand you correctly. Are you refering to an encoder?

**Comment by taodaqiao** [comment]
@flobernd Convert disassembly code to machine code
mov qword ptr ds:[0xFFFFF8016C664E68], rax  
to
48 A3 68 4E 66 6C 01 F8 FF FF

**Comment by flobernd** [comment]
Ah yes, that requires a combination of `encoder` and `parser` components. And encoder was on our todo for some time already, but was never finished. For the meantime you probably want to take a look at https://github.com/asmjit/asmjit (C++ tho and not super lightwight).

**Comment by taodaqiao** [comment]
None of them support windows kernel

**Comment by mrsshr** [comment]
implement it yourself and make pr to improve zydis
