### ISSUE TITLE
The x86 loop instructions: loop, loope, & loopne are all meta.branch_type ZYDIS_BRANCH_TYPE_NONE

### ISSUE THREAD

**Issue by BigJim** [zyantific/zydis#131]
I noticed in testing that for the three legacy x86 loop instructions:  
ZYDIS_MNEMONIC_LOOP, ZYDIS_MNEMONIC_LOOPE, and ZYDIS_MNEMONIC_LOOPNE .

ZydisDecodedInstruction.meta.meta.branch_type == ZYDIS_BRANCH_TYPE_NONE

Shouldn't these be ZYDIS_BRANCH_TYPE_SHORT instead?; since they are short branches after all.
If so, I see the probably easy fix is to change their corresponding "InstructionDefinitions.inc" flags.

**Comment by athre0z** [comment]
Yes, that looks like a table error to me. I pushed a fix to [this branch in our table repo](https://github.com/zyantific/zydis-db/tree/fix-loop), however I don't have the generator for the .inc files at hand right now, so we're going to have to wait for @flobernd to do update them, probably sometime later today.

Also: you're the IDA MSVC RTTI plugin guy, by any chance?

**Comment by BigJim** [comment]
Yea, I'm the ClassInformer guy.
Thanks for this great disassembler and your work on x64dbg et al.

**Comment by flobernd** [comment]
I will re-generate the tables later today.

**Comment by athre0z** [comment]
> Yea, I'm the ClassInformer guy.
> Thanks for this great disassembler and your work on x64dbg et al.

Happy you like it! We pulled a **ton** of value out of ClassInformer as well back when we were still doing a lot game hacking, thanks for creating it!
