### ISSUE TITLE
Assertion error triggered in `ZydisInfo` for series of instructions

### ISSUE THREAD

**Issue by kirschju** [zyantific/zydis#140]
Hi,

the following command causes an assertion error:

```
$ ZydisInfo -64 0fc7642440488b7310488b7b08e81695
ZydisInfo: <zydis_path>/zydis/src/Decoder.c:3497: ZydisSetEffectiveOperandWidth: Assertion `0' failed.
```

The problem is related to the last `0x95` instruction byte. Removing it clears up the issue.

~kirschju

**Comment by flobernd** [comment]
Thanks for reporting. I will have a look!
