### ISSUE TITLE
Building and printing assembly instructions by hand

### ISSUE THREAD

**Issue by BullyWiiPlaza** [zyantific/zydis#141]
First of all, thanks for this great and fairly modern library.

I've been wanting to build assembly instructions manually by filling `ZydisDecodedInstruction` structs with the respective data. While doing this I've been running into lots of trouble printing it back out correctly due to invalid field values and such. The error feedback in `zydis` in this regard seems quite lacking since no exceptions or crashes occur.

Is this library intended to do this task and/or are there are pointers towards doing this correctly?

An example of generating a `MOV` instruction with a specified destination register and an immediate value I came up with is below:

```
ZydisDecodedInstruction generate_move(ZydisRegister destination_register, unsigned long immediate) {
	ZydisDecodedInstruction instruction;
	instruction.attributes = 0;
	instruction.mnemonic = ZYDIS_MNEMONIC_MOV;
	instruction.operand_count = 2;
	instruction.operand_width = 64;

	ZydisDecodedOperand first_operand;
	first_operand.type = ZYDIS_OPERAND_TYPE_REGISTER;
	first_operand.reg.value = destination_register;
	instruction.operands[0] = first_operand;

	ZydisDecodedOperand second_operand;
	second_operand.type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
	second_operand.imm.value.u = immediate;
	second_operand.imm.is_relative = false;
	second_operand.imm.value.u = immediate;
	instruction.operands[1] = second_operand;

	return instruction;
}
```

**Comment by athre0z** [comment]
Hey & sorry for the late reply.

>  The error feedback in zydis in this regard seems quite lacking since no exceptions or crashes occur.
This library is written in C -- there is no such thing as exceptions in this language. In C, failure is reported via error codes.

> Is this library intended to do this task and/or are there are pointers towards doing this correctly?
Well, no, not really -- the formatter is primarily intended to print instructions that have previously been decoded by our decoder, but it should still work in general. Then again, I guess just `printf`ing the instructions without using Zydis would likely be a lot easier, unless you're just slightly previously changing existing `ZydisDecodedInstruction` structs.

> An example of generating a MOV instruction with a specified destination register and an immediate value I came up with is below:
Your example doesn't properly zero initialize the structs, all fields that you didn't manually overwrite are thus filled with completely random values, which will severely confuse the formatter.

You have to add
```C
memset(&first_operand, sizeof first_operand, 0);
```
etc., or write
```C
ZydisDecodedOperand first_operand = {0};
```

**Comment by BullyWiiPlaza** [comment]
@athre0z Thanks. After posting this issue I had the idea to simply assembly a string/buffer using an assembler and then diassembling it with `Zydis` to get a proper `ZydisDecodedInstruction` without fiddling around. This is a bit slower but more reliable. Due to that it would be great if `Zydis` or a sister project will one day support assembling like someone else asked for in this issue: https://github.com/zyantific/zydis/issues/145
