### ISSUE TITLE
How to use cmakelist creat zydiskernel.sln

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#143]

**Comment by athre0z** [comment]
Interpreting this as "How to use CMake to create a kernel mode version of Zydis":

Well, you don't. CMake doesn't support kernel mode builds -- you'll have to create a VS solution manually. There is a `ZydisWinKernel` example here:

https://github.com/zyantific/zydis/tree/master/msvc/examples

**Comment by DiskGetor** [comment]
No,please see here.
https://github.com/SergiusTheBest/FindWDK
vs2017 is too big,i use clion and findwdk build zydiskernel, i feel maybe modify some codes in zycore cmake?

**Comment by flobernd** [comment]
CMake doesn't support kernel mode builds -- you'll have to create a Clion solution manually. There is a `ZydisWinKernel` example here:

https://github.com/zyantific/zydis/tree/master/msvc/examples
