### ISSUE TITLE
Relative flag not set for ff 25 jmp in x86

### ISSUE THREAD

**Issue by stevemk14ebr** [zyantific/zydis#146]
When in x86 decoding mode the ZYDIS_ATTRIB_RELATIVE flag on the attributes member is not set for ff 25 style jmps (and probably calls too). This leads to inconsistencies with x64/x86 code.

The instruction is jmp dword ptr [eip+0] which zydis decodes as jmp dword ptr ds:[0]. The display here is fine but that flag should be set as the encoding is relative to eip.

**Comment by athre0z** [comment]
There's no such thing as EIP relative addressing in x86 / 32-bit mode. In 32 bit mode, the `mod == 0b101 && rm == 0b00` branch (as indicated by the `25` in the insn), the disp part of the instruction is interpreted as an absolute address:

https://www.sandpile.org/x86/opc_rm.htm

I checked and it looks like some assemblers such as the one used on defuse.ca incorrectly accept and drop an EIP base register for this instruction.

**Comment by stevemk14ebr** [comment]
Ah I see, I use defuse.ca. My mistake!

**Comment by athre0z** [comment]
No problem. :)
