### ISSUE TITLE
Add function to get the bit of a flag?

### ISSUE THREAD

**Issue by Michelele** [zyantific/zydis#147]
switch (flag) {
case ZYDIS_CPUFLAG_CF: return 0;
case ZYDIS_CPUFLAG_ZF: return 6;
...etc

**Comment by flobernd** [comment]
Hi there, 

take a look at `ZydisGetAccessedFlagsByAction` and variants. These will return you a bitmask .. it’s not the same mask as internally used by the CPU tho. 

Does that help you?

**Comment by flobernd** [comment]
Closed due to inactivity.
