### ISSUE TITLE
ZydisRegisterGetLargestEnclosing bug

### ISSUE THREAD

**Issue by Michelele** [zyantific/zydis#148]
ZydisRegisterGetLargestEnclosing(ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_REGISTER_RFLAGS)

returns ZYDIS_REGISTER_NONE

shouldn't it return ZYDIS_REGISTER_RFLAGS ?

**Comment by flobernd** [comment]
No. The `FLAGS/EFLAGS/RFLAGS` register can't coexist and they don't form a "real" group like e.g. all the GPR registers do.

Depending on the CPU mode only one of the flag registers is used.

In 16-bit mode it's always `FLAGS`,
in 32-bit mode it's always `EFLAGS` and
in 64-bit mode it's always `RFLAGS`.
