### ISSUE TITLE
vcpkg install zydis

### ISSUE THREAD

**Issue by kouzhudong** [zyantific/zydis#155]
$ vcpkg install zydis
bash: vcpkg: command not found

上面的命令是错误的，应该是：

$ ./vcpkg.exe install zydis
Computing installation plan...
...

**Comment by athre0z** [comment]
Issues must be submitted in English. It looks like you didn't install `vcpkg` first. Please take a look here:

https://github.com/microsoft/vcpkg#quick-start-windows

**Comment by kouzhudong** [comment]
$ vcpkg install zydis
bash: vcpkg: command not found
$ ./vcpkg.exe install zydis
Computing installation plan...
