### ISSUE TITLE
error LNK2019

### ISSUE THREAD

**Issue by kouzhudong** [zyantific/zydis#157]
1>Disasm.obj : error LNK2019: 无法解析的外部符号 __imp__ZydisDecoderInit，函数 "void __cdecl Disasm32(unsigned long,unsigned char *,unsigned long)" (?Disasm32@@YAXKPAEK@Z) 中引用了该符号
1>Disasm.obj : error LNK2019: 无法解析的外部符号 __imp__ZydisDecoderDecodeBuffer，函数 "void __cdecl Disasm32(unsigned long,unsigned char *,unsigned long)" (?Disasm32@@YAXKPAEK@Z) 中引用了该符号
1>Disasm.obj : error LNK2019: 无法解析的外部符号 __imp__ZydisFormatterInit，函数 "void __cdecl Disasm32(unsigned long,unsigned char *,unsigned long)" (?Disasm32@@YAXKPAEK@Z) 中引用了该符号
1>Disasm.obj : error LNK2019: 无法解析的外部符号 __imp__ZydisFormatterFormatInstruction，函数 "void __cdecl Disasm32(unsigned long,unsigned char *,unsigned long)" (?Disasm32@@YAXKPAEK@Z) 中引用了该符号

怪哉！
同一个git，在一台电脑上可以编译，在另外一台却不可以，是32位。
首先确保lib已经导入，否则会显示找不到lib的错误。
第二，函数的调用方式没变（cpp文件和__cdecl），lib的编译也是静态的（./vcpkg remove zydis:x86-windows-static）。
第三，用 extern也不行。

**Comment by athre0z** [comment]
Just like I told you last time, we only accept issues in English language.
