### ISSUE TITLE
Unresolved external symbol _imp_ZydisDecoderDecodeBuffer

### ISSUE THREAD

**Issue by Tetragromaton** [zyantific/zydis#159]
So first I am compiling Zydis as an project and it compiles fine, then as only as I do
`#include <Zydis/Zydis.h>` I am getting error:
LNK2001 Unresolved external symbol _imp_ZydisDecoderDecodeBuffer
Am I doing something wrong ?

**Comment by flobernd** [comment]
Did you forgot to link against the `Zydis` library maybe? Including the header is not sufficient.
