### ISSUE TITLE
How do you disassemble the first instruction in a byte array that have an unknown length?

### ISSUE THREAD

**Issue by jessielesbian** [zyantific/zydis#161]

**Comment by athre0z** [comment]
Just use `ZydisDecoderDecodeBuffer` and pass the maximum amount of bytes that are valid for Zydis to read. You aren't expected to pass the length of the instruction, but instead the maximum length to ensure that Zydis doesn't accidentally cause an overflowing read

**Comment by jessielesbian** [comment]
Thanks! That's a fast response!

**Comment by athre0z** [comment]
Since this question came up a few times, I now also improved the documentation on this:

https://github.com/zyantific/zydis/commit/c88a4b0cc1271b516b9697af8d088c851745dd60
