### ISSUE TITLE
Lods is missing register info

### ISSUE THREAD

**Issue by ZehMatt** [zyantific/zydis#166]
Lodsb/Lodsw/Lodsd/Lodsq is missing (R/E)SI being modified.

**Comment by athre0z** [comment]
I think this is expected behavior -- `lodsb` and friends don't access `RDI`, only `RSI`, `RAX` and `RFLAGS`:

https://www.felixcloutier.com/x86/lods:lodsb:lodsw:lodsd:lodsq

**Comment by ZehMatt** [comment]
Sorry I mixed it up with Stos where its RSI, silly x86. Corrected the first comment.

**Comment by flobernd** [comment]
Will add the conditional write access to this one as well. Thanks for reporting!
