### ISSUE TITLE
ZydisDecoderDecodeBuffer instruction length issue

### ISSUE THREAD

**Issue by NickTsl** [zyantific/zydis#172]
I use 	ZydisDecoderDecodeBuffer(&ZyDec64, Instruction, 15, &ZyIns)  to get the instruction length of instructions.  Most of the time this works well, but sometimes it reports an incorrect length. For example, zydis might read the following instruction as 4 bytes:

`48 89 5C 24 08                mov     [rsp+arg_0], rbx`

rather than 5 bytes

**Comment by flobernd** [comment]
I was not able to reproduce this:

```
>ZydisInfo -64 48 89 5C 24 08
== [    BASIC ] ============================================================================================
   MNEMONIC: mov [ENC: DEFAULT, MAP: DEFAULT, OPC: 0x89]
   LENGTH:  5
```

Is your `ZyDec64` buffer guaranteed to always be 15 bytes or larger? The hardcoded `15` as `length` argument always alerts me.

**Comment by NickTsl** [comment]
> I was not able to reproduce this:
> 
> ```
> >ZydisInfo -64 48 89 5C 24 08
> == [    BASIC ] ============================================================================================
>    MNEMONIC: mov [ENC: DEFAULT, MAP: DEFAULT, OPC: 0x89]
>    LENGTH:  5
> ```
> 
> Is your `ZyDec64` buffer guaranteed to always be 15 bytes or larger? The hardcoded `15` as `length` argument always alerts me.

I tried using lengths of 20 bytes, and it still had the same problem with the same instructions.

**Comment by flobernd** [comment]
You got me wrong here. I suspect your buffer does overflow and/or does not contain the correct instruction bytes.

Did you check the buffer contents before calling the Zydis decode function?

Without showing more code, I won't be able to help you.
