### ISSUE TITLE
3 features that should be added in the future

### ISSUE THREAD

**Issue by ghzcrlvct2** [zyantific/zydis#175]
1) Option to not automatically skip invalid bytes:

If for example you have [invalid byte] [invalid byte] [valid byte] [valid byte], it would be helpful to have a way to tell zydis to stop after the invalid byte and return, so they can be separated from the valid instructions decoded.

2) Field in InstructionInformation with just the valid instruction bytes.

For example, in the case of SQRTSD, they would contain F2 0F 51 and the raw number of opcodes without prefixes, modrm, etc.

3) Attribute that says if the instruction is an extension

For example, 80, has 8 extensions, so it would be helpful for myself to know if it is extended and which of the extensions it is

--

But perhaps there's already a way to perform at least one of these things that I don't know of, in which case, you could perhaps help

Thanks!

**Comment by flobernd** [comment]
Hey there,

1. You should check the return value of `ZydisDecoderDecodeBuffer()`. If it fails, you know the instruction was invalid.
2. There are 2 ways of getting this information
  - Request the instruction segments (`Utils.h`) and work with the offset and size of the `OPCODE` segment
  - Check the `.opcode_map` and `.opcode` fields in the `ZydisDecodedInstruction`
3. For this case you could check the `.encoding` of the first operand. It should tell you that the register is encoded in the opcode itself.

Let me know, if you need further information.

**Comment by flobernd** [comment]
Closed for now. Feel free to ask again, if you need more information @ghzcrlvct2
