### ISSUE TITLE
Assertion failed in ZydisInfo for apparent Intel AMX instruction

### ISSUE THREAD

**Issue by tremalrik** [zyantific/zydis#182]
While feeding randomized x86 to zydis, I get an assertion failure, that can be reproduced up in the ZydisInfo tool:
```
ZydisInfo -64  C4 C2 7A 4B 04 00
ZydisInfo: /home/tremalrik/x86_decode/zydis-master/zydis/src/Decoder.c:1171: ZydisSetOperandSizeAndElementInfo: Assertion `definition->size[context->eosz_index]' failed.
Aborted (core dumped)
```
The instruction appears to be an AMX instruction, probably TILESTORED.

**Comment by flobernd** [comment]
Thanks for reporting! Sadly it was not discovered during the fuzzer run 😞

**Comment by flobernd** [comment]
Fixed with: https://github.com/zyantific/zydis/commit/67f7892446ff879e17717e9a88ef144f710cce97

The assertion was incorrect. For the tile memory operands we can not set a specific size as they are variable width.
