### ISSUE TITLE
output: "invalid"

### ISSUE THREAD

**Issue by israelelizera** [zyantific/zydis#185]
i'm creating patcher project which includs Zydis disassembler. i'm get the assembly input and compare it to the output in the official web of Zydis, basicly the code is the same code except to location i'm get "invalid" output while the Zydis web prints DB 0xFF. is someone know why?

**Comment by athre0z** [comment]
The website prints instructions as raw bytes (`db 0xXX`) when the decoder reports invalid instructions. This is expected behavior.

**Comment by flobernd** [comment]
In both cases you are trying to disassemble an invalid instruction. Maybe you got the address wrong or there are data bytes in the code section which you would have to skip while e.g. doing a linear sweep.
