### ISSUE TITLE
Failure to correctly disassemble JMP [rip+0x0] QWORD 

### ISSUE THREAD

**Issue by Fahersto** [zyantific/zydis#188]
Im currently writing a hooking library using Zydis and came across an issue when relocating conditional jumps.
My relocation involves a jump of this type:

jmp [rip+0] QWORD

The QWORD is the absolute address I want to jump to. So lets say I want to jump to 0x1122334455667788:

ff 25 00 00 00 00 88 77 66 55 44 33 22 11

I use this jump because it can jump to an absolute 8 byte address without making any register dirty.

Test results:
Zydis - fails
CheatEngine - correct
x64dbg - fails 
https://defuse.ca/online-x86-assembler.htm#disassembly2 - fails

![zydis_issue_14byte_jmp](https://user-images.githubusercontent.com/31221314/124948692-c4e7a980-dfc5-11eb-94a2-c08903bc0398.png)

**Comment by athre0z** [comment]
Hey there! There is no such instruction -- CE seems to be the one doing it incorrectly. You can try it out, the CPU won't actually do what you expect. x64dbg is using Zydis as well by the way. The only instruction with a 64 bit immediate is `movabs`.

**Comment by Fahersto** [comment]
When jmp [rip+0] QWORD is executed rip+0 points to that QWORD and it will jump to it. I do understand what you mean by there is no such instruction though. So I guess CheatEngine is going the extra mile here understanding the semantic of the instruction instead of just parsing tables?

**Comment by mrsshr** [comment]
i don't think this is what the disassembler is supposed to do.
check the mnemonic, operand type, register, disp, etc.. and treat them specially.
zydis provides everything you need.

**Comment by athre0z** [comment]
> When jmp [rip+0] QWORD is executed rip+0 points to that QWORD and it will jump to it.  I do understand what you mean by there is no such instruction though. So I guess CheatEngine is going the extra mile here understanding the semantic of the instruction instead of just parsing tables?

Ah yeah, true, it does work, but it isn't a separate instruction. Yes, CE seems to be emitting a non-standard pseudo-instruction for that special case.

**Comment by Fahersto** [comment]
I fully understand that this can be considered as working as indented. Its just something that confused me for a moment because you will get 8 bytes worth of "random" instructions if you don't treat this type of jump separately when disassembling. 
And maybe your entire disassembling goes down the drain if the last of your "random" instructions happens to create a new instruction with the following bytes? Im not sure about that.

@mrsshr I'm fully aware that Zydis offers me all information I need to treat this special case. I was just not sure if this is a special case everyone would have to catch themselves or if this can be solved in a reasonable way for everyone.

**Comment by mrsshr** [comment]
@Fahersto it would be nice to be able to handle the case of mixing code and data automatically, but i'm not sure if it's the right thing to do in zydis.

**Comment by athre0z** [comment]
So I think that this would be a reasonable thing to expect from a higher level disassembler library that constructs control flow graphs etc., but it doesn't really fit into Zydis. Zydis is essentially just a decoder library, analogous to the instruction decoder unit in CPUs. Semantic analysis is left for higher level layers in the stack. There are quite a few cases where data and code can end up being intermixed, with switch tables being a prominent example. Properly analyzing and detecting such cases is non-trivial, and I think that adding a special case for this one thing that we can detect easily would make things just even more confusing.

**Comment by flobernd** [comment]
CheatEngine probably just does not do linear sweep disassembly, but instead extracts all the symbols from a PE file and uses them (and the EP) as a starting point to follow all branches. 

Other than that I agree with athre0z above statement.

**Comment by Fahersto** [comment]
I understand mixture of code and data is a topic beyond the scope of the project.  
Thanks for the discussion and Zydis in general 😄
