### ISSUE TITLE
MOVS instructions missing register info

### ISSUE THREAD

**Issue by johnined** [zyantific/zydis#190]
MOVSB/D/W instructions are also missing writes for [R/ESI and R/EDI](https://www.felixcloutier.com/x86/movs:movsb:movsw:movsd:movsq).

Zydis classifies the BSF/BSR destination register as CW, but the destination is [undefined if it is not written](https://www.felixcloutier.com/x86/bsf), so this should be W.
Edit: What is the intended behavior here? The comment above `COND_WRITE` says "may write" but `STOSB` currently classifies R/EDI as conditional write but it always writes to the variable.

**Comment by flobernd** [comment]
@johnined 
> What is the intended behavior here? The comment above COND_WRITE says "may write" but STOSB currently classifies R/EDI as conditional write but it always writes to the variable.

Sorry for late reply, I did not see your edit.

For the "normal" `stosb` (without prefix), it is `WRITE`. For the prefixed forms (e.g. `rep stosb`) it is `COND_WRITE` because the `REP` condition is checked before the first execution of the instruction. In theory this can cause a no-op, if the `REP` condition is not met when executing the `stosb`.

**Comment by flobernd** [comment]
Fixed with https://github.com/zyantific/zydis/commit/2ab6a5ccb49043e077bcb2559893b1944f8e0a09

**Comment by ZehMatt** [comment]
> @johnined I fixed the data-tables in this commits:
> 
> * [zyantific/zydis-db@19e51f8](https://github.com/zyantific/zydis-db/commit/19e51f8c0f4d2730754b83a101a56a826cf48742)
> * [zyantific/zydis-db@6b5a35a](https://github.com/zyantific/zydis-db/commit/6b5a35a28db17cd8012e2b28e85e3b4b73256b01)
> 
> Going to apply the fix to `Zydis` in the next few days.
> 
> Note that we now use the `condwrite` action for all the prefixed (`REP`) versions of `stos*`/`movs*`. A `condread_condwrite` action would probably be better, but this type currently does not exists.
> 
> The implicit memory operand uses the `DI`/`SI` register anyways (in `READ` mode obviously), so make sure to always check the individual components (registers) of memory operands as well to determine a complete set of registers read (as you won't see the `READ` operation for the implicit register operand anymore).

I just ran into this exact issue wondering why the registers arent marked as read, the work-around is a bit odd for me as I place the exact memory address in the memory operands for tainting purposes so I loose that information, I think it would be good if the rsi/rdi register is also marked condread as that would make a bit more sense given its not just read for the memory operand but also read to update the registers.
