### ISSUE TITLE
Incorrect formatting of signed displacements

### ISSUE THREAD

**Issue by mappzor** [zyantific/zydis#192]
All displacements are treated as signed and that works fine in most cases except for absolute addresses in relative mode (`ZYDIS_RUNTIME_ADDRESS_NONE`). This mode breaks for instructions with displacement-only SIB bytes and moffs operands. This can easily lead to some very confusing outputs, especially for Intel syntax.

Examples:
```
ZydisInfo.exe -32 67a08888
...
== [      ATT ] ============================================================================================
   ABSOLUTE: mov 0x00008888, %al
   RELATIVE: mov -0x7778, %al

== [    INTEL ] ============================================================================================
   ABSOLUTE: mov al, byte ptr ds:[0x00008888]
   RELATIVE: mov al, byte ptr ds:[0x7778]

ZydisInfo.exe -32 67a07877
== [      ATT ] ============================================================================================
   ABSOLUTE: mov 0x00007778, %al
   RELATIVE: mov 0x7778, %al

== [    INTEL ] ============================================================================================
   ABSOLUTE: mov al, byte ptr ds:[0x00007778]
   RELATIVE: mov al, byte ptr ds:[0x7778]
```
Relative mode should apply only to displacements that are actually relative to something other than segment base i.e. explicit register(s) or RIP.

Seems like a small fix is required in code of `ZydisFormatterXXXFormatOperandMEM` functions to correct this. Example fix for Intel (it's practically the same for AT&T):
```diff
-        if (context->operand->mem.disp.has_displacement && (context->operand->mem.disp.value
-            || neither_reg_nor_idx))
+        if (neither_reg_nor_idx)
+        {
+            ZYAN_CHECK(formatter->func_print_address_abs(formatter, buffer, context));
+        }
+        else if (context->operand->mem.disp.has_displacement && context->operand->mem.disp.value)
         {
             ZYAN_CHECK(formatter->func_print_disp(formatter, buffer, context));
         }
```
By the way I found this while investigating some issues I had with signedness of immediates and other values in Zydis. For example why in `mov al, moffs8 (A0)` source operand is treated as unsigned (`uint8`) but in `mov ax/eax/rax, moffs16/32/64 (A1)` element type is specified as `int`? I know that defining signedness in data transfer instructions (except for zero/sign-extending variants of mov) is pointless but I would expect some consistency here (all signed, all unsigned or something like "not applicable").

**Comment by flobernd** [comment]
Hey @mappzor, thanks for reporting. I will have a look when I'm back from vacation.

The first thing pretty much looks like  a bug.

For the `A0`/`A1` inconsistency I sadly can't remember. What you are writing makes sense. Usually I choose `int` for operations which do stuff like sign-extension and `uint` for the data move instructions. Could be that I just missed some places (initially `int` was the default type for all instructions). If you have found more places, please report them as well. This would help me to find out a pattern (if there is one).
