### ISSUE TITLE
BNDMK with rip-relative addressing

### ISSUE THREAD

**Issue by tremalrik** [zyantific/zydis#205]
According to the Intel SDM, the Intel MPX instructions BNDLDX, BNDSTX and BNDMK should #UD if used with RIP-relative addressing. Zydis reports a decoding error for BNDLDX and BNDSTX in this case, but not for BNDMK  - "ZydisInfo -64 F3 0F 1B 05 00 00 00 00" returns "bndmk bnd0,ds:[rip]". I assume this one should have reported as an error as well?

**Comment by flobernd** [comment]
@tremalrik Thanks for reporting! Yes, we consider incorrect disassembly as bugs 😃

**Comment by flobernd** [comment]
`RIP`-relative addressing was only prevented for actual `MIB` operands. The check did not apply to `BNDMK` as it uses a normal memory operand (more precisely: `AGEN`).

Fixed in the CET branch by a table/generator adjustment.

**Comment by flobernd** [comment]
Fixed with #204
