### ISSUE TITLE
VEX/EVEX instruction decoding allowed in 16-bit real mode

### ISSUE THREAD

**Issue by mappzor** [zyantific/zydis#208]
Presence of VEX/EVEX prefix guarantees #UD in real mode but Zydis doesn't enforce that when initialized with `ZYDIS_MACHINE_MODE_REAL_16`. I believe that `DECODING_ERROR` should be returned for those instructions.

For some reason Intel provided very clearly labeled sections about some interactions (`VEX and the LOCK prefix`, `VEX and the 66H, F2H, and F3H prefixes`, `VEX and the REX prefix`) but didn't describe real mode behavior explicitly. All VEX/EVEX have exception classes assigned though and all of them guarantee #UD due to VEX/EVEX prefix.

This could be fixed in code or in the generator (treat all VEX/EVEX instrictions as if they had `protected_mode` flag). It seems that fix inside `ZydisNodeHandlerOpcode` would be the best approach allowing to fail as soon as possible.

**Comment by tremalrik** [comment]
This issue affects AMD's XOP prefix as well - like VEX/EVEX, it is considered #UD in real mode.

The restriction is specific to real/virtual-86 mode - VEX/EVEX/XOP instructions appear be fully allowed in e.g. 16-bit protected mode. Also, the restriction applies to the prefix rather than the associated ISA extensions - e.g. for BMI1, `BZHI` (which uses a VEX prefix) is affected by this restriction while `TZCNT` (which doesn't use any of these prefixes) is not.

**Comment by flobernd** [comment]
Thanks guys, will apply the suggested in-code fix!

**Comment by flobernd** [comment]
@mappzor @tremalrik Just to be safe here:

- 16-bit real: -
- 16-bit-protected: XOP, VEX, EVEX
- 32-bit protected: XOP, VEX, EVEX
- 64-bit: XOP, VEX, EVEX, MVEX

**Comment by tremalrik** [comment]
Looks right to me. (For XOP, the relevant documentation would be AMD APM, volume 4, chapter 3 "Exception Summary" - the XOP instructions are Class 10.)

MVEX is a bit special in that it appears to be only supported on Knights Corner, which only allows any of these prefixes in 64-bit mode. There also exists a bunch of KNC-specific instructions that use the VEX prefix (e.g. `c4 e1 78 41 ca - KAND k1,k2`)  - these are all available in 64-bit mode only. (VEX-encoded instructions that were introduced in KNC but also exist in later processors - such as e.g. `c4 e1 78 98 ca - KORTESTW k1,k2` - are restricted to 64-bit on KNC but are allowed in 16/32-bit protected mode on later processors.) A few cursory tests indicate that Zydis handles MVEX and the KNC-specific instructions correctly.

**Comment by flobernd** [comment]
Thanks for clarification! In this case my PR should work.
