### ISSUE TITLE
Assertion failure on new AVX512-FP16 VGETMANTPH instruction

### ISSUE THREAD

**Issue by tremalrik** [zyantific/zydis#215]
Running `ZydisInfo -64  62 B3 7C 39 26 00 00` using the new 61731ae version of Zydis, I get an assertion:
```
ZydisInfo: /home/tremalrik/x86_decode/zydis-master/zydis/src/Decoder.c:2567: ZydisSetAVXInformation: Assertion `!evex_b || ((!evex_w && context->evex.element_size == 32) || ( evex_w && context->evex.element_size == 64))' failed.
Aborted (core dumped)
```
XED decodes this instruction encoding to `vgetmantph ymm0{k1}, word ptr [rax]{1to16}, 0x0`.

**Comment by flobernd** [comment]
Nice finding again! Almost expected an assert to fail after the latest change, but probably I did not test and fuzz long enough.

May I ask if you found this "randomly" or do you have some kind of testsuite?

**Comment by tremalrik** [comment]
Yeah, I do have a directed-random fuzz tester (biased in favor of creating x86 instruction encodings with many prefixes and/or one of the multi-byte prefixes - 0F_0F, 0F_38, 0F_3A, VEX2, VEX3, XOP, EVEX - since these parts of the x86 opcode space tend to be unreasonably hard to hit with unbiased-random byte sequences). Adapting it to specifically test Zydis itself turned out to be fairly simple, see https://github.com/tremalrik/zydis-fuzzer for an initial version. For Zydis, this fuzzer seems only really useful for finding decode assertions - it will not detect incorrect decodings or anything of that sort.

With the 61731ae version of Zydis, it generally finds an assertion in about 1 to 15 seconds, depending on input seed. So far, I've seen it produce assertions on a VRNDSCALEPH (`62 53 7C 3C 08 47 75 11` in 64-bit mode), a VREDUCEPH (`36 67 62 E3 7C DF 56 9E 8E 79 C2 46 A6` in 16-bit mode) and a VCMPPH (`62 C3 14 19 C2 4B 2F 32` in 16-bit mode) in addiiton to the VGETMANTPH.

**Comment by flobernd** [comment]
That looks very useful :-)

@athre0z Maybe we should think about adding this custom fuzzer to our CI as well, if @tremalrik does not mind.

OssFuzz indeed seems not reach the more complex regions of the X86 ISA within an acceptable amount of time.

**Comment by athre0z** [comment]
I'm not even sure whether we even have assertions enabled in OSS-Fuzz, to be honest.

**Comment by flobernd** [comment]
> I'm not even sure whether we even have assertions enabled in OSS-Fuzz builds, to be honest.

This we should check 😄

**Comment by flobernd** [comment]
There might be issues with the other tuple-types as well. The FP16 SDM mentions some differences in the disp8 scale I need to check. It should not crash anymore with my latest commit, but some of the disp8 values might be scaled incorrectly.

**Comment by flobernd** [comment]
I did not pay attention to the generator code and therefore did not notice EVEX map 5/6 are used for some of the new instructions. Fixed all that mess in my latest commits and as well checked the scaling. Looks good now for all my testcases. As well compared to XED and did not find any noticeable differences at first sight.

**Comment by tremalrik** [comment]
I'm getting assertion failures in fuzzing again, e.g. for `62 35 7D BF 78 5A 08` in 64-bit mode (which xed thinks is `vcvttph2uqq ymm11{k7}{z}, word ptr [rdx+0x10]{1to4}`.) From running it a few times, it appears that all the new failures affect EVEX map 5.

**Comment by flobernd** [comment]
@tremalrik Are you sure you rebuilt Zydis? For me locally it works perfectly fine:
![screenshot](https://nextcloud.flobernd.de/s/EiqLQddijT3xgn8/preview)

**Comment by flobernd** [comment]
@tremalrik Fixed in my latest commit, thanks! Hope this will be the last one. I forked your fuzzer and will run it as well later when I'm back home. Sadly it seems like oss-fuzz still does not find the issues very efficiently, even after athre0z latest improvements.
