### ISSUE TITLE
Print `{z}` decorator for instructions with zero-only mask mode

### ISSUE THREAD

**Issue by flobernd** [zyantific/zydis#220]
Certain instructions like e.g. `vpshufbitqmb` use hardcoded zero masking.

Intel SDM says:
> This instruction uses write masking (zeroing only).

Zydis correctly reflects this in the `ZydisDecodedInstruction`, but currently we do not print the `{z}` decorator for these cases.

Related to https://github.com/intelxed/xed/issues/277

**Comment by flobernd** [comment]
I just found my own comment while working on it:
https://github.com/zyantific/zydis/blob/80d8d5231f7204c7e39f70d2fe5887654037825c/src/FormatterBase.c#L597

@athre0z Can we compare against other disassemblers or assemblers?

**Comment by mappzor** [comment]
I'm aware of two cases:
- NASM: will not accept `{z}` decorator when assembling, ndisasm will not show it when disassembling
- capstone (cstool): fails to decode instruction completely ;)

**Comment by flobernd** [comment]
Thanks for checking! 

I think in this case I will close this issue and don't print it as well. The `.avx.mask_mode` property will correctly contain `ZYDIS_MASK_MODE_ZEROING` or `ZYDIS_MASK_MODE_CONTROL_ZEROING` anyways, if somebody needs this information.
