### ISSUE TITLE
Grouping bytes of opcode

### ISSUE THREAD

**Issue by torusrxxx** [zyantific/zydis#23]
x64dbg users are expecting the bytes of opcode can be grouped like Ollydbg. For example, `B8 00 00 00 00` (`mov eax,0`) can be displayed as `B8 00000000` and `C7 86 11 11 11 11 22 22 22 22` (`mov dword ptr ds:[esi+11111111],22222222`) can be displayed as `C786 11111111 22222222`. It will be very helpful if such information can be available with zydis. Thank you.

**Comment by flobernd** [comment]
So you are actually trying to seperate displacement and immediate values from the rest of the instruction-bytes?

You can accomplish this by evaluating `instruction.raw.disp.offset`, `instruction.raw.disp.size`, `instruction.raw.imm[0/1].offset` and `instruction.raw.imm[0/1].size`.

**Comment by torusrxxx** [comment]
Is there also a way to get size of prefix?

**Comment by athre0z** [comment]
Yup. Check `ZydisDecodedInstruction::raw::prefixes::count`.

**Comment by DiskGetor** [comment]
DbgPrint("0x%02X,", (opcodes + offset)[i]); 没安排好，但可以了解一下
