### ISSUE TITLE
Inconsistent segment override behavior for agen/agen_norel operands

### ISSUE THREAD

**Issue by mappzor** [zyantific/zydis#230]
I've been looking at `accepts_segment` evaluation logic and found a discrepancy in segment override handling.
| Instruction(s) | operand_type | prefix_flags | accepts_segment |
| --- | --- | --- | --- |
| bndcl, bndcn, bndcu | agen | none | yes |
| bndmk | agen_norel | none | no |
| lea | agen | remove_segment | no |

Issue with the database is that `remove_segment` is used only for `lea`. Issue in the generator is that currently `agen` and `agen_norel` are handled differently becasue `agen_norel` wasn't added here:
```delphi
    if (Definition.Operands.Items[I].OperandType in
      [optImplicitMem, optMEM, optMEMVSIBX, optMEMVSIBY, optMEMVSIBZ, optPTR, optAGEN,
       optMOFFS, optMIB]) then
    begin
      if (Definition.Operands.Items[I].IgnoreSegmentOverride) then
      begin
        Continue;
      end;

      Result := true;
      Break;
    end;
```
My suggestion to fix this is to modify `TZYDefinitionTableGenerator.AcceptsSegment`, so both `agen` and `agen_norel` are NOT present there. Then I would remove `remove_segment` from `lea` definition just to clean it up. This will ensure consistent, default LEA-like behavior for all `agen/agen_norel` operands without having to remember about adding extra stuff like `remove_segment` flag.

**Comment by flobernd** [comment]
Thanks for reporting! I probably forgot to add the `AGEN_NOREL` to the segment-override logic as this operand type was introduced later.

For the `remove_segment` I think we already talked on Discord and the conclusion was, that this flag has been the initial approach to solve this problem for the whole instruction, but with the need to ignore segment overrides only for certain operands, it became obsolete.

Besides your suggested solution, I will as well check if any other instruction uses the old `remove_segment` and will convert it to the new "per-operand" flag.

**Comment by flobernd** [comment]
@mappzor 
I applied your suggested fix in the `zydis-db` repo, but did not consolidate the `remove_segment` for all instructions yet.

The following instructions are still using the `remove_segment` flag:

```
insb
insd
insw
montmul
scasb
scasd
scasq
scasw
stosb
stosd
stosq
stosw
xcrypt_cbc
xcrypt_cfb
xcrypt_ctr
xcrypt_ecb
xcrypt_ofb
xsha1
xsha256
xstore
```

I will need some time to check which operands are affected, because some of them have multiple implicit memory operands. To keep the current semantics I would have to mark all of the operands with the `ignore_segment_override` flag, but I would like to double check, if this is really correct for all of them.

**Comment by mappzor** [comment]
Those have single ES mem operands with `ignore_seg_override`, so removing `remove_segment` will not change anything:
```
insb
insd
insw
montmul
scasb
scasd
scasq
scasw
stosb
stosd
stosq
stosw
xstore
```
Those have multiple ES mem operands but all of them with `ignore_seg_override`, so removing `remove_segment` will not change anything:
```
xcrypt_cbc
xcrypt_cfb
xcrypt_ctr
xcrypt_ecb
xcrypt_ofb
xsha1
xsha256
```
Everything looks good to me :smiley:

**Comment by flobernd** [comment]
I removed the obsolete flag in this commit: https://github.com/zyantific/zydis-db/commit/773e0489becd7775705dbef6d5bf986143582f8f
