### ISSUE TITLE
EVEX-encoded VCOMISS and the {sae} modifier

### ISSUE THREAD

**Issue by tremalrik** [zyantific/zydis#232]
According to the Intel SDM (June 2021 revision) description of the `vcomiss` instruction, the EVEX-encoded version of this instruction supports the `{sae}` (suppress-all-exceptions) modifier when used with two register arguments. This is recognized by xed but not Zydis:
 * `xed -64 -d 62 f1 7c 78 2f c1` returns `vcomiss xmm0{sae}, xmm1`
 * `ZydisInfo -64 62 f1 7c 78 2f c1` returns `vcomiss xmm0, xmm1`

The same issue also applies to the closely related instructions `vcomish`, `vcomisd`, `vucomiss`, `vucomish`, `vucomisd`.

(The SDM appears to contradict itself on this modifier: it specifies that these instructions belong to the "E3NF" exception class, but the description of E3NF (volume 2, section 2.7.3, table 2-47) specifies that EVEX.b != 0 should result in #UD. This would seem to prohibit the `{sae}` encoding completely, but this contradicts both the instruction description and the xed output, so I assume the table 2-47 is in error.)

**Comment by mappzor** [comment]
This seems to be a known formatter issue. Decoder properly detects `{sae}` but ZydisInfo won't print it because:
```c
                // TODO: `sae` is displayed twice e.g. for `62 E30D1B 0A D3 A5`
                // TODO: Checking the `operand_count` does not work for instructions with hidden operands
```
`operand_count` here is 3 and last operand is hidden therefore code to print `{sae}` decorator is never triggered.

**Comment by flobernd** [comment]
Thanks for reporting and thanks for the fix!
