### ISSUE TITLE
Invalid hidden register scaling for some packed compare instructions

### ISSUE THREAD

**Issue by mappzor** [zyantific/zydis#245]
Currently Zydis has multiple definitions to accomodate for hidden register scaling based on VEX.W. In some cases current behavior doesn't match Intel SDM:
```
pcmpestri (A)
vpcmpestri (A)
pcmpistri (B)
vpcmpistri (B)
```
| Case | Current behavior | Correct behavior |
| --- | --- | --- |
| A | EAX, EDX, ECX scale | EAX, EDX scale, ECX does not scale |
| B | ECX scales | ECX does not scale |

**Comment by flobernd** [comment]
Somehow these definitions were messed up. We had identical definitions for some of these instructions with `REX.W=0` and `REX.W=1`. Same thing for `MODE=64` and `MODE!=64`.

Did not make a difference in the generated tables as they are deduplicated by the code generator, but cleans up the `instructions.json` a little:
https://github.com/zyantific/zydis-db/commit/50dba92f3172bb48142647f991600df819083c41
