### ISSUE TITLE
AVX512: Opmask source operands using the VEX.B/EVEX.B bit

### ISSUE THREAD

**Issue by tremalrik** [zyantific/zydis#292]
According to the Intel SDM (volume 1, section 2.6.11.3), when the ModRM:r/m field of an instruction with VEX or EVEX prefix encodes an opmask source register, the B bit of the VEX/EVEX prefix must be ignored. Zydis does not appear to do this correctly in 64-bit mode, resulting in unexpected BAD_REGISTER errors.

A couple of examples of instructions encodings exhibiting this issue in 64-bit mode:
 * `C4 C1 7C 41 C1` (encoding with VEX.B=0) is decoded by XED but not Zydis as `kandw k0,k0,k1`. (The corresponding VEX.B=1 encoding  `C4 E1 7C 41 C1` is decoded as `kandw k0,k0,k1` by both.)
 * `62 D2 7E 48 3A C1` (encoding with EVEX.B=0) is decoded by XED but not Zydis as `vpbroadcastmw2d zmm0,k1` (The corresponding EVEX.B=1 encoding `62 F2 7E 48 3A C1` is decoded by both)

**Comment by flobernd** [comment]
Good finding, thanks! This used to work in the past and probably is a regression caused by https://github.com/zyantific/zydis/commit/33c5bccff79c66c13ca09d523cd5fd726ce93f94
