### ISSUE TITLE
Encoder may prepend operand size prefix to reduce length

### ISSUE THREAD

**Issue by ZehMatt** [zyantific/zydis#296]
It seems possible that for some instructions the encoder might add an operand size prefix to shorten the immediate this however changes usually how the instruction works, a concrete example would be ```push <imm>```.

Encoding ```push 0x1CC``` will generate following bytes:
```
66:68 CC01 | push 1CC
```` 
I think the encoder should not prepend prefixes in order to shrink the size, this potentially changes how the instruction operates. Other instructions other than push might be affected, can't think of any right now.

**Comment by tremalrik** [comment]
This seems like it would need to vary a lot by instruction, with x86 generally having a lot of pitfalls:
* For `push 1cc`, the encoding `66 68 cc 01` will push 2 bytes on the stack in both 32-bit and 64-bit mode, while `68 cc 01 00 00 ` will push 4 bytes in 32-bit mode and 8 bytes in 64-bit mode; as such `66 68 cc 01` seems quite unsafe.
* Near branch instructions in 32-bit mode can take a 66h prefix to cut the offset from 4 to 2 bytes, however this has the side effect of ANDing IP with 0xFFFF as part of the branch instruction. (The exception to this is XBEGIN, which doesn't do this truncation and thus safely can use the 66h prefix to cut the immediate-size.)
* For e.g. `mov [0x12345678],eax`, in 64-bit mode, it is safe to use the Direct-Offset encoding with 67h prefix to cut length, resulting in `67 a3 78 56 34 12`. However, the Direct-Offset encoding does not work with the `xrelease`prefix: `xrelease mov [0x12345678],eax` cannot be encoded as `f3 67 a3 78 56 34 12` but must instead be encoded with something like `f3 88 04 25 78 56 34 12`.
* In 32-bit mode, using the 67h prefix to encode a memory load/store with an immediate address less than 64K is usually safe - e.g. `les eax,[0x10]` can safely be encoded as `67 c4 06 10 00` which is 1 byte shorter than `c4 05 10 00 00 00`. However, this becomes unsafe near the end of the 64K region, especially for instructions that take multipart memory arguments. E.g. `les eax,[0xfffc]` can be encoded either as `67 c4 06 fc ff` or `c4 05 fc ff 00 00`. Both of these encodings will load EAX from ds:[0xfffc], but - the first one will load ES from ds:[0] while the second one will load ES from ds:[0x10000]. Other instructions affected by this issue include wide-memory-operand x87 instructions (e.g. FSAVE, FLDENV, FBSTP) and the 80286 protected-mode instructions (e.g. SGDT, LIDT).
* Shift instructions: `SHL al,1` can be encoded as either `c0 e0 01` or `d0 e0`. These are not equivalent - the `c0 e0 01` form leaves the OF flag unmodified, while `d0 e0` modifies the OF flag depending on result. This issue also applies to SHR and SAR, but not ROL/ROR/RCL/RCR. (Some tools handle this issue by treating `d0 e0` and similar encodings as 1-argument instructions - `SHL al`)

The use of 66/67 type prefixes to shorten instructions also have a performance issue on Intel CPUs, where they can act as Length-Changing Prefixes, which will cause a multi-cycle decode stall if the instruction is not already in the uop cache ( see e.g. https://stackoverflow.com/questions/65530097/does-a-length-changing-prefix-lcp-incur-a-stall-on-a-simple-x86-64-instruction )

**Comment by mappzor** [comment]
Note for future reference: this issue applies only to situations where sizing hints were not provided. Default behavior in such case is to prefer shorter instruction size above everything else and that might result in unusual matches. Improvement opportunity here is to change this behavior, so default address/operand size is prioritized depending on machine mode and instruction.

@tremalrik:
 > For push 1cc, the encoding 66 68 cc 01 will push 2 bytes on the stack in both 32-bit and 64-bit mode, while 68 cc 01 00 00 will push 4 bytes in 32-bit mode and 8 bytes in 64-bit mode; as such 66 68 cc 01 seems quite unsafe.

Explained above.

> Near branch instructions in 32-bit mode can take a 66h prefix to cut the offset from 4 to 2 bytes, however this has the side effect of ANDing IP with 0xFFFF as part of the branch instruction. (The exception to this is XBEGIN, which doesn't do this truncation and thus safely can use the 66h prefix to cut the immediate-size.)

Encoder already doesn't allow that.

> For e.g. mov [0x12345678],eax, in 64-bit mode, it is safe to use the Direct-Offset encoding with 67h prefix to cut length, resulting in 67 a3 78 56 34 12. However, the Direct-Offset encoding does not work with the xreleaseprefix: xrelease mov [0x12345678],eax cannot be encoded as f3 67 a3 78 56 34 12 but must instead be encoded with something like f3 88 04 25 78 56 34 12.

Encoder will respect prefix requirements, so we are good here.

> In 32-bit mode, using the 67h prefix to encode a memory load/store with an immediate address less than 64K is usually safe - e.g. les eax,[0x10] can safely be encoded as 67 c4 06 10 00 which is 1 byte shorter than c4 05 10 00 00 00. However, this becomes unsafe near the end of the 64K region, especially for instructions that take multipart memory arguments. E.g. les eax,[0xfffc] can be encoded either as 67 c4 06 fc ff or c4 05 fc ff 00 00. Both of these encodings will load EAX from ds:[0xfffc], but - the first one will load ES from ds:[0] while the second one will load ES from ds:[0x10000]. Other instructions affected by this issue include wide-memory-operand x87 instructions (e.g. FSAVE, FLDENV, FBSTP) and the 80286 protected-mode instructions (e.g. SGDT, LIDT).

I think it's fair to assume correct memory management is responsibility of the user. This affects only a handful of rarely used instructions in very specific conditions.

> Shift instructions: SHL al,1 can be encoded as either c0 e0 01 or d0 e0. These are not equivalent - the c0 e0 01 form leaves the OF flag unmodified, while d0 e0 modifies the OF flag depending on result. This issue also applies to SHR and SAR, but not ROL/ROR/RCL/RCR. (Some tools handle this issue by treating d0 e0 and similar encodings as 1-argument instructions - SHL al)

According to Intel SDM `SAL/SAR/SHL/SHR 1` modifies OF and `SAL/SAR/SHL/SHR count` leaves it undefined, so current behavior (shorter variant has priority) seems safe. I don't think anyone uses OF after shifts anyway.
