### ISSUE TITLE
Best way to print a single operand?

### ISSUE THREAD

**Issue by gdbinit** [zyantific/zydis#30]
Hi,

I need to have a string output of the second operand of a given instruction. What is the best way to achieve this? Installing a hook at ZYDIS_FORMATTER_HOOK_FORMAT_INSTRUCTION seems the right way but looking at ZydisFormatInstrIntel() code it depends on some internal functions?

I need the operand to easily reassemble into another instruction using Keystone engine.

Thanks,
fG!

**Comment by athre0z** [comment]
Check out [this piece of code in x64dbg](https://github.com/x64dbg/x64dbg/blob/development/src/zydis_wrapper/zydis_wrapper.cpp#L146) – I think it should do what you need.

**Comment by flobernd** [comment]
You might additionally take a look at `ZydisStringInit` and `ZydisStringFinalize` in the `String.h` as we recently switched to a custom string type. Some of the hook constants are outdated in the x64dbg code as well, I guess.

**Comment by gdbinit** [comment]
Thanks for the tips. I noticed that x64dbg code is for older version and master (I am using development branch). I was looking at FormatterHooks.c and I got it working, but it means I need to set formatters for all types and mnemonic, and return ZYDIS_STATUS_SUCCESS for all operands and mnemonic except the one that I am interested at. Looks a bit too complex. Maybe the Zydis API could have a function that allowed to print the mnemonic and each operand without hooking formatters? Or I am still doing this the wrong way?

**Comment by flobernd** [comment]
> Or I am still doing this the wrong way?

Your way should work, but it's easier without actually hooking the functions. Here is an example that works for the latest development build (AVX-512 decorators will not get printed this way):
```c
ZydisStatus printOperand(ZydisFormatter* formatter, 
    const ZydisDecodedInstruction* instruction, const ZydisDecodedOperand* operand)
{
    char buffer[100];
    ZydisString string;
    string.buffer   = buffer;
    string.length   = 0;
    string.capacity = sizeof(buffer) - 1;

    ZydisFormatterHookType type;
    switch (operand->type)
    {
    case ZYDIS_OPERAND_TYPE_REGISTER:
        type = ZYDIS_FORMATTER_HOOK_FORMAT_OPERAND_REG;
        break;
    case ZYDIS_OPERAND_TYPE_MEMORY:
        type = ZYDIS_FORMATTER_HOOK_FORMAT_OPERAND_MEM;
        break;
    case ZYDIS_OPERAND_TYPE_IMMEDIATE:
        type = ZYDIS_FORMATTER_HOOK_FORMAT_OPERAND_IMM;
        break;
    case ZYDIS_OPERAND_TYPE_POINTER:
        type = ZYDIS_FORMATTER_HOOK_FORMAT_OPERAND_PTR;
        break;
    default:
        return ZYDIS_STATUS_INVALID_PARAMETER;
    }
    // Call `ZydisFormatterSetHook` with `callback` pointing to a `NULL` value to retrieve the 
    // currently used function without replacing it (this gets you the pointer of the internally 
    // used `ZydisFormatOperand*Intel`)
    ZydisFormatterOperandFunc func = ZYDIS_NULL;
    ZYDIS_CHECK(ZydisFormatterSetHook((ZydisFormatter*)formatter, type, (const void**)&func));

    ZYDIS_CHECK(func(formatter, &string, instruction, operand, ZYDIS_NULL));
    ZYDIS_CHECK(ZydisStringFinalize(&string));

    printf(buffer);
    return ZYDIS_STATUS_SUCCESS;
}
```
For the mnemonic you can write similar code that retrieves the functions of `ZYDIS_FORMATTER_HOOK_PRINT_MNEMONIC` and `ZYDIS_FORMATTER_HOOK_PRINT_PREFIXES`.

> it prints the comma if there are more more than one operand

Ouh, that looks like a bug. I will take a look at it.

**Comment by flobernd** [comment]
It indeed was a bug. Could you try out your solution after pulling my latest commit (https://github.com/zyantific/zydis/commit/ca9898fa42be5d7fe498cc00dea5b303370e0f65)?

**Comment by gdbinit** [comment]
Yep, the commit does solve the issue (still prints that extra space from the first append but that's fine for my case):
second operand:  [rcx+r9*1+0x04]

Going to check the second commit, looks like a cleaner solution :-)

**Comment by flobernd** [comment]
> The printOperand() looks to be the best one because you can pass it directly the operand you need

It's easy to use, but I'm not sure if it is the best solution as there might be some glitches with this code. E.g. you won't be able to print a mask-register operand encoded in `EVEX.aaa`/`MVEX.kkk` because the internal code omits these operands and prints them as decorator. In addition no AVX-512 and KNC decorators will be printed by using this code (could be unexpected for some users).

I'm perhaps going to add a `ZydisFormatterFormatOperand` function to the public API, but I have to re-think some things first and I definitely need a good documentation for this function.

**Comment by flobernd** [comment]
Feel free to test my latest commit (https://github.com/zyantific/zydis/commit/bbb864561d38130066528dc3a4db4a85c712c197).

I added single operand formatting functions to the public interface and introduced `ZYDIS_STATUS_SKIP_OPERAND` (this allows users to return actual error codes in `PRE_OPERAND`/`POST_OPERAND`).

The above code missed the size cast for memory operands btw.

**Comment by gdbinit** [comment]
Got busy with something else, let me see if I can test it tomorrow (the commit looks good).
Btw thanks for the prompt support. Great to see Zydis project active!
