### ISSUE TITLE
Compilation Error When -DZYDIS_MINIMAL_MODE Is Enabled

### ISSUE THREAD

**Issue by matthew-olson-intel** [zyantific/zydis#305]
When I compile Zydis while passing `-DZYDIS_MINIMAL_MODE` to CMake, I get the following error:

```
src/Decoder.c:4390:16: error: ‘ZydisInstructionDefinitionLEGACY’ {aka ‘const
struct ZydisInstructionDefinitionLEGACY_’} has no member named ‘no_compat_mode’
 4390 |         if (def->no_compat_mode &&
      |                ^~
```

This appears to be the only compilation error, as simply wrapping this condition in `#ifndef ZYDIS_MINIMAL_MODE` fixes it; of course, that just removes the check entirely, which I'm sure isn't ideal.

There are, as well, a lot of warnings thrown about `src/Generated/InstructionDefinitions.inc`, but they don't look like they'd affect functionality.

Thanks,
Ben Olson

**Comment by athre0z** [comment]
Which commit are you trying to build, and on what platform? Latest master with minimal mode enabled is building just fine for me using the following CMake invocation:

```
cmake -DZYDIS_MINIMAL_MODE=ON -DZYDIS_FEATURE_ENCODER=OFF ..
```

**Comment by flobernd** [comment]
The initializer value for this field should be wrapped the ZYDIS_NOT_MIN() macro.

If that's not the case for your local version, your workaround will cause problems as the initializer values in the InstructionDefinitions.inc will shift.

**Comment by matthew-olson-intel** [comment]
Ach, you're right: I was looking at a tagged version, forgetting that I had added the tagged version as a submodule (not `master`, as I assumed).  Sorry about that.
