### ISSUE TITLE
fatal error: 'ZydisExportConfig.h' file not found

### ISSUE THREAD

**Issue by udishamir** [zyantific/zydis#31]
Hi,

The build went well on OSX High Sierra, when trying to compile one of the examples iv'e noticed that 
the install creates additional "include" under:

 "/usr/local/include/<include>".

When copying "Zydis" headers under "/usr/local/include" manually it fails with ZydisExportConfig.h

fatal error: 'ZydisExportConfig.h' file not found, did you ever encountered such an issue ?

That indeed fixed the problem, the next issue is:

When trying to compile one of your example, please see bellow:

Cheers,

/usr/local/include/Zydis/Defines.h:35:10: fatal error: 'ZydisExportConfig.h' file not found
#include <ZydisExportConfig.h>
^~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by athre0z** [comment]
Hi, thanks for reporting! Please check [my commit on `develop`](https://github.com/zyantific/zydis/commit/320a90db537687268a85d0d0d4092e7d9666d6c7), it should resolve the issue.

**Comment by athre0z** [comment]
Quoting from [commit comment](https://github.com/zyantific/zydis/commit/320a90db537687268a85d0d0d4092e7d9666d6c7#commitcomment-27378431):
> That indeed fixed the problem, the next issue is:
>
>When trying to compile one of your example, please see bellow:
>
>Cheers,
>
>/usr/local/include/Zydis/Defines.h:35:10: fatal error: 'ZydisExportConfig.h' file not found
>#include <ZydisExportConfig.h>
>^~~~~~~~~~~~~~~~~~~~~
>1 error generated.

How are you trying to build the examples? They are supposed to be built through the CMakeList, when `ZYDIS_BUILD_EXAMPLES` is enabled, which is the default.

**Comment by athre0z** [comment]
Nevertheless, it is an issue that this particular include files doesn't get installed by the install rules.

**Comment by udishamir** [comment]
Great, so when copying 'ZydisExportConfig.h' to the <Zydis> all u need is to change /usr/local/include/Zydis/Defines.h line 35 and replace to quotes (as calling the header file locally not absolute) and it get solved.

Thanks

**Comment by athre0z** [comment]
Yeah, but people shouldn't have to go through manually changing anything. I pushed [another commit](https://github.com/zyantific/zydis/commit/fca59443d1e2b60562907fa048e47a50385fbc0d) that now also installs this previously missing file.

**Comment by udishamir** [comment]
Thanks !
