### ISSUE TITLE
Maybe wrong output for 66480F50C1 (movmskpd rax, xmm1)

### ISSUE THREAD

**Issue by Fibergeek** [zyantific/zydis#312]
Hello,

I get a wrong output for the movmskpd instruction.
To verify this issue I used the latest Zydis source code and compiled ZydisInfo.

ZydisInfo.exe -64 "66480F50C1"

It's output is:
movmskpd eax, xmm1

However, IDA disassembles this instruction as 
movmskpd rax, xmm1

Also assembling this instruction using NASM yields:
    660F50C1                movmskpd eax, xmm1
    66480F50C1            movmskpd rax, xmm1

Is this an error Zydis or are the other tools wrong about this?

**Comment by flobernd** [comment]
Hey, thanks for reporting this case.

I think Zydis is wrong here according to the SDM, this instruction is defined as:
```
66 0F 50 /r MOVMSKPD reg, xmm
```

and

> The default operand size is 64-bit in 64-bit mode.

This means `660F50C1` in 64-bit mode should always result in `movmskpd rax, xmm1`.

However honoring the REX.W inbetween the mandatory `66` and the opcode `0FF5` like NASM seems to do it in your 2nd example, looks pretty suspicious to me.

**Comment by flobernd** [comment]
I did further research and it seems the SDM "recently" got updated for `MOVMSKPS` and `MOVMSKPD`. 

In old versions (e.g. https://c9x.me/x86/html/file_module_x86_id_192.html) were explictily using `r32` destination operands while new versions are using `reg` (32- or 64-bit) with the addition of a default 64-bit operand size in 64-bit mode.

**Comment by flobernd** [comment]
@Fibergeek I had an internal discussion with @mappzor and we came to the conclusion that either way semantics do not change. The instruction always writes a 16-bit mask and zeroes the upper bits of the containing 32/64-bit register (depending on machine mode) regardless of the effective operand-size.

I pushed a change which imho makes Zydis operate more closely to the behavior described in the SDM Vol2:

```
mode 16 -> EAX
mode 32 -> EAX
mode 64 -> RAX
```

Sadly other places (e.g. Vol1) still refers to the destination register as `r32`. I will ask the current maintainers of XED for clarification and might change the behavior again.

**Comment by Fibergeek** [comment]
Thank you for looking into this.

I was looking also at the AMD Programmer's guide (https://www.amd.com/system/files/TechDocs/26568.pdf)
> 
> The source operand is an XMM register. The destination can be either a 64-bit or a 32-bit general pur-
> pose register. 

I have the answers I need for my own project. Thanks again.

**Comment by ZehMatt** [comment]
> @Fibergeek I had an internal discussion with @mappzor and we came to the conclusion that either way semantics do not change. The instruction always writes a 2/4-bit mask and zeroes the upper bits of the containing 32/64-bit register (depending on machine mode) regardless of the effective operand-size.
> 
> I pushed a change which imho makes Zydis operate more closely to the behavior described in the SDM Vol2:
> 
> ```
> mode 16 -> EAX
> mode 32 -> EAX
> mode 64 -> RAX
> ```
> 
> Sadly other places (e.g. Vol1) still refers to the destination register as `r32`. I will ask the current maintainers of XED for clarification and might change the behavior again.
> 
> **Reminder for myself**: Change `vmovmskpd/vmovmskps` accordingly.

I think this caused a regression, the encoder seems to fail trying to encode:
```
66 0F 50 CA | movmskpd ecx, xmm2
```
this is part of the Zasm tests and fails now.
I looked into why the encocder rejects it
```
else if (match->eosz64_forbidden && match->eosz == 64)
```
is the condition that fails.

**Comment by flobernd** [comment]
As the semantics do not change anyways, I will change back the operand to `GPR_OSZ_32_32_64` and the default operand size to 32. This way the encoder should accept 32- and 64-bit registers in 64-bit mode.

**Comment by flobernd** [comment]
@ZehMatt Fix is pushed.
