### ISSUE TITLE
Question: source for *.inc files in src/Generated

### ISSUE THREAD

**Issue by hainest** [zyantific/zydis#313]
Having machine-readable instruction tables is a real luxury. I'm curious where they came from. Are they hand-generated? Did they come from parsing LLVM's tablegen output?

**Comment by athre0z** [comment]
They are generated from our instruction database that lives here: https://github.com/zyantific/zydis-db

The database is composed from various sources, the most important of which is Intel XED. We have also added and fixed many things manually over the years.
