### ISSUE TITLE
Is there a way to set displacement width when using encoder?

### ISSUE THREAD

**Issue by Inori** [zyantific/zydis#314]
Is there a way to force the displament width like XED:
`void xed_encoder_request_set_memory_displacement(xed_encoder_request_t* p, xed_int64_t memdisp, xed_uint_t nbytes);`
Sometimes it's a requirement to get proper instruction size.
Currently I only came a way which is set a large displacement value (e.g. 0xFFFFFFFF) first then edit the generated binary bytes manually to the desired value.

**Comment by mappzor** [comment]
There is no option to specify physical size for displacements/immediates. You need to either use your patching approach or pad with NOPs.
