### ISSUE TITLE
Fix gitter link in README.md

### ISSUE THREAD

**Issue by insolor** [zyantific/zydis#32]
Currently the link given there leads to nonexistent page (404 error)

![714262f2-98b0-4e2c-bff6-167485d48d63](https://user-images.githubusercontent.com/2442833/35990494-3713a1e4-0d15-11e8-9a06-99d7c9b85464.png)

**Comment by athre0z** [comment]
Already fixed on [`develop`](https://github.com/zyantific/zydis/tree/develop). I'll leave this open until it's on master.
