### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by nlepleux** [zyantific/zydis#321]
Just a little typo that prevents making a perfect copy/pasta to install zydis

vcpkg part is currently:
`git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
vcpkg install zydis`

it should be:
`git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install zydis`

you could also specify (because those genius at MS still use x86 as default)
`git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
./bootstrap-vcpkg.sh
./vcpkg integrate install
./vcpkg install zydis:x64-windows`

**Comment by athre0z** [comment]
Fixed, thank you!
