### ISSUE TITLE
ZydisDecodedOperand data type

### ISSUE THREAD

**Issue by Tsn0w** [zyantific/zydis#322]
Hi, 
Why `ZydisDecodedOperand` store the following fields as different fields and not inside a union:
- reg
- mem
- ptr
- imm

As I understand, Operand can be only one of this values, so it will save memory.

**Comment by flobernd** [comment]
Hi there,

you are completely right. In the initial implementation we choose to not use `union`s in our public structs to support more foreign language bindings.

There is a discussion going on in this recent issue:
https://github.com/zyantific/zydis/issues/280

So apparently most common languages are supporting unions natively and for those who don't, there usually are workarounds. This means it's pretty likely for us to change our public interface to use `union`s on all applicable places in the future.

**Comment by Tsn0w** [comment]
Thanks for the fast response!
