### ISSUE TITLE
Object file name conflict between libZydis.a and libZycore.a

### ISSUE THREAD

**Issue by bjorn3** [zyantific/zydis#343]
Both archives contain a file called String.c.o. Some archive file writers don't allow multiple files with the same name, which makes it impossible to merge libZydis.a and libZycore.a into a single archive. This seems to have been the root cause of https://github.com/bjorn3/rustc_codegen_cranelift/issues/1228. I could work around it by renaming the object files in rustc_codegen_cranelift, but for better compatibility with different toolchains it would be nice if one of the String.c files would be renamed to solve this conflict or possibly have all files of either library prefixed.

**Comment by athre0z** [comment]
Hmmm. From the top of my head, it would seem to me that this is an issue with the linker rather than with our projects, no? The only way to consistently avoid that issue would be to prefix the source files with a sort of namespace, which I've rarely ever seen to be done by any C projects.

**Comment by bjorn3** [comment]
The reason it was a problem in this case is because one of rustc_codegen_cranelift's dependencies didn't correctly handle writing symbol tables when multiple archive members have the same name, which causes a problem when it merges all static library together with the local object files into a single .rlib archive. While most archive writers correctly handle this, some tools don't like libtool (https://github.com/rust-lang/compiler-builtins/issues/443#issuecomment-981070154). In addition it becomes rather hard to extract a specific member of an archive if multiple members have the same name. This conflict is generally not an issue for C libraries as archives are rarely merged together. However rust bundles all static libraries into the rlib that requires them by default in which case you can get multiple archive members with the same name.

**Comment by athre0z** [comment]
Would it not be better to change the code that bundles up the static libraries and perhaps prepend the members within with some sort of prefix (e.g. the shared library name) while merging? I'm not sure where this name is actually used and whether altering it like this will break other things.

To be clear: I'm not strictly opposed to namespacing our source files, but this seems to me like something that you're guaranteed to run into with a LOT of other C projects as well.

**Comment by bjorn3** [comment]
I changed rustc_codegen_cranelift to add an incrementing prefix in case of conflicts, so the immediate problem for me is solved. If you prefer not fixing the conflicting names on zydis' end, I am fine with closing this issue.

**Comment by flobernd** [comment]
I don't like the idea of prefixing source files at all tbh.

As this really seems to be an issue specific to the one toolset you are using, I think it should be fixed on their side (I read that's not possible due to some kind of backwards compatibility) or with a workaround like yours.
