### ISSUE TITLE
How to install Zydis with specific tag version?

### ISSUE THREAD

**Issue by yszhou2019** [zyantific/zydis#349]
I am one contributor of the xmake community (xmake is an open source compilation & configuration & package management tool), and I recently working at including zydis in xmake-repo (xmake official repository)

In this process,  i need to collect specific versions and set the corresponding installation script.

But for example, in the zip or tar.gz of the v3.2.1 version, https://github.com/zyantific/zydis/archive/refs/tags/v3.2.1.zip, since there is no .git directory in the folder after decompression, the build and install process cannot be completed through CMakeLists.txt. https://github.com/zyantific/zydis/blob/4022f22f9280650082a9480519c86a6e2afde2f3/CMakeLists.txt#L60-L64

So I'm wondering, how can I build this repo correctly without following `git clone --recursive` to clone the repo?

**Comment by yszhou2019** [comment]
emm, acturally now i can patch CMakeLists.txt like the picture bellow. In this way, i can build and install different verions of zydis.zip without using instruction `git clone --recursive`
<img width="565" alt="image" src="https://user-images.githubusercontent.com/59953951/174472581-f75429c6-012b-4652-adf6-cc99b434035c.png">

Still thanks~

**Comment by yszhou2019** [comment]
or, i can patch CMakeLists.txt like this. it works fine.
<img width="556" alt="image" src="https://user-images.githubusercontent.com/59953951/174472814-0f010bd0-f95d-40e4-aeb2-93ce5663c2e0.png">

**Comment by flobernd** [comment]
Hey! 

I would rather suggest leaving the Cmake file alone and instead pull the submodule using a custom setup script. Afterwards set the ZYDIS_ZYCORE_PATH in the Cmake invocation (only possible for the latest Zydis). 

Please be aware that different versions of Zydis are using different versions of Zycore and the Cmake files of both projects might change from version to version.

**Comment by yszhou2019** [comment]
> Hey!
> 
> I would rather suggest leaving the Cmake file alone and instead pull the submodule using a custom setup script. Afterwards set the ZYDIS_ZYCORE_PATH in the Cmake invocation (only possible for the latest Zydis).
> 
> Please be aware that different versions of Zydis are using different versions of Zycore and the Cmake files of both projects might change from version to version.

I got it. Thanks~
