### ISSUE TITLE
Windows Wsign-compare warning in SharedData.c

### ISSUE THREAD

**Issue by rvandermeulen** [zyantific/zydis#354]
This is with v3.2.1, but as far as I can tell, the code is the same on tip. We can suppress the warning if this isn't something you're inclined to fix, but filing in case you are 😄 
```
SharedData.c(165,25): error: comparison of integers of different signs: 'ZydisInternalElementType' (aka 'enum ZydisInternalElementType_') and 'unsigned int' [-Werror,-Wsign-compare]
    ZYAN_ASSERT(element < ZYAN_ARRAY_LENGTH(lookup));
    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Defines.h(268,42): note: expanded from macro 'ZYAN_ASSERT'
#   define ZYAN_ASSERT(condition) assert(condition)
                                  ~~~~~~~^~~~~~~~~~
windows kits/10/include/10.0.17134.0/ucrt/assert.h(33,17): note: expanded from macro 'assert'
            (!!(expression)) ||                                                              \
                ^~~~~~~~~~
1 error generated.
```

**Comment by athre0z** [comment]
We can definitely fix that on our side, no need to suppress the warning. Out of curiosity, what is the build setup that you're using there? You mention that you're on Windows, but the compiler arguments are printed with dashes (`-Werror` etc.), so probably MinGW? We should probably have something like this in our CI as well.

**Comment by rvandermeulen** [comment]
This was with clang-cl 14.0.5
