### ISSUE TITLE
Invalid decoding of jmp cs:0x1122334455667788

### ISSUE THREAD

**Issue by HoShiMin** [zyantific/zydis#36]
I have a bug with decoding this machine code (x64):
FF 25 00 00 00 00 11 22 33 44 55 66 77 88
Zydis decodes only first part (FF 25 00 00 00 00) as jmp cs:RelativeOffset32 (and second part with 8-bytes address as junk - another instructions). But it should be a single instruction with absolute 8-byte address -jmp cs:AbsoluteAddress64.

**Comment by athre0z** [comment]
Hm, yeah, that looks wrong indeed. On AMD64, being `FF /4`, this should be decoded as `JMP r/m64` according to Intel SDM.

<img width="820" alt="screen shot 2018-03-07 at 09 37 05" src="https://user-images.githubusercontent.com/6553158/37083895-38908442-21f1-11e8-8112-a5a82399b32a.png">

IDA and XED decode it the same way, however. Perhaps there's something that I'm missing in the documentation — or, we're just all decoding it incorrectly.

**Comment by athre0z** [comment]
Mh, yeah, never mind, it's decoded correctly.

`r/m64` only refers to the logical size of the memory operand — not the size of the displacement. There is no jump instruction with a "RelativeOffset64" in the x86-64 instruction set. The instruction you provided is `RIP`-relative, but the offset/displacement size is 32 bit.

**Comment by chaplja** [comment]
I think you're misinterpreting the manual and that everyone mentioned decodes it correctly. It's an absolute indirect jump, that doesn't mean that an absolute address is encoded within the instruction, just that the address pointed to by the memory operand is absolute. Memory operands in 64bit mode treat 32bit displacement as RIP relative.

**Comment by flobernd** [comment]
Correct. There is no way to encode a 64-bit displacement using the `Mod/Rm` (technically impossible.)

**Comment by HoShiMin** [comment]
But wait.
I use this form to splice some functions, so you can check that it really exists and works correctly.
Look at this sample:
```
void a() {
	printf("a\r\n");
}

void b() {
	printf("b\r\n");
}

void fill_trampoline(unsigned char* trampoline, void* address) {
	*(short*)trampoline = 0x25FF;
	*(int*)(trampoline + 2) = 0x00000000;
	*(void**)(trampoline + 6) = address;
}

int main(int argc, char* argv[]) {
	unsigned char trampoline[14];
	fill_trampoline(trampoline, b);
	DWORD old_protect;
	VirtualProtect(a, sizeof(trampoline), PAGE_EXECUTE_READWRITE, &old_protect);
	memcpy(a, trampoline, sizeof(trampoline));
	a(); // Intercepted function
}
```
And you will see "b". So, this form works.

**Comment by flobernd** [comment]
Your are mixing up code (the `JMP` instruction) and data (your jump target address) to emulate a 64-bit direct jump.

`FF 25 00 00 00 00` is decoded as `jmp qword ptr ds:[0x0000000000000006]` (absolute) or `jmp qword ptr ds:[RIP+0x00]` (RIP-relative). The memory operand of these two equivalent textual representations refers to your `(trampoline + 6)` (the absolute target address of your trampoline).

**Comment by HoShiMin** [comment]
Oh, yes, now I understand! And it breaks the next decoding as this address interprets as junk. So, what about make dynamical resolution of given address if it in bounds of given code buffer?

**Comment by flobernd** [comment]
> So, what about make dynamical resolution of given address if it in bounds of given code buffer?

This would rather be the task of a high-level disassembler (in-depth analysis, construction of callgraphs, ...). Zydis decodes instructions but does not interpret them with reference to a certain context.

**Comment by HoShiMin** [comment]
Thanx, anyway!

**Comment by flobernd** [comment]
You are welcome!
