### ISSUE TITLE
Installing using vcpkg SharedTypes.h missing items

### ISSUE THREAD

**Issue by RadonCoding** [zyantific/zydis#369]
I installed using vcpkg and the following things are missing from SharedTypes.h `ZYDIS_STACK_WIDTH_64` `ZYDIS_MAX_OPERAND_COUNT_VISIBLE` `ZYDIS_DFLAG_VISIBLE_OPERANDS_ONLY`

**Comment by flobernd** [comment]
I assume you are trying to test the example code from the readme? 

Our master branch contains the bleeding edge (unreleased) version 4.x. You need to check out the latest v3.x tag and look at the examples there.

**Comment by RadonCoding** [comment]
Ah i had the feeling it was just me being stupid thank you

**Comment by RadonCoding** [comment]
Is is possible for me to use the unreleased version with vcpkg?
