### ISSUE TITLE
LNK2001 static linking

### ISSUE THREAD

**Issue by RadonCoding** [zyantific/zydis#370]
I built the repository using CMake and included it in my project. When trying to build i get the following errors
`error LNK2001: unresolved external symbol __imp_ZydisDecoderInit`
`error LNK2001: unresolved external symbol __imp_ZydisDecoderDecodeFull`

This is my directory setup:
```bash
C:.
└───zydis
    ├───include
    │   ├───Zycore
    │   │   ├───API
    │   │   └───Internal
    │   └───Zydis
    │       ├───Generated
    │       └───Internal
    ├───lib
    └───src
        ├───Zycore
        │   └───API
        └───Zydis
            └───Generated
```

Here are my project settings:
```bash
Additional Include Directories: $(SolutionDir)Dependencies\zydis\include
Additional Library Directories: $(SolutionDir)Dependencies\zydis\lib
Additional Dependencies: Zycore.lib;Zydis.lib;
```

**Comment by flobernd** [comment]
@RadonCoding Could you please try to set `ZYDIS_STATIC_BUILD` in the compiler commandline flags?

**Comment by RadonCoding** [comment]
Sorry where do i set the compiler commandline flags?

**Comment by flobernd** [comment]
You can use `-D ZYDIS_STATIC_BUILD` in the command line or set it in the project options in Visual Studio like this:

![](https://nextcloud.flobernd.de/s/MQZcdcWaRwDttgH/preview)

**Comment by RadonCoding** [comment]
Thanks for the fast response. That worked!
