### ISSUE TITLE
Mnemonic RSM formatted as ret?

### ISSUE THREAD

**Issue by tripleslash** [zyantific/zydis#38]
Hi, I was writing some code to check whether an instruction is some kind of return opcode and I noticed that ZydisMnemonicGetStaticString(ZYDIS_MNEMONIC_RSM) == "ret". Why does it not return "rsm"?

**Comment by athre0z** [comment]
What version / commit are you using? Seems to be working fine, returning "rsm", on `HEAD` of `develop` and `master`.

**Comment by tripleslash** [comment]
![image](https://user-images.githubusercontent.com/4272703/38437826-03324344-39d9-11e8-8739-8493553d9839.png)

I'm using a freshly built fork of 2852492484c9053c26a3655fa2efdbb4d16aa9de

**Comment by tripleslash** [comment]
Also I found this example here: https://github.com/zyantific/zydis/blob/master/examples/ZydisPE.c

However the API version that this example uses seems to be outdated? What I'm looking for is a custom symbol resolver. I would like to have my output formatted like:

004A7390  call HelloWorld.main+0
...

**Comment by athre0z** [comment]
Oh, yeah, that file is indeed **very** outdated — that API is from a very early version in-dev of v2. Looks like we forgot to put it into the `CMakeLists` file, thus never realizing it broke. We dropped the direct support for symbols resolves in favor of a more advanced formatter hook system. You can achieve the desired behavior using `ZydisFormatterSetHook` and `ZYDIS_FORMATTER_HOOK_FORMAT_OPERAND_(MEM|IMM)`.

Regarding the RSM issue: any chance your object files and headers are out of sync? Possibly you accidentally deleted a few lines in the enum, having the `RSM` move into the spot of `RET`? The mnemonic string functions are just simple range-check & array index access functions, there's really not a whole lot of stuff that could go wrong there.

<img width="1046" alt="screen shot 2018-04-06 at 20 58 41" src="https://user-images.githubusercontent.com/6553158/38439793-49b34ad8-39df-11e8-848c-f95ca9b18a2c.png">

**Comment by tripleslash** [comment]
Oh that makes sense. Seems I accidentally copied header files from a wrong version to the project while using a newer object file :(

Sorry but thank you for the help!

**Comment by athre0z** [comment]
Haha, no problem!

**Comment by flobernd** [comment]
For a custom symbol resolver use `ZYDIS_FORMATTER_HOOK_FORMAT_ADDRESS` instead of `ZYDIS_FORMATTER_HOOK_FORMAT_OPERAND_(MEM|IMM)`. It's much easier this way.
