### ISSUE TITLE
zydis's port int vcpkg is misconfigured

### ISSUE THREAD

**Issue by r4ve1** [zyantific/zydis#388]
I installed `zydis` and `zycore` by running `vcpkg install zydis:x64-windows`, but when I want to use these packages in my CMake project with `find_package(zycore REQUIRED)` and `find_package(zydis REQUIRED)`, CMake report errors like this
<img width="502" alt="image" src="https://user-images.githubusercontent.com/59314380/195038363-f3cb45bb-adbe-4efb-9a57-9dac95085f0d.png">

And I looked into `zydis`'s install directory, `zydis-config.cmake` is placed under the `zydis` subfolder of `${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/share/zydis`, that's why cmake can't find it. 

Desired behavior: 
`zycore` and `zydis` should be placed separately under vcpkg's folder
<img width="524" alt="image" src="https://user-images.githubusercontent.com/59314380/195039264-b598f29d-03c3-459d-b497-147b0a305aa9.png">

**Comment by flobernd** [comment]
Hi! Thanks for reporting this.

According to our README:

> The Zydis port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.

I have to admit that I don't have any experience with `vcpkg`. I will leave this issue open for a while in case we can support resolving this problem on our side.

**Comment by r4ve1** [comment]
I'm also not very familiar with vcpkg 🤣 that's why I didn't create a pull request directly in vcpkg's repository

**Comment by r4ve1** [comment]
After spending half a day on vcpkg, I figured a way to fix this issue.
My idea is to add `Zycore` as a new port to vcpkg and declare it as `Zydis`'s dependency, this works perfectly on my own fork of vcpkg. 
I have created pull requests to vcpkg, waiting for its maintainers to merge my commits 😃

**Comment by flobernd** [comment]
Thanks for taking care! I was under the impression that Zycore already is an independent module on vcpkg.

**Comment by athre0z** [comment]
Ah, nice! We originally argued against making Zycore a separate port because it neither had version numbers on its own, nor did it have any API or ABI stability guarantees. This has since changed, so making it a separate port is indeed probably for the best. Thanks for investigating and fixing this!

**Comment by flobernd** [comment]
VCPKG PR for reference: https://github.com/microsoft/vcpkg/pull/27195

**Comment by alandtse** [comment]
While this appears to resolve find_package on zycore, zydis still has the problem because it's zydis-config.cmake is in a subdirectory `zydis/zydis`.

The simple workaround is to copy all the .cmake files down to the root.
