### ISSUE TITLE
 why there are so many error when I build them

### ISSUE THREAD

**Issue by RachelWealth** [zyantific/zydis#393]
I have used vs2013,2015,2019, the results are all the same.
![image](https://user-images.githubusercontent.com/74123687/196062018-3ebdfe4e-24e9-4dc4-b6c0-3892381a19bd.png)

**Comment by mappzor** [comment]
First of all it seems that you aren't building Zydis but x64dbg (which includes an old version of Zydis) and that's a rather important thing to mention. Probably you should check if you cloned the repo correctly (with submodules) and/or include path configured for the project. None of Zydis types is actually recognized by the compiler, so it's a project configuration error.

**Comment by athre0z** [comment]
Closing since this is clearly not a Zydis issue.
