### ISSUE TITLE
Encoder RETF instruction issue plus some more…

### ISSUE THREAD

**Issue by behnamshamshirsaz** [zyantific/zydis#398]
1) It seems retf instruction is not implemented.
2) jmp far instruction in mode 5 (real) is not encodable with offset value other than 0
3) addressing modes [basereg+indxreg] & [basereg+indxreg+offset] won’t encode on inc, dec and push instructions. May be some others too. (One Operand)
4) it seems Push instruction with immediate value is not encodable.

**Comment by flobernd** [comment]
Hi, could you please show the code that you used to encode these instructions?

**Comment by mappzor** [comment]
As mentioned by @flobernd, please provide code to show how you construct your encoder requests. Below you can find my successful attempts to encode those instructions. I assumed 64-bit mode unless otherwise specified. All examples start with:
```c
ZydisEncoderRequest req;
memset(&req, 0, sizeof(req));
```
1. Zydis doesn't have a separate mnemonic for far returns.
```c
req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
req.mnemonic = ZYDIS_MNEMONIC_RET;
req.branch_type = ZYDIS_BRANCH_TYPE_FAR;
// Output: CB (ret far)
```
2.
```c
req.machine_mode = ZYDIS_MACHINE_MODE_REAL_16;
req.mnemonic = ZYDIS_MNEMONIC_JMP;
req.branch_type = ZYDIS_BRANCH_TYPE_FAR;
req.operand_count = 1;
req.operands[0].type = ZYDIS_OPERAND_TYPE_POINTER;
req.operands[0].ptr.segment = 0x1234;
req.operands[0].ptr.offset = 0x5678;
// Output: EA 78 56 34 12 (jmp far 0x1234:0x5678)
```
3.
```c
req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
req.mnemonic = ZYDIS_MNEMONIC_INC;
req.operand_count = 1;
req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
req.operands[0].mem.base = ZYDIS_REGISTER_RAX;
req.operands[0].mem.index = ZYDIS_REGISTER_RCX;
req.operands[0].mem.scale = 1;
req.operands[0].mem.size = 4;
// Output: FF 04 08 (inc dword ptr ds:[rax+rcx*1])
```
4.
```c
req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
req.mnemonic = ZYDIS_MNEMONIC_PUSH;
req.operand_count = 1;
req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
req.operands[0].imm.u = 0x11223344;
//Output: 68 44 33 22 11 (push 0x11223344)
```

**Comment by behnamshamshirsaz** [comment]
Thanks a lot florian, I’ll chek far ptr problem for ret and jmp in real mode. Actually I’m converting and implementing ZyDis code into special environment in x86 32 bits assembly language and because of it’s special mode & situation the calling code won’t be usable for you for testing. I found the main problem about addressing modes [base+index+…], Actually the base field and index field are exchanged in encoder request structure ! (Main Zydis code considers Base[0] as Index[0] and vice versa !) check it 😉

**Comment by flobernd** [comment]
@behnamshamshirsaz 

> Actually the base field and index field are exchanged in encoder request structure ! (Main Zydis code considers Base[0] as Index[0] and vice versa !) check it

Could you please elaborate? I don't really get what you mean by that 😋

**Comment by behnamshamshirsaz** [comment]
Actually I’m writing a parser for zydis encoder in x86 assembly. Some errors in code and bad parameter passing in Encoder Request structure misguided me. Code corrected and everything is set 😎 thanks a lot 🙏❤️
