### ISSUE TITLE
Failure to compile on Red Hat Enterprise/CentOS

### ISSUE THREAD

**Issue by gdbinit** [zyantific/zydis#40]
Hi,

CentOS 7 and equivalent Red Hat Enterprise still ship very old GCC on default install and Zydis fails to compile. Essentially the -std=c99 option is required, which is set on Zydis Cmake files for the debug build but not default one. You might want to pass that option by default or detect RH/CentOS and set it.

Other than newer Cmake version and that option it compiles and works fine there.

Best,
Pedro

**Comment by athre0z** [comment]
Thanks for reporting this issue! [Implemented on develop](https://github.com/zyantific/zydis/commit/a343d9062831efef10b8a6752fc2f5b011a374d9), port on future branch will follow. Please let me know if it works on your Red Hat machine as well — I only got to test it in a Docker CentOS container.

**Comment by gdbinit** [comment]
Confirmed to work on a Red Hat Enterprise Server 7.1.
