### ISSUE TITLE
ZydisDecodedInstruction_ in V4 and V3

### ISSUE THREAD

**Issue by OSPFvX** [zyantific/zydis#410]
Hello everyone!

In the Zydis v3.0.0 - v3.2.1 in the documentation in the section "Zydis/Data Structures/ZydisDecodedInstruction_/" there is "operands"(https://doc.zydis.re/v3.2.1/html/structZydisDecodedInstruction__#aabe959e75d8b87f4b4c1a77d5922b31d) , but in version v4.0.0-v4.0.0-rc1 in the section "Zydis/Data Structures/ZydisDecodedInstruction_/" there is no "operands", where the "operands" from ZydisDecodedInstruction_ in V4 version?
https://ibb.co/kGsh16Z
https://ibb.co/2sjrg9s

At the moment, I can only observe the selection of operands in the Encoder, but where are the "operands" in the Decoder in v4?!
https://ibb.co/3F7WNPg

**Comment by mappzor** [comment]
See [porting guide](https://github.com/zyantific/zydis/blob/master/assets/porting-guide-v3-v4.md)

**Comment by OSPFvX** [comment]
> See [porting guide](https://github.com/zyantific/zydis/blob/master/assets/porting-guide-v3-v4.md)

Is there anywhere I can see examples using the v4 version?

**Comment by mappzor** [comment]
[Examples](https://github.com/zyantific/zydis/tree/master/examples)
Disassemble for `ZydisDecoderDecodeFull`
DisassembleSimple for `ZydisDisassembleIntel`
