### ISSUE TITLE
ZydisV4.0.0-rc1 Encoder

### ISSUE THREAD

**Issue by OSPFvX** [zyantific/zydis#411]
Hello everyone!
All readers with merry Christmas!

And this is another stupid question from a rookie =) I'm sorry if this annoys someone =)

Problem:
I am trying to read the second operand in lea rax, qword ptr ds:[VA] and paste it into JMP VA, but when I do so the code:

      ...
       ZydisEncoderRequest req;
    memset(&req, 0, sizeof(req));
    ...
       ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
           &instruction));
       if (instruction.info.mnemonic == ZYDIS_MNEMONIC_LEA && instruction.operands[1].mem.index == ZYDIS_REGISTER_NONE)
       {
           unsigned int A = instruction.operands[1].mem.disp.value;
           req.operand_count = 1; //<---
           req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;//<---
           req.operands[0].mem.displacement = A;//<---

           uc_mem_read(uc, address + instruction.info.length+TF, data, size);
           int TS = instruction.info.length + TF;

           ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
               &instruction));
           if (instruction.info.mnemonic == ZYDIS_MNEMONIC_XCHG && instruction.operands[0].mem.base == ZYDIS_REGISTER_RSP)
           {
               uc_mem_read(uc, address + instruction.info.length + TS, data, size);
               int TT = instruction.info.length + TS;

               ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
                   &instruction));
               if (instruction.info.mnemonic == ZYDIS_MNEMONIC_RET)
               {

                   req.mnemonic = ZYDIS_MNEMONIC_JMP;//<---
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;//<---

                   ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
                   ZyanUSize encoded_length = sizeof(encoded_instruction);

                   if (ZYAN_FAILED(ZydisEncoderEncodeInstruction(&req, encoded_instruction, &encoded_length)));
                   {
                       puts("Failed to encode instruction");
                   }

                   for (ZyanUSize i = 0; i < encoded_length; ++i)
                   {
                       printf("%02X ", encoded_instruction[i]);
                   }
                   puts("");

               }
           }
       }
    }
I get a "Failed to encode instruction", why?! I'm kind of doing everything right...

**Comment by OSPFvX** [comment]
Somehow very strange, it works:
                
                   req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_REGISTER;
                   req.operands[0].reg.value = ZYDIS_REGISTER_RAX;
OutPut: FF E0

But this:
                  
                  req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
                   req.operands[0].mem.displacement = 0xF9BAEDDB;`
doesn't work
OutPut: "Failed to encode instruction" --->  CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC

**Comment by OSPFvX** [comment]
It worked, but only the imm number does not want to be read normally.
                 
 ```
req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;

                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
                   req.operand_size_hint = ZydisOperandSizeHint::ZYDIS_OPERAND_SIZE_HINT_64;
                   req.operands[0].imm.u = (uint64_t)0xF9BAED;//16 366 317 // 4 189 777 371
```

doesn't work
 ```
req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;

                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
                   req.operand_size_hint = ZydisOperandSizeHint::ZYDIS_OPERAND_SIZE_HINT_64;
                   req.operands[0].imm.u = (uint64_t)0xF9BAED00;//16 366 317 // 4 189 777 371
```
Some kind of limitation for imm

**Comment by mappzor** [comment]
> I am trying to read the second operand in lea rax, qword ptr ds:[VA] and paste it into JMP VA

First of all, such instructions do not exist in this ISA :) 

> Why is the imm operand in JMP? according to intel documentation, the operand in jmp is offset! Or I don't understand something then...

When dealing with addresses you need to consider two common issues with address handling:
- relative immediates (`jmp`, `jnz`, `jge`, etc.) - they are 8 or 32-bits, sign-extended, **relative to RIP** (after decoding check `ZydisDecodedOperandImm.is_relative` to detect them)
- RIP-relative displacements of memory operands - they are 32-bits and are subject to sign-extension as well

Zydis decodes those values and does not interpret them e.g. `E9 44 33 22 11` will get decoded as jump with immediate (`is_relative == true`) 0x11223344. If you pass that immediate back to encoder via `ZydisEncoderEncodeInstruction` no interpretation will happen. It's an **offset** not an **address**. Remember that instruction is RIP-relative, so placing it at runtime address 0x22222222 is not equivalent to placing it at address 0x33333333. You will end up with different destinations. You can use `ZydisCalcAbsoluteAddress` to calculate absolute addresses based on relative operands. You can use `ZydisEncoderEncodeInstructionAbsolute` to pass absolute addresses to encoder and have it calculate correct relative values for you. However you need to remember that it still cannot achieve impossible things. With 32-bit values you can reference memory starting from -2 GB to +2 GB from instruction's address.

You can see [this comment](https://github.com/zyantific/zydis/issues/403#issuecomment-1328222169) for generic algorithm (rest of the discussion might be useful as well).

**Comment by OSPFvX** [comment]
> You can use `ZydisEncoderEncodeInstructionAbsolute`

Yes, thanks, when using ZydisEncoderEncodeInstructionAbsolute I can use a 64 bit value, i.e.
```
                   req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE; //ZYDIS_OPERAND_TYPE_IMMEDIATE
                   req.operands[0].imm.u = 0xFFFFFFFF ;



                   ZyanU64 rntime_address = 0x106FFFFF0;

                   ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
                   ZyanUSize encoded_length = sizeof(encoded_instruction);

                   ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, rntime_address);
```
OutPut: E9 0A 00 00 F9(my address space is 0x140000000 ImageBase)
But I need to somehow automatically calculate the values for each VA with the template above in runtime
>  You can use `ZydisCalcAbsoluteAddress` to calculate absolute addresses based on relative operands.

It doesn't work for some reason, why?!?!

```
       ZyanU64 runtime_address = 0x15A79131D;
       ....
       if (instruction.info.mnemonic == ZYDIS_MNEMONIC_LEA && instruction.operands[1].mem.index == ZYDIS_REGISTER_NONE)
       {
           ZyanU64 result_address; <----
           
           ZydisCalcAbsoluteAddress(&Instruction, &operands[1], runtime_address, &result_address); <----

           uc_mem_read(uc, address + instruction.info.length+TF, data, size);
           int TS = instruction.info.length + TF;

           ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
               &instruction));
           if (instruction.info.mnemonic == ZYDIS_MNEMONIC_XCHG && instruction.operands[0].mem.base == ZYDIS_REGISTER_RSP)
           {
               uc_mem_read(uc, address + instruction.info.length + TS, data, size);
               int TT = instruction.info.length + TS;

               ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
                   &instruction));
               if (instruction.info.mnemonic == ZYDIS_MNEMONIC_RET)
               {       
                   req.mnemonic = ZYDIS_MNEMONIC_JMP; <----
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64; <----
                   req.operand_count = 1; <----
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE; //ZYDIS_OPERAND_TYPE_IMMEDIATE <----
                   req.operands[0].imm.u = result_address;// 0xF9BAEDDE <----

                   ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH]; <----
                   ZyanUSize encoded_length = sizeof(encoded_instruction); <---- 

                   ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, runtime_address); <----
                   for (ZyanUSize i = 0; i < encoded_length; ++i)
                   {
                       printf("%02X ", encoded_instruction[i]);
                   }
                   puts("");

               }
           }
       }
```
OutPut: CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC   =>  I get a "Failed to encode instruction".

**Comment by OSPFvX** [comment]
Some kind of fucked up, can I see some examples of use in the JMP VA encoder somewhere, or maybe there is a "ShowCase" section somewhere to look at projects that use Zydis for deobfuscation, for example?

**Comment by OSPFvX** [comment]
Oh! I got it! So JMP is encoded!

```
                   req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE; //ZYDIS_OPERAND_TYPE_IMMEDIATE
                   req.operands[0].imm.u = 0x154340105(VA in ImageBase);// 0xF9BAEDDE

                   ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
                   ZyanUSize encoded_length = sizeof(encoded_instruction);
                   
                   ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, runtime_address + 5(static));
```
Only now I need to figure out how to pass a dynamic runtime_address, since my RIP from Unicorn throws an error when switching to encode, i.e.
WORK
```
static void ZYDIS_DISASM(uc_engine* uc, uint64_t address, uint32_t size, void* RIP)
{
    ZyanU8 data[16];
    int TF, TS, TT;
    ZyanU8 tmp[16];

    ZydisDecoder decoder;
    ZydisDecoderInit(&decoder, ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_STACK_WIDTH_64);

    ZydisEncoderRequest req;
    memset(&req, 0, sizeof(req));

    ZydisFormatter formatter;
    ZydisFormatterInit(&formatter, ZYDIS_FORMATTER_STYLE_INTEL);

    uint64_t runtime_address = 0x15A79131D; //0x15A79131D
    ZyanU64 rtime_address = (uint64_t)RIP;
 
    ZyanUSize offset = 0;
    const ZyanUSize length = sizeof(data);
    ZyanUSize length_Absolute = sizeof(tmp);

    ZydisDisassembledInstruction instruction;

    ZydisDecodedInstruction Instruction;
    ZydisDecodedOperand operands[ZYDIS_MAX_OPERAND_COUNT];

    ZydisDecoderDecodeFull(&decoder, data + offset, length - offset,
        &Instruction, operands);

    uc_mem_read(uc, address, data, size);
    ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
        &instruction));
    
    

    size = sizeof(data);

    if (instruction.info.mnemonic == ZYDIS_MNEMONIC_PUSH)
    {
       uc_mem_read(uc, address+instruction.info.length, data, size);
       int TF = instruction.info.length;
        
       

       ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
           &instruction));
       if (instruction.info.mnemonic == ZYDIS_MNEMONIC_LEA && instruction.operands[1].mem.index == ZYDIS_REGISTER_NONE)
       {
           ZyanU64 result_address;
         //  unsigned int A = instruction.operands[1].mem.disp.value;
         //  req.operand_count = 2;
         //  req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;//ZYDIS_OPERAND_TYPE_MEMORY
         //  req.operands[0].mem.displacement = A;
         //  req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
         //  req.operands[1].reg.value = ZYDIS_REGISTER_RIP;
           
           ZydisCalcAbsoluteAddress(&Instruction, &operands[1], runtime_address, &result_address);

           uc_mem_read(uc, address + instruction.info.length+TF, data, size);
           int TS = instruction.info.length + TF;

          

           ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
               &instruction));
           if (instruction.info.mnemonic == ZYDIS_MNEMONIC_XCHG && instruction.operands[0].mem.base == ZYDIS_REGISTER_RSP)
           {
               uc_mem_read(uc, address + instruction.info.length + TS, data, size);
               int TT = instruction.info.length + TS;

               

               ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
                   &instruction));
               if (instruction.info.mnemonic == ZYDIS_MNEMONIC_RET)
               {
      
                   req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE; //ZYDIS_OPERAND_TYPE_IMMEDIATE
                   req.operands[0].imm.u = 0x154340105;// 0xF9BAEDDE

                   ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
                   ZyanUSize encoded_length = sizeof(encoded_instruction);
                   
                   ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, runtime_address);
                 
                   

                   for (ZyanUSize i = 0; i < encoded_length; ++i)
                   {
                       printf("%02X ", encoded_instruction[i]);
                   }
                   puts("");

               }
           }
       }
    }
}
```
OutPut:E9 DE ED BA F9

But when transferring RIP from Unicorn to Zydis, everything stops working(Instead of Static address, I pass RIP from Unicorn to the runtime_address variable)(uint64_t runtime_address = (uint64_t)RIP); <--- one change 
Code:
```
 static void ZYDIS_DISASM(uc_engine* uc, uint64_t address, uint32_t size, void* RIP)
{
    ZyanU8 data[16];
    int TF, TS, TT;
    ZyanU8 tmp[16];

    ZydisDecoder decoder;
    ZydisDecoderInit(&decoder, ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_STACK_WIDTH_64);

    ZydisEncoderRequest req;
    memset(&req, 0, sizeof(req));

    ZydisFormatter formatter;
    ZydisFormatterInit(&formatter, ZYDIS_FORMATTER_STYLE_INTEL);

    uint64_t runtime_address = (uint64_t)RIP; //0x15A79131D
    ZyanU64 rtime_address = (uint64_t)RIP;
 
    ZyanUSize offset = 0;
    const ZyanUSize length = sizeof(data);
    ZyanUSize length_Absolute = sizeof(tmp);

    ZydisDisassembledInstruction instruction;

    ZydisDecodedInstruction Instruction;
    ZydisDecodedOperand operands[ZYDIS_MAX_OPERAND_COUNT];

    ZydisDecoderDecodeFull(&decoder, data + offset, length - offset,
        &Instruction, operands);

    uc_mem_read(uc, address, data, size);
    ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
        &instruction));
    
    

    size = sizeof(data);

    if (instruction.info.mnemonic == ZYDIS_MNEMONIC_PUSH)
    {
       uc_mem_read(uc, address+instruction.info.length, data, size);
       int TF = instruction.info.length;
        
       

       ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
           &instruction));
       if (instruction.info.mnemonic == ZYDIS_MNEMONIC_LEA && instruction.operands[1].mem.index == ZYDIS_REGISTER_NONE)
       {
           ZyanU64 result_address;
         //  unsigned int A = instruction.operands[1].mem.disp.value;
         //  req.operand_count = 2;
         //  req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;//ZYDIS_OPERAND_TYPE_MEMORY
         //  req.operands[0].mem.displacement = A;
         //  req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
         //  req.operands[1].reg.value = ZYDIS_REGISTER_RIP;
           
           ZydisCalcAbsoluteAddress(&Instruction, &operands[1], runtime_address, &result_address);

           uc_mem_read(uc, address + instruction.info.length+TF, data, size);
           int TS = instruction.info.length + TF;

          

           ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
               &instruction));
           if (instruction.info.mnemonic == ZYDIS_MNEMONIC_XCHG && instruction.operands[0].mem.base == ZYDIS_REGISTER_RSP)
           {
               uc_mem_read(uc, address + instruction.info.length + TS, data, size);
               int TT = instruction.info.length + TS;

               

               ZYAN_SUCCESS(ZydisDisassembleIntel(ZYDIS_MACHINE_MODE_LONG_64, runtime_address, data + offset, length - offset,
                   &instruction));
               if (instruction.info.mnemonic == ZYDIS_MNEMONIC_RET)
               {
      
                   req.mnemonic = ZYDIS_MNEMONIC_JMP;
                   req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                   req.operand_count = 1;
                   req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE; //ZYDIS_OPERAND_TYPE_IMMEDIATE
                   req.operands[0].imm.u = 0x154340105;// 0xF9BAEDDE

                   ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
                   ZyanUSize encoded_length = sizeof(encoded_instruction);
                   
                   ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, runtime_address+5);
                 //  ZydisEncoderEncodeInstruction(&req, encoded_instruction, &encoded_length);
                   

                   for (ZyanUSize i = 0; i < encoded_length; ++i)
                   {
                       printf("%02X ", encoded_instruction[i]);
                   }
                   puts("");

               }
           }
       }
    }
}
```

**Comment by mappzor** [comment]
Please try to keep examples minimal, so it's easier to follow. It's enough to show encoder request construction, values of other variables passed to `ZydisEncoderEncodeInstruction`/`ZydisEncoderEncodeInstructionAbsolute` (such as runtime address), describe expected result and actual result you got.

**Comment by OSPFvX** [comment]
> Please try to keep examples minimal, so it's easier to follow. It's enough to show encoder request construction, values of other variables passed to `ZydisEncoderEncodeInstruction`/`ZydisEncoderEncodeInstructionAbsolute` (such as runtime address), describe expected result and actual result you got.

Oh, I'm sorry, just for the lack of normal examples for Zydis in terms of memory, I'm doing my own here, since I don't want anyone else to suffer so much.

**Comment by mappzor** [comment]
Still please make sure to include all the elements I've listed. Examples in issues exist to facilitate reproduction of the problem. In your latest example:
```
static void ZYDIS_DISASM(uc_engine* uc, uint64_t address, uint32_t size, void* RIP)
...
uint64_t runtime_address = (uint64_t)RIP; //0x15A79131D
ZyanU64 rtime_address = (uint64_t)RIP;
...
ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, runtime_address);
```
Ultimately I have no idea what's the value of `runtime_address` because it's not shown anywhere (I assume `//0x15A79131D` is commented out from previous example therefore it's irrelevant), so I cannot help you in diagnosing this problem. I can only speculate this value is the problem.

On the other hand something like this would tell me everything I need to know:
```
ZydisEncoderRequest req;
memset(&req, 0, sizeof(req));
req.mnemonic = ZYDIS_MNEMONIC_JMP;
req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
req.operand_count = 1;
req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
req.operands[0].imm.u = 0x00400000;
ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
ZyanUSize encoded_length = sizeof(encoded_instruction);
ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, 0x1122334455667788);
```

**Comment by OSPFvX** [comment]
> Still please make sure to include all the elements I've listed. Examples in issues exist to facilitate reproduction of the problem. In your latest example:
> 
> ```
> static void ZYDIS_DISASM(uc_engine* uc, uint64_t address, uint32_t size, void* RIP)
> ...
> uint64_t runtime_address = (uint64_t)RIP; //0x15A79131D
> ZyanU64 rtime_address = (uint64_t)RIP;
> ...
> ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, runtime_address);
> ```
> 
> Ultimately I have no idea what's the value of `runtime_address` because it's not shown anywhere (I assume `//0x15A79131D` is commented out from previous example therefore it's irrelevant), so I cannot help you in diagnosing this problem. I can only speculate this value is the problem.
> 
> On the other hand something like this would tell me everything I need to know:
> 
> ```
> ZydisEncoderRequest req;
> memset(&req, 0, sizeof(req));
> req.mnemonic = ZYDIS_MNEMONIC_JMP;
> req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
> req.operand_count = 1;
> req.operands[0].type = ZYDIS_OPERAND_TYPE_IMMEDIATE;
> req.operands[0].imm.u = 0x00400000;
> ZyanU8 encoded_instruction[ZYDIS_MAX_INSTRUCTION_LENGTH];
> ZyanUSize encoded_length = sizeof(encoded_instruction);
> ZydisEncoderEncodeInstructionAbsolute(&req, encoded_instruction, &encoded_length, 0x1122334455667788);
> ```
In general, my problem was that the RIP variable contains pointers to itself again and again, i.e.
RIP = VOID(POINTER) => VOID(POINTER) = VA, but I need to get this VA, i.e.
```
mov rax, qword ptr ds:[&RIP] 1) The first pointer
mov rax, [rax] 2) the second pointer
mov rax, [rax] 3) MY VA = uint64_t
mov [&runtime_address], rax <- put in runtime_address my uint64_t VA
```
My problem basically lies in the fact that I have been writing in ASM all my life and I had to write C++ now, since I have no other alternatives.

I need to implement the assembly code above in C++, then Zydis will be able to read RIP or implement its RIP counterpart. The second option (with the implementation of its RIP counterpart) is extremely pointless (since even more resources will be consumed), since my deobfuscator already consumes about 3GB of memory, and I also need to deobfuscate about 60 million instructions or more, since I am writing a deobfuscator for DENUVO.

I will now study how to implement the assembly code above in C++ and then I will send a Pull request so that my deobfuscator is included in the examples for zydis, since it will implement a template for memory and pointers, as well as for ordinary instructions.

**Comment by OSPFvX** [comment]
@mappzor 
Thank you for helping me!

**Comment by OSPFvX** [comment]
https://pastebin.com/AYJ3Pqby
As I promised an example of a deobfuscator using ZYDIS v4.0.0
