### ISSUE TITLE
ZydisV4.0.0-rc1 Encoder, Offsets Encoding 

### ISSUE THREAD

**Issue by OSPFvX** [zyantific/zydis#412]
Hello everyone! Hello @mappzor =)
All readers with merry Christmas!

And this is another stupid question from a rookie =) I'm sorry if this annoys someone =)

Problem:
The problem lies in the encoding of offsets, here is the code:
I need to encode the `MOV QWORD PTR SS:[RSP+0x8], RDI` instruction
Here's the code, but I can't figure out how I can encode the offsets from the registers?
 ```
               ...
               ZydisEncoderRequest pattern_req;
               memset(&pattern_req, 0, sizeof(pattern_req));
               ...
                pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_POINTER;
                pattern_req.operands[0].ptr.segment = ZYDIS_REGISTER_SS;
                pattern_req.operands[0].ptr.offset = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].ptr.offset = +0x8;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);
                
                for (ZyanUSize i = 0; i < encoded_l; ++i)
                {
                    printf("%02X ", encoded_i[i]);
                }
```
This code is non-working. How can I encode the instruction above(`MOV QWORD PTR SS:[RSP+0x8], RDI`)?

**Comment by OSPFvX** [comment]
Hmm, a strange thing, so there is also no encoding of this instruction with this code:

 ```
pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
                pattern_req.operands[0].mem.base = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].mem.displacement = 0x8;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);
```

**Comment by flobernd** [comment]
Hi @OSPFvX,

as you noticed yourself, the operand is not a POINTER type but MEMORY instead.

Could you please try to set "index" instead of "base"? If that does not work, try to manually set "scale" to "1" (I can't remember if we do that implicitly).

Usually it's a good thing to first decode the instruction of interest to inspect the resulting struct afterwards. This should give you a hint about what fields you need to initialize.

**Comment by OSPFvX** [comment]
> Hi @OSPFvX,
> 
> as you noticed yourself, the operand is not a POINTER type but MEMORY instead.
> 
> Could you please try to set "index" instead of "base"? If that does not work, try to manually set "scale" to "1" (I can't remember if we do that implicitly).
> 
> Usually it's a good thing to first decode the instruction of interest to inspect the resulting struct afterwards. This should give you a hint about what fields you must initialize.

Hmm, it doesn't work
Code with set "scale" to "1":
```
                pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
                pattern_req.operands[0].mem.index = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].mem.scale = 1;
                pattern_req.operands[0].mem.displacement = 0x8;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);

                for (ZyanUSize i = 0; i < encoded_l; ++i)
                {
                    printf("%02X ", encoded_i[i]);
                }

```
Also does not work without scale:
Code without set "scale" to "1":
```
                pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
                pattern_req.operands[0].mem.index = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].mem.displacement = 0x8;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);

                for (ZyanUSize i = 0; i < encoded_l; ++i)
                {
                 //   uc_mem_write(uc, RIP + 1 + i, &encoded_instruction[i], 5);
                    printf("%02X ", encoded_i[i]);
                }
```
In all two cases I get("CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC" => "Failed to encode instruction")

**Comment by OSPFvX** [comment]
> Edit: This table is useful to get an overview of the addressing modes:
> 
> https://wiki.osdev.org/X86-64_Instruction_Encoding#32.2F64-bit_addressing

Thanks for the table

**Comment by flobernd** [comment]
Ok, so decoder outputs this:

```
== [ OPERANDS ] ============================================================================================
##       TYPE  VISIBILITY  ACTION      ENCODING   SIZE  NELEM  ELEMSZ  ELEMTYPE                        VALUE
--  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------
 0     MEMORY    EXPLICIT       W      MODRM_RM     64      1      64       INT  TYPE  =                 MEM
                                                                                 SEG   =                  ss
                                                                                 BASE  =                 rsp
                                                                                 INDEX =                none
                                                                                 SCALE =                   0
                                                                                 DISP  =  0x0000000000000008
 1   REGISTER    EXPLICIT       R     MODRM_REG     64      1      64       INT                          rdi
--  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------
```

For me it seems like your second approach was pretty much correct. Did you try with explicitly specifying the `SS` segment?

```C
pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
pattern_req.operand_count = 2;
pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
pattern_req.operands[0].mem.segment = ZYDIS_REGISTER_SS;
pattern_req.operands[0].mem.base = ZYDIS_REGISTER_RSP;
pattern_req.operands[0].mem.displacement = 0x8;
pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;
```

**Comment by OSPFvX** [comment]
> Ok, so decoder outputs this:
> 
> ```
> == [ OPERANDS ] ============================================================================================
> ##       TYPE  VISIBILITY  ACTION      ENCODING   SIZE  NELEM  ELEMSZ  ELEMTYPE                        VALUE
> --  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------
>  0     MEMORY    EXPLICIT       W      MODRM_RM     64      1      64       INT  TYPE  =                 MEM
>                                                                                  SEG   =                  ss
>                                                                                  BASE  =                 rsp
>                                                                                  INDEX =                none
>                                                                                  SCALE =                   0
>                                                                                  DISP  =  0x0000000000000008
>  1   REGISTER    EXPLICIT       R     MODRM_REG     64      1      64       INT                          rdi
> --  ---------  ----------  ------  ------------   ----  -----  ------  --------  ---------------------------
> ```
> 
> For me it seems like your second approach was pretty much correct. Did you try to explicitly specify the `SS` segment?
> 
> ```c
> pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
> pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
> pattern_req.operand_count = 2;
> pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
> pattern_req.operands[0].mem.segment = ZYDIS_REGISTER_SS;
> pattern_req.operands[0].mem.base = ZYDIS_REGISTER_RSP;
> pattern_req.operands[0].mem.displacement = 0x8;
> pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
> pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;
> ```

This is of course great, but in:
```
ZydisEncoderRequest pattern_req;
memset(&pattern_req, 0, sizeof(pattern_req));
```

this does not exist:
`pattern_req.operands[0].mem.segment = ZYDIS_REGISTER_SS;`


https://ibb.co/f1FnWVQ
I am using the latest version of Zydis.

Full code:
```
...
ZydisEncoderRequest pattern_req;
    memset(&pattern_req, 0, sizeof(pattern_req));
...
if (instruction.info.mnemonic == ZYDIS_MNEMONIC_MOV && instruction.operands[0].mem.segment == ZYDIS_REGISTER_DS)
            {
                TT = instruction.info.length + TS;

                pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
                pattern_req.operands[0].mem.segment = ZYDIS_REGISTER_SS;
                pattern_req.operands[0].mem.base = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].mem.displacement = 0x32;
                pattern_req.operands[0].mem.scale = 1;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);
```
class "ZydisEncoderOperand_::ZydisEncoderOperandMem_" has no member "segment"
My includes:

```
#include <iostream>
#include <string.h>
#include <windows.h>
#include <memoryapi.h>
#include <tlhelp32.h>
#include <unicorn.h>
#include <x86.h>
#include <inttypes.h>
#include <Zydis/Zydis.h>
```
My libs
https://ibb.co/6W6fx26
Also Zydis itself is located in the .sln itself:
https://ibb.co/0mkWTvG
I connected Zydis like this:
https://github.com/zyantific/zydis-submodule-example

**Comment by flobernd** [comment]
Sorry, the encoder does not use the `segment` field. I would really suggest decoding the instruction and using `ZydisDecodedInstructionToEncoderRequest` to see what fields you must initialize.

![](https://nextcloud.flobernd.de/s/6ibfxLjnyPFsrQg/preview)

![](https://nextcloud.flobernd.de/s/45nrDG5SztJPrgf/preview)

Maybe the size hints were missing. The encoder is pretty verbose (by design).

**Comment by OSPFvX** [comment]
> Sorry, the encoder does not use the `segment` field. I would really suggest decoding the instruction and using `ZydisDecodedInstructionToEncoderRequest` to see what fields you must initialize.
> 
> ![](https://camo.githubusercontent.com/846f2eb3190e9637d66c4361bfb1396b4571d127239bde43534f7f51adfcd321/68747470733a2f2f6e657874636c6f75642e666c6f6265726e642e64652f732f36696266784c6a6e795046737251672f70726576696577)
> 
> ![](https://camo.githubusercontent.com/c4255caa52af43679df84f2a92afc115fb0a86f1d2b30d1aaf342272af620b16/68747470733a2f2f6e657874636c6f75642e666c6f6265726e642e64652f732f34356e72444735537a744a507267662f70726576696577)
> 
> Maybe the size hints were missing. The encoder is pretty verbose (by design).

I initialized everything as you have in the picture
Anyway I have("CC CC CC CC CC CC CC CC CC CC CC CC CC CC CC" => "Failed to encode instruction")

> ZydisDecodedInstructionToEncoderRequest

This does not exist, there is only this: `ZydisEncoderDecodedInstructionToEncoderRequest`
My code is now and it still doesn't work, even though I initialized everything!:
```
                pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.address_size_hint = ZYDIS_ADDRESS_SIZE_HINT_64;
                pattern_req.operand_size_hint = ZYDIS_OPERAND_SIZE_HINT_64;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
                pattern_req.operands[0].mem.segment = ZYDIS_REGISTER_SS;
                pattern_req.operands[0].mem.base = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].mem.displacement = 0x8;
                pattern_req.operands[0].mem.size = 0x8;
                pattern_req.operands[0].mem.scale = 1;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);

                for (ZyanUSize i = 0; i < encoded_l; ++i)
                {
                    printf("%02X ", encoded_i[i]);
                }
```

**Comment by OSPFvX** [comment]
Oh, fucked up.
Does this look like a Zydis bug? I'm going to start studying Zydis and calling this function through the debugger in a couple of hours now, but people clearly need more examples for the encoder so that they can use it normally.

**Comment by OSPFvX** [comment]
Attach this deobfuscator as an example of using everything that is in Zydis, I will supplement it with other templates built on Zydis.

**Comment by flobernd** [comment]
Please check the values again. I see at least one difference: "scale" is "0" in my screenshot, but you still set it to "1" in your code.

The instruction is 100% encodable in Zydis. You can check yourself by debugging the "ZydisInfo" tool and setting a breakpoint inside of "PrintSizeOptimizedForm()". This is the place where I checked the encoder request for the screenshots.

**Comment by OSPFvX** [comment]
```
pattern_req.mnemonic = ZYDIS_MNEMONIC_MOV;
                pattern_req.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
                pattern_req.operand_count = 2;
                pattern_req.address_size_hint = ZYDIS_ADDRESS_SIZE_HINT_64;
                pattern_req.operand_size_hint = ZYDIS_OPERAND_SIZE_HINT_64;
                pattern_req.allowed_encodings = ZYDIS_ENCODABLE_ENCODING_LEGACY;
                pattern_req.operands[0].type = ZYDIS_OPERAND_TYPE_MEMORY;
              //  pattern_req.operands[0].mem.segment = ZYDIS_REGISTER_SS;
                pattern_req.operands[0].mem.base = ZYDIS_REGISTER_RSP;
                pattern_req.operands[0].mem.displacement = 0x8;
              //  pattern_req.operands[0].mem.size = 0x8;
                pattern_req.operands[0].mem.scale = 0;
                pattern_req.operands[1].type = ZYDIS_OPERAND_TYPE_REGISTER;
                pattern_req.operands[1].reg.value = ZYDIS_REGISTER_RDI;

                ZyanU8 encoded_i[ZYDIS_MAX_INSTRUCTION_LENGTH];
                ZyanUSize encoded_l = sizeof(encoded_i);

                ZydisEncoderEncodeInstruction(&pattern_req, encoded_i, &encoded_l);

                for (ZyanUSize i = 0; i < encoded_l; ++i)
                {
                 //   uc_mem_write(uc, RIP + 1 + i, &encoded_instruction[i], 5);
                    printf("%02X ", encoded_i[i]);
                }
```
 it still doesn't work with  "scale" is "0"

**Comment by OSPFvX** [comment]
it works!! How can I calculate the scale for further instructions:?

**Comment by flobernd** [comment]
I briefly remember a discussion about `scale` in the encoder request ... I __think__ you should always use '0' if you don't use the `index` register and '1' if the `index` register is set. Please correct me, if I'm wrong @mappzor.

In doubt, you can always use this trick (see my previous comment):

> You can check yourself by debugging the "ZydisInfo" tool and setting a breakpoint inside of "PrintSizeOptimizedForm()". This is the place where I checked the encoder request for the screenshots.
>
> I can only repeat myself: Using "ZydisDecodedInstructionToEncoderRequest" on the decoded struct for an instruction of interest, is the easiest way to find out what must be initialized in the encoder request 🙂

This will show you the completely initialized encoder request.

**Comment by mappzor** [comment]
Size hints (`address_size_hint`/`operand_size_hint`) are not required here. However what's always required is the size of the memory operand (`mem.size`). You would face same problem while using a regular assembler:
```asm
mov [rax], rax     ; qword is automatically deduced
mov [rax], 1       ; error: operation size not specified
```
Encoder in Zydis will not try to deduce anything, you just provide that information via `mem.size`.

> I think you should always use '0' if you don't use the index register and '1' if the index register is set. Please correct me, if I'm wrong @mappzor.

It's correct. Scale should be 1 or greater when there's an index register and 0 otherwise. There's an exception for special MIB operands that can have index register but scale is still 0. However this applies to `bndldx`/`bndstx` instructions only and 99.999% of users will never have to deal with them.

In general if you don't know how to construct a request it's best to debug `PrintSizeOptimizedForm` in ZydisInfo as @flobernd suggested or calling `ZydisEncoderDecodedInstructionToEncoderRequest` in your own code and examining its output.

**Comment by OSPFvX** [comment]
Thank you guys so much!
Now I will write and post with pastebin here an example of using an encoder with this instruction in the deobfuscator, then I will close the issue. Thank you guys very much!

**Comment by OSPFvX** [comment]
Example
https://pastebin.com/AYJ3Pqby
Thank you guys so much!
