### ISSUE TITLE
Operand Effective Width

### ISSUE THREAD

**Issue by fred26** [zyantific/zydis#42]
Is there a way to read the number of bytes an instruction is effectively reading?

Let's say movaps [rsp+30],xmm6, [rsp+30] is accessing 16 bytes.

or movsd xmm6,[code.dll+148830] is accessing 8 bytes.

I am looking at here: 

https://zyantific.com/doc/zydis/struct_zydis_decoded_instruction__.html

Thanks

**Comment by fred26** [comment]
I read and maybe the operands[].size element does this?

**Comment by flobernd** [comment]
> I read and maybe the operands[].size element does this?

Yep, that should fit your needs. The `instruction.operands[].size` field refers to the logical size of the operand (in bits).

**Comment by fred26** [comment]
Thanks so much.
