### ISSUE TITLE
Error in parsing

### ISSUE THREAD

**Issue by yonisoft** [zyantific/zydis#425]
It can't parse the assmebly "mov, eax, esi" in this code:
(https://pastebin.com/3g0XWz3U)
here is the bytes of the assembly:
`52 68 E0 94 36 7B 48 89 34 24 BE 24 80 BF 3F BA F1 64 40 6C 31 F2 48 8B 34 24 48 83 C4 08 09 D6 5A 81 EE 67 6A FF 7B 89 F0 5E`

i used "ZYDIS_MACHINE_MODE_LONG_64" mode.

the problem is between this two:
81 EE 67 6A FF 7B
89 F0 <--- here problem

**Comment by flobernd** [comment]
I just tested this on our [zydis.re](zydis.re) website and it seem to work fine:

![image](https://user-images.githubusercontent.com/8585557/222900614-f4c2f955-92c3-4a21-abfa-fa9e611f3f86.png)

Could you show some code?

**Comment by yonisoft** [comment]
You right, my bad, i put small size in the argument, thanks for the fast support :)
