### ISSUE TITLE
Slightly Incorrect Disassembly In Browser Disassembler

### ISSUE THREAD

**Issue by brightprogrammer** [zyantific/zydis#427]
![image](https://user-images.githubusercontent.com/37365905/223071967-c29d01af-34be-4692-95fc-2e71336d92f1.png)

AMD64 Instruction Set Manual states that `CS`, `DS`, `ES` and `SS` segment overrides are ignored, but adding 26 and 36 as prefix changes segment. It should instead be decoded as `db 26` and `db 36`.

![image](https://user-images.githubusercontent.com/37365905/223072899-0797f968-00a4-4d06-88e9-b9aa9c2efd22.png)

**Comment by mappzor** [comment]
Handling of those prefixes has been reworked in 4.0.0 and current version of Zydis interprets them correctly:
```
ZydisInfo.exe -64 36 01 20
...
ABSOLUTE: add dword ptr ds:[rax], esp
RELATIVE: add dword ptr ds:[rax], esp
```
Demo at zydis.re uses an outdated version of the library.

**Comment by brightprogrammer** [comment]
Nice, I was using your disassembler to cross check the disassembler I'm working on and I encountered this problem so I thought I should report. I don't know what should be done next. Should I close this issue?

**Comment by athre0z** [comment]
Updated, should disassemble correctly now!
