### ISSUE TITLE
Support for ENQCMD instruction

### ISSUE THREAD

**Issue by jpidancet** [zyantific/zydis#431]
Hello,

Zydis seems to be missing support for ENQCMD and related instructions.

You can find them documented there: https://community.intel.com/legacyfs/online/drupal_files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf

You can see it implemented in the linux kernel there: https://elixir.bootlin.com/linux/latest/source/arch/x86/include/asm/special_insns.h#L286

Thanks,

**Comment by mappzor** [comment]
`enqcmd` and `enqcmds` are supported by the current version of Zydis. Your example from linux kernel can be disassembled correctly.

**Comment by flobernd** [comment]
The payload from the linked header decodes fine for me as well:

![screenshot](http://nextcloud.flobernd.de/s/A7kJtJX4yGJP5EH/preview)

**Comment by flobernd** [comment]
Yes, the online version unfortunately is outdated. We should maybe include it in our CI/CD.
