### ISSUE TITLE
UD0 instruction without ModRM byte

### ISSUE THREAD

**Issue by jpidancet** [zyantific/zydis#436]
Hi,

The UD0 instruction is a bit special in that it can appear with or without a ModR/M byte:

In Intel® 64 and IA-32 Architectures Software Developer’s Manual ( _INSTRUCTION SET REFERENCE, M-U_), it is described **with** a ModR/M byte,

However, it also says this:

> UD - Undefined Instruction:
> [...]
> NOTES:
>  1. Some processors decode the UD0 instruction without a
>     ModR/M byte. As a result, those processors would deliver
>     an invalid-opcode exception instead of a fault on
>     instruction fetch when the instruction with a
>     ModR/M byte (and any implied bytes) would cross a page
>     or segment boundary.
> 

Now, my problem is that it appears **without** the ModRM byte in some old versions of the Linux kernel: https://elixir.bootlin.com/linux/v4.14.313/source/arch/x86/include/asm/refcount.h#L17, so using Zydis to disassemble code from these kernels will fail because it will attempt to consume 1 byte too many.

I agree this is a difficult one to solve since there's no way for Zydis to evaluate wether the instruction length is 2 or 3 since it depends on the context. For info, capstone seems to ignore the ModR/M byte and views it as a 2byte only instruction.

Is there any way we could add a feature flag to control whether Zydis should accept or reject the ModR/M byte for this instruction ?

**Comment by flobernd** [comment]
Yeah that's a tricky one. I guess a feature flag should work here!

Let's see if I find some time to add this in the next days.. 😵‍💫

**Comment by jpidancet** [comment]
Hi @flobernd. Any updates on this ?

Thanks.

**Comment by flobernd** [comment]
@jpidancet I try to take a look at the end of next week!

**Comment by flobernd** [comment]
@jpidancet It took a while, but I finally found time to implement a decoder mode for this issue.
