### ISSUE TITLE
Question about ZydisCPUFlagAction

### ISSUE THREAD

**Issue by mrexodia** [zyantific/zydis#44]
Hello,

I am trying to get information about which flags a decoded instruction is accessing. The `ZydisDecodedInstruction.accessedFlags[ZYDIS_CPUFLAG_CF].action` appears to give me how the `CF` flag is affected by the instruction.

I am confused about the meaning of `ZYDIS_CPUFLAG_ACTION_MODIFIED`. For the `ADC` and `SBB` instructions the `CF` flag is both tested and modified. Does this mean that modified can implicitly mean tested as well, or is this a missing action?

Thanks,

Duncan

**Comment by flobernd** [comment]
Hi there,

`ZYDIS_CPUFLAG_ACTION_MODIFIED` is used, when the corresponding flag is updated conditionally (either `0` or `1`). `TEST` is not implied by `MODIFIED`. I guess we just missed the additional `TEST` action in our database.

**Comment by mrexodia** [comment]
Thanks! So how could I go about fixing this? Add the flag modified+tested and update the database?

**Comment by flobernd** [comment]
I took a closer look at the issue and recognized, that the problem is more complex than i thought. First problem is, that we indeed missed some flag actions for certain instructions (not a real problem, as these actions are already present in our database). The second - more serious - issue is, that our table design does not even support multiple actions per flag.

This will probably take me some days to fix. Thanks for reporting.

**Comment by flobernd** [comment]
I implemented a workaround for this problem in 5080b7676efc80c54e3165e6c52c569ec0c8922f (future-branch) by adding a new combined CPU-flag action called `TESTED_MODIFIED`. 

Will backport this to develop/master in the next few days (probably already until tomorrow).

**Comment by flobernd** [comment]
Did my latest commit on `develop` resolves the issue for you?

**Comment by mrexodia** [comment]
Hey,

Thanks for the backport in develop! From my test everything appears to work great now 👍 

```
instruction: adc eax, ebx
bytes: 13 C3
zydis: adc eax, ebx
read:
  eax
  ebx
  rflags
write:
  eax
  rflags
flag read:
  cf
flag write:
  cf
  pf
  af
  zf
  sf
  of
```

**Comment by flobernd** [comment]
Perfect!
