### ISSUE TITLE
ZydisDisassemble (MSVC) generates 2 memset calls

### ISSUE THREAD

**Issue by lordbendtner1337** [zyantific/zydis#445]
Currently the following code below will place a ZydisDisassembledInstruction on the stack, then memset it (and also memset ZydisDecodedInstruction info), then it will use a memcpy afterwards. This will cause 2 intrinsic memset calls to be placed into the code.
`    *instruction = (ZydisDisassembledInstruction)
    {
      .runtime_address = runtime_address
    };`
That will cause issues when using ZYAN_NO_LIBC.

Wouldn't it be better to just set the runtime_address;
`instruction->runtime_address = runtime_address;`

Am I missing something? It's possible it's some compiler settings I'm using.

**Comment by mappzor** [comment]
See discussion in #430
