### ISSUE TITLE
Failure to compile in FreeBSD due to unsupported platform in examples

### ISSUE THREAD

**Issue by gdbinit** [zyantific/zydis#45]
Hi,

examples/ZydisPerfTest.c only supports Windows/Apple/Linux and default CMake will fail to build on latest FreeBSD (both master and develop branches).

Fixed it by not compiling the examples in the CMake file:
option(ZYDIS_BUILD_EXAMPLES
    "Build examples"
    OFF)

FreeBSD freebsd 11.2-RELEASE FreeBSD 11.2-RELEASE #0 r335510: Fri Jun 22 04:32:14 UTC 2018     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

Do you want me to try to fix the examples to support FreeBSD and make a pull request?

**Comment by athre0z** [comment]
Sure, will be happy to merge that! Please make sure to branch from either `develop` (v2.0 maintenance) or `future` (v3.0 development, breaking API changes). We'll then up/downport the fix later. A lazy "fix" would be to simply exclude this sample when building on FBSD (via in the CMakeLists).
