### ISSUE TITLE
Question about ZydisEncoderDecodedInstructionToEncoderRequest's operand_count parameter

### ISSUE THREAD

**Issue by asesidaa** [zyantific/zydis#458]
This parameter is called `operand_count `, however, there is a runtime check at https://github.com/zyantific/zydis/blob/master/src/Encoder.c#L4639 that requires it to be less than or equal to `instruction->operand_count_visible`. So maybe it should be renamed to `operand_count_visible` to reduce confusion?

An example is `shl rcx, 0x07`. This would fail if using `ZydisEncoderDecodedInstructionToEncoderRequest(
    &insn.info, insn.operands, insn.info.operand_count, &req);`

**Comment by athre0z** [comment]
Sounds good to me. We used to have the same check in the formatter, but then made it more [lenient a while ago](https://github.com/zyantific/zydis/pull/371). For the encoder I think renaming is the better approach though -- simply ignoring trailing operands might be even more confusing. @flobernd @mappzor opinions?

**Comment by mappzor** [comment]
Renaming sounds good to me.

**Comment by flobernd** [comment]
@athre0z +1 for renaming
