### ISSUE TITLE
Missing enum definitions in Documentation

### ISSUE THREAD

**Issue by r3bb1t** [zyantific/zydis#465]
[Here](https://doc.zydis.re/v4.0.0-rc.1/html/structZydisDecodedInstructionMeta__) we can see the documentation for meta information of decoded instruction with fields which are not available directly. It makes users forced to clone the repo from github and manually grepping the needed enum definitions. 

For example,  **ZydisInstructionCategory** is defined in **include/Zydis/Generated/EnumInstructionCategory.h** and is invisible in documentation.

**Comment by athre0z** [comment]
Ah yes, good catch. Fixed in #467.
