### ISSUE TITLE
ZydisDecodedInstruction has ZYDIS_ATTRIB_IS_RELATIVE attribute when decoding absolute JMP

### ISSUE THREAD

**Issue by EthanZoneCoding** [zyantific/zydis#487]
First of all, I'm not a huge assembly guy so bear with me.

I'm using the safetyhook library which uses Zydis as a disassembler. Hooks can't be placed over a relative instruction, because anything the hook replaces has to be moved to a "trampoline" allocation. When that trampoline's instructions use relative operands, it's all messed up.

The application I'm hooking has intermediate jumps to the function I want to hook. 
I thought that if I hooked here, I could eliminate the issue of relative jumps causing problems. I wrote a function that patches the e9 jump to an absolute ff 25 one, and here is where I ran into a problem.

Patched jump:
![image](https://github.com/zyantific/zydis/assets/42895240/6e44f292-cd57-44ac-a808-d75ba1971d55)

Zydis seems to consider this "relative" still, even though it is an absolute jump. I took a look through the code but like I said, I'm still learning (dis)assembly and I wasn't sure how to proceed.

Thanks

**Comment by athre0z** [comment]
There's no such thing as an absolute 64-bit jump in X86-64. This is just Cheat Engine's weird way of displaying a `jmp [rip]; dq 0x123456712345678` combination of instructions. This has previously caused confusion on multiple occasions. For example, see [here](https://github.com/zyantific/zydis/issues/360).

**Comment by EthanZoneCoding** [comment]
Thank you. I will take a look when I'm back at my computer. I guess I'm
confused why it wouldn't be an absolute jump if the entire absolute address
was an operand.

**Comment by EthanZoneCoding** [comment]
Looks like you were right. I guess I misunderstood, thanks for your patience. I guess I'll close this since it isn't a bug
