### ISSUE TITLE
Support formatting immediates in decimal

### ISSUE THREAD

**Issue by th0rex** [zyantific/zydis#51]
It should be possible to set `ZYDIS_FORMATTER_PROP_IMM_FORMAT` to something like `ZYDIS_IMM_FORMAT_DEC_{SIGNED|UNSIGNED|AUTO}`. Since that would also duplicate some options regarding the signedness it might be better to instead have something like `ZYDIS_FORMATTER_PROP_IMM_BASE` which can be set to either `DEC` or `HEX` and `ZYDIS_FORMATTER_PROP_IMM_SIGNEDNESS` which can be set to `AUTO`, `SIGNED` or `UNSIGNED`.

**Comment by athre0z** [comment]
Although not insanely common, decimal formatting might also be interesting for displacements. Looking through `Formatter.h`, all these number formatting properties for addresses, immediates and displacements are rather similar, except for `ZYDIS_IMM_FORMAT_HEX_AUTO` and `ZYDIS_ADDR_FORMAT_ABSOLUTE`. Maybe we can find a way to merge those into a single enum used for all number formatters and then have another enum `ZYDIS_FORMATTER_RADIX_{10|16}` shared between all of them as well (as proposed by @th0rex).

Putting those into a struct 
```C
struct ZydisNumberFormat {
  ZydisFormatterRadix x;
  ZydisFormatterSignedness y;
};
```
comes to mind, but that would probably suck with the `ZydisUPointer` arg type on `ZydisFormatterSetProperty`, so we might be better off with two properties per number type.

**Comment by athre0z** [comment]
Implemented on master.
