### ISSUE TITLE
Encoding possible issue/help

### ISSUE THREAD

**Issue by colbster255** [zyantific/zydis#515]
Hi everyone, ive been trying to encode an instruction: "**movaps xmm(0-9), [reg]**" and no matter what I try it fails to encode. Its an issue with movaps xmm as I do the same 2nd op settings other places in my code and its fine. I was wondering if someone saw anything wrong with this and or could leave an example on how they would do it.

Thanks alot,

![zydis](https://github.com/zyantific/zydis/assets/95893306/1cb31061-7d30-433b-8e3c-5ec7763b82db)

**Comment by mappzor** [comment]
Memory size should be 16 (128 bits).

**Comment by colbster255** [comment]
> Memory size should be 16 (128 bits).

But that's only for the second operand, no? r15 is a 64 but register so i assumed it would need to be 8 bytes. I'll give it a try when im home, but i'd love to learn why aswell

**Comment by mappzor** [comment]
You are confusing size of base register with size of memory operand. Currently you are trying to encode `movaps xmm9, qword ptr [r15]`. Such instruction cannot exist, as `movaps` requires access to 16 bytes of memory (`movaps xmm9, xmmword ptr [r15]`).

**Comment by colbster255** [comment]
> You are confusing size of base register with size of memory operand. Currently you are trying to encode `movaps xmm9, qword ptr [r15]`. Such instruction cannot exist, as `movaps` requires access to 16 bytes of memory (`movaps xmm9, xmmword ptr [r15]`).

Interesting, thanks so much! I appreciate it a lot. That makes sense, I was confused why I was manually setting the size of the register.

**Comment by colbster255** [comment]
> You are confusing size of base register with size of memory operand. Currently you are trying to encode `movaps xmm9, qword ptr [r15]`. Such instruction cannot exist, as `movaps` requires access to 16 bytes of memory (`movaps xmm9, xmmword ptr [r15]`).

Worked, thanks so much for the help.
