### ISSUE TITLE
Formatter property ZYDIS_FORMATTER_PROP_UPPERCASE_TYPECASTS not implemented

### ISSUE THREAD

**Issue by kbugstar** [zyantific/zydis#518]
It not work when set ZYDIS_FORMATTER_PROP_UPPERCASE_TYPECASTS True,
i checked source file FormatterIntel.c 
function
‘’‘
ZyanStatus ZydisFormatterIntelPrintTypecast(const ZydisFormatter* formatter,
    ZydisFormatterBuffer* buffer, ZydisFormatterContext* context)
{
    ZYAN_ASSERT(formatter);
    ZYAN_ASSERT(buffer);
    ZYAN_ASSERT(context);

    switch (ZydisFormatterHelperGetExplicitSize(formatter, context, context->operand))
    {
    case   8: ZYDIS_BUFFER_APPEND(buffer, SIZE_8_INTEL  ); break;
    case  16: ZYDIS_BUFFER_APPEND(buffer, SIZE_16_INTEL ); break;
    case  32: ZYDIS_BUFFER_APPEND(buffer, SIZE_32_INTEL ); break;
    case  48: ZYDIS_BUFFER_APPEND(buffer, SIZE_48       ); break;
    case  64: ZYDIS_BUFFER_APPEND(buffer, SIZE_64_INTEL ); break;
    case  80: ZYDIS_BUFFER_APPEND(buffer, SIZE_80       ); break;
    case 128: ZYDIS_BUFFER_APPEND(buffer, SIZE_128_INTEL); break;
    case 256: ZYDIS_BUFFER_APPEND(buffer, SIZE_256_INTEL); break;
    case 512: ZYDIS_BUFFER_APPEND(buffer, SIZE_512_INTEL); break;
    default:
        break;
    }

    return ZYAN_STATUS_SUCCESS;
}
’‘’
do the typecast thing
Should I replace the ZYDIS_BUFFER_APPEND macro with ZYDIS_BUFFER_APPEND_CASE to implement the uppercase feature?

**Comment by flobernd** [comment]
Hi @kbugstar,

this is currently not supported:

https://github.com/zyantific/zydis/blob/16c6a369c193981e9cf314126589eaa8763f92c3/include/Zydis/Internal/FormatterBase.h#L164

If you need this functionality, you could use a `ZYDIS_FORMATTER_FUNC_PRINT_TYPECAST` hook to replace the `ZydisFormatterIntelPrintTypecast` function with some custom code.

This example demonstrates how to use formatter hooks in general:
https://github.com/zyantific/zydis/blob/master/examples/Formatter02.c
