### ISSUE TITLE
make error.呆瓜开发者，md有毒吧

### ISSUE THREAD

**Issue by 0xbbbbbbbb** [zyantific/zydis#519]
root@ubuntu:/home/niuma/Desktop/zydis# cmake -B build
CMake Error: The source directory "/home/niuma/Desktop/zydis/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
root@ubuntu:/home/niuma/Desktop/zydis# cmake --build build -j4
Unknown argument -j4
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
root@ubuntu:/home/niuma/Desktop/zydis# 
wdf,什么东西？

**Comment by 0xbbbbbbbb** [comment]
> Try `cmake . -B build`

root@ubuntu:/home/niuma/Desktop/zydis# cmake . -B build
CMake Error: The source directory "/home/niuma/Desktop/zydis/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
root@ubuntu:/home/niuma/Desktop/zydis# 


no ok

**Comment by 0xbbbbbbbb** [comment]
so？

**Comment by mappzor** [comment]
> root@ubuntu:/home/niuma/Desktop/zydis# cmake -B build
CMake Error: The **source directory "/home/niuma/Desktop/zydis/build"** does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
root@ubuntu:/home/niuma/Desktop/zydis# cmake --build build -j4
**Unknown argument -j4**

**Highlighted** errors suggest that cmake version might be an issue. What's your `cmake --version`?

**Comment by 0xbbbbbbbb** [comment]
newest

mappzor ***@***.***> 于 2024年8月2日周五 22:35写道：

**Comment by 0xbbbbbbbb** [comment]
Tomorrow I try

mappzor ***@***.***> 于 2024年8月2日周五 23:19写道：
