### ISSUE TITLE
Addresses leading zeros

### ISSUE THREAD

**Issue by Antiever** [zyantific/zydis#52]
Hi. Is there a way to remove leading zeros without hooking?

![z](https://user-images.githubusercontent.com/9666515/43359117-e270c79a-92a5-11e8-8ef5-02024003f5c0.png)

**Comment by flobernd** [comment]
There is no way to archieve this without hooking at the moment, but I‘ll keep this issue open as a reminder for me to implement this feature.

**Comment by Antiever** [comment]
Thank you for adding new formatter options!
Could you please give an example of how new flags should be used in this case

**Comment by flobernd** [comment]
Sure, just call
```c
ZydisFormatterSetProperty(&formatter, ZYDIS_FORMATTER_PROP_ADDR_PADDING_ABSOLUTE, ZYDIS_PADDING_DISABLED)
```
after initializing the formatter.
