### ISSUE TITLE
Comment error

### ISSUE THREAD

**Issue by wonderzdh** [zyantific/zydis#53]
/**
     * @brief   A pointer to the @c ZydisInstructionDecoder instance.
     */
    const ZydisDecoder* decoder;

**Comment by flobernd** [comment]
Are you using the `master` branch? If **not**, please add the file and line-number to this issue. 

I searched for `ZydisInstructionDecoder` in my local project files, but could not find the phrase ... this might already be fixed in the `future` branch.

**Comment by wonderzdh** [comment]
/**
 * @brief   Defines the @c ZydisDecoderContext struct.
 */
typedef struct ZydisDecoderContext_
{
    /**
     * @brief   A pointer to the @c ZydisInstructionDecoder instance.
     */
    const ZydisDecoder* decoder;

zydis\src\Decoder.c line 47

**Comment by flobernd** [comment]
Thanks for reporting. This is already fixed in the `future` branch and will be merged to master when we update to v3.0.
