### ISSUE TITLE
Getting unresolved external symbol

### ISSUE THREAD

**Issue by engiValk** [zyantific/zydis#54]
So I've gone through and done Cmake, built, and added all the files where I believe they should go, but I keep getting Unresolved external symbol for the following:

Error	LNK2001	unresolved external symbol ZydisDecoderInit	thesisBitMapper	Code\thesisBitMapper\thesisBitMapper\thesisBitMapper.obj	1	
Error	LNK2001	unresolved external symbol ZydisFormatterInit	thesisBitMapper	Code\thesisBitMapper\thesisBitMapper\thesisBitMapper.obj	1	
Error	LNK2001	unresolved external symbol ZydisFormatterFormatInstruction	thesisBitMapper	Code\thesisBitMapper\thesisBitMapper\thesisBitMapper.obj	1	
Error	LNK2001	unresolved external symbol ZydisDecoderDecodeBuffer	thesisBitMapper	Code\thesisBitMapper\thesisBitMapper\thesisBitMapper.obj	1

**Comment by aswerw** [comment]
Does adding #define ZYDIS_STATIC_DEFINE before including Zydis.h fix it?

**Comment by athre0z** [comment]
Your pathes contain backslashes, so I'll assume it's Windows. There is a VS project in `msvc`, but CMake should work as well. It appears as if you forgot to add the Zydis static library to your project. Please check out if linking `Zydis.lib` as described in [this SO thread](https://stackoverflow.com/questions/10049640/linking-a-static-library-to-my-project-on-visual-studio-2010) fixes your problem. Alternatively, add `#pragma comment(lib, "ZYDIS LIB PATH HERE")` to your code — however, this is generally considered bad-practice.

**Comment by engiValk** [comment]
So, the pragma thing fixed it, thanks for that. 

Any reason it is bad practice?

**Comment by athre0z** [comment]
It is MSVC specific (code won't compile on other platforms) and kind of mixes up code and build logic. Also, it ignores any project settings such as target platform (Win32, X64, ...). If you just target one platform, you might be good to go. However, adding it via project settings is pretty much just as easy as adding the pragma.
