### ISSUE TITLE
Incomplete decode for sequential loop instructions

### ISSUE THREAD

**Issue by hainest** [zyantific/zydis#540]
For exposition, let's assume this sequence is encoded as "E2FE E1FC E0FA".

```asm
label:
  loop label
  loope label
  loopne label
```

Running `ZydisInfo -64 $opcode` on many permutations of the byte sequence above using 3-choose-1, 3-choose-2, and 3-choose-3 with and without whitespace, the only opcode that is ever decoded is the first one. For example,

```bash
ZydisInfo -64 "E2FE E1FC E0FA"
ZydisInfo -64 "E1FC E2FE E0FA"
ZydisInfo -64 "E0FAE2FEE1FC"
```

reports only `loop`, `loope`, and `loopne`, respectively.

I tried debugging this, but didn't get very far. I could see the first two bytes running through `ZydisNodeHandlerOpcode`, but couldn't nail down the exactly termination condition. I'd be happy to retry with some suggestions.

I have verified that xed, bddisasm, and Capstone decode these as three separate instructions.

----
branch: master
commit: bffbb61
CMake options: default

**Comment by mappzor** [comment]
> the only opcode that is ever decoded is the first one

This is just how ZydisInfo is supposed to work. It decodes a single instruction (extra bytes are ignored).

**Comment by hainest** [comment]
> > the only opcode that is ever decoded is the first one
> 
> This is just how ZydisInfo is supposed to work. It decodes a single instruction (extra bytes are ignored).

Oh, I didn't realize. Ok. Then all is well. Thanks for the super quick response!

**Comment by flobernd** [comment]
There is the ZydisDisasm tool that accepts a stream of instructions 🙂
