### ISSUE TITLE
bug encoding RIP relative instructions

### ISSUE THREAD

**Issue by li4321** [zyantific/zydis#541]
I am running into issues encoding RIP relative instructions

I believe my code is correct

`cpp

	request.machine_mode = ZYDIS_MACHINE_MODE_LONG_64;
	request.mnemonic = ZYDIS_MNEMONIC_LEA;
	request.operands[0].type = ZYDIS_OPERAND_TYPE_REGISTER;
	request.operands[0].reg.value = ZYDIS_REGISTER_RAX;

	request.operands[1].type = ZYDIS_OPERAND_TYPE_MEMORY;
	request.operands[1].mem.base = ZYDIS_REGISTER_RIP;
	request.operands[1].mem.displacement = 123;
	request.operands[1].mem.size = 4;
	
	request.operand_count = 2;
`

I have attempted to step through ZydisEncoderEncodeInstruction --> ZydisEncoderEncodeInstructionInternal
--> ZydisFindMatchingDefinition --> ZydisIsDefinitionCompatible --> ZydisIsMemoryOperandCompatible 

![image](https://github.com/user-attachments/assets/b8d266ef-943e-418f-8e60-fae5eb487578)
it fails over here, the match->easz is 32, but the candidate easz is 64
I think there may be some bug causing match->easz to be 32 when it is supposed to be 64?

when I change the value of match->easz to 64, it works just fine
when I encode with EIP as the base register instead, it works just fine, but not RIP for some reason

**Comment by ZehMatt** [comment]
I think you have mem size wrong, you are asking to do lea rax, dword ptr[rel 123]

**Comment by li4321** [comment]
> I think you have mem size wrong, you are asking it to do lea rax, dword ptr[rel 123]

I always thought rip relative displacements would be 32 bits/4 bytes long, 
this may sound strange but my code was all working before but suddenly stopped working
I had made sure I did not corrupt anything within zydis.h and zydis.c by re-downloading them into my project

I am setting mem.size to 2, and 8, just to try because why not, still same results, impossible instruction status

**Comment by mappzor** [comment]
> I always thought rip relative displacements would be 32 bits/4 bytes long,

`mem.size` specifies size of memory operand not displacement. With size of 8 it works perfectly fine: `48 8D 05 7B 00 00 00 | lea rax, qword ptr ds:[0x0000000000000082]`.

> I am setting mem.size to 2, and 8, just to try because why not, still fails, with 8 it is a ZYDIS_STATUS_ILLEGAL_LOCK
with 4 it is ZYDIS_STATUS_IMPOSSIBLE_INSTRUCTION

Are you sure rest of the structure is zeroed out?

**Comment by li4321** [comment]
> > I always thought rip relative displacements would be 32 bits/4 bytes long,
> 
> `mem.size` specifies size of memory operand not displacement. With size of 8 it works perfectly fine: `48 8D 05 7B 00 00 00 | lea rax, qword ptr ds:[0x0000000000000082]`.
> 
> > I am setting mem.size to 2, and 8, just to try because why not, still fails, with 8 it is a ZYDIS_STATUS_ILLEGAL_LOCK
> > with 4 it is ZYDIS_STATUS_IMPOSSIBLE_INSTRUCTION
> 
> Are you sure rest of the structure is zeroed out?

oh yea it works not, i guess i was just confused lol, my bad for wasting time here, thanks @mappzor @ZehMatt
