### ISSUE TITLE
Add flag for instructions that might write all registers

### ISSUE THREAD

**Issue by athre0z** [zyantific/zydis#56]
Some instructions like `XRSTOR` can write pretty much any register in the CPU simultaneously. It'd be poor design to list all >200 registers for those instructions in `ZydisDecodedInstruction::operands` (it would require to significantly increase the struct size in order to stay malloc free). Instead, we should add an attribute indicating that all registers and CPU states might be written by the instruction to allow correct taint tracking in optimizers and static code analyzers. We might also want so differentiate between full CPU state change and X87 only state updates (e.g. `FRSTOR`) using another attribute.

It could also be set for interrupt and syscall style instruction, although this will require further consideration.

**Comment by flobernd** [comment]
Same applies to instruction that may conditionally read multiple CPU registers at the same time (like `XSAVE`).

Possible attributes:
- `ZYDIS_ATTRIB_CPU_STATE_{CR|CW}` for general CPU-state access
- `ZYDIS_ATTRIB_FPU_STATE_{CR|CW}` for FPU-state (`x87` and `MMX`) access
- `ZYDIS_ATTRIB_XMM_STATE_{CR|CW}` for XMM-state access
