### ISSUE TITLE
How to use zydis as an external dependency in a CMake project?

### ISSUE THREAD

**Issue by newgre** [zyantific/zydis#58]
What's the cleanest way to build a hello world program that links to zydis using CMake?

Since zydis doesn't seem to offer the typical Find* routines, I had to manually add the include directory and the built static library as a dependency. However, when doing so, I get a compiler error saying that `ZydisExportConfig.h` couldn't be found. Turns out, this file is generated and put into the root directory of the build directory. In the meantime I can work around this by manually adding above file as a CMake variable, but it seems hack-ish? What would be the preferred way to make this scenario work?

Thanks!

**Comment by athre0z** [comment]
AFAIK the "FindX" stuff is a glue mechanic for libs that aren't CMake native. 

Currently, the cleanest way to link against Zydis that I'm aware of involves adding the repo as a git submodule (or just pasting the files and adding them to your repo directly) add have the `CMakeLists.txt` like this:

```cmake
cmake_minimum_required(VERSION "3.12")
add_subdirectory("zydis")
add_executable("helloworld" "hello.c")
target_link_libraries("helloworld" PRIVATE "Zydis")
```

If you happen to know more than us regarding CMake best-practices and this doesn't match them, we'd be happy to improve things on our side!

**Comment by newgre** [comment]
Thank you, the above works for me.
