### ISSUE TITLE
Go bindings for Zydis

### ISSUE THREAD

**Issue by LordNoteworthy** [zyantific/zydis#59]
Hello folks,

Any plans to support go bindings in the future ?

Thank you.

**Comment by athre0z** [comment]
Nothing official is planned. We don't have any Go devs in the team and we only officially bind to languages where we have enough experience to ensure the bindings are at least mostly idiomatic. If you feel like it, you are however more than welcome to build and maintain your own bindings and we'd be happy to feature them in the README!

**Comment by flobernd** [comment]
I created an issue for all language bindings specific tasks here: https://github.com/zyantific/zydis/issues/111

Closing this one for now.
