### ISSUE TITLE
Optable generator marked as todo

### ISSUE THREAD

**Issue by 8BitPimp** [zyantific/zydis#6]
Looking at the code, it seems your optable is generated from an xml document, however the optable generator main function is marked as todo.  Did you complete this part (I assume so since you have a complete optable in the main library), and would you consider uploading the generator too?  I would be realy interested to study that part.  Thanks.

**Comment by flobernd** [comment]
Sorry for late reply. You might take a look at the develop branch. I recently uploaded the InstructionEditor (currently written in Delphi/ObjectPascal) project which I used to create the instruction-database and generate the tables.

**Comment by flobernd** [comment]
The instruction DB and the editor/generator project is now available in a seperarte [repository](https://github.com/zyantific/zydis-db).
