### ISSUE TITLE
Generated tables?

### ISSUE THREAD

**Issue by cblichmann** [zyantific/zydis#64]
Hi,
I'd like to know how the tables in `src/Generated` were, well, generated. Care to share a bit more about the process? Do you have a PDF parser for the Intel manuals (or the AMD ones)? Are they copied and modified from some other project? Where they even "generated" by hand?

Cheers,

Christian

**Comment by flobernd** [comment]
Hi there,

the tables in the `src/Generated` directory are indeed not generated by hand. You can find the generator project and our instruction database in the [zydis-db](https://github.com/zyantific/zydis-db) repository. 

The [instruction database](https://github.com/zyantific/zydis-db/blob/master/Data/instructions.json) itself was created from different sources:
- Intel XED
- LLVM
- sandpile.org
- and of course the official manuals

**Comment by cblichmann** [comment]
Doh! I totally overlooked that. Thanks! Good to know that the DB is also freely available. Unlike for, err, other well-known instruction decoder libraries... :P
