### ISSUE TITLE
Compile error when building dev mode twice

### ISSUE THREAD

**Issue by ceeac** [zyantific/zydis#74]
Version:  805f5e9
Steps to reproduce:
```bash
git clone --recursive https://github.com/zyantific/zydis.git
cd zydis && mkdir build && cd build
cmake -DCMAKE_C_COMPILER=gcc-8 -DZYAN_DEV_MODE=ON .. && make
cmake -DCMAKE_C_COMPILER=gcc-8 -DZYAN_DEV_MODE=ON .. && make
```
Output (abridged for brevity):
```
In file included from /home/ceeac/Projects/code/zydis/dependencies/zycore/include/Zycore/Vector.h:37,
                 from /home/ceeac/Projects/code/zydis/dependencies/zycore/include/Zycore/String.h:39,
                 from /home/ceeac/Projects/code/zydis/dependencies/zycore/include/Zycore/Format.h:37,
                 from /home/ceeac/Projects/code/zydis/dependencies/zycore/src/Format.c:27:
/home/ceeac/Projects/code/zydis/dependencies/zycore/include/Zycore/Comparison.h:123:71: error: ISO C does not allow extra ‘;’ outside of a function [-Werror=pedantic]
 ZYAN_INLINE ZYAN_DECLARE_EQUALITY_COMPARISON(ZyanEqualsBool, ZyanBool);
```
This happens for both clang and GCC, so this is not compiler specific.

**Comment by athre0z** [comment]
Thanks for letting us know. I addressed most of the issues with `pedantic`, however cannot fix those that involve the generated table files (@flobernd will have to deal with that, I don't have the generator at hand).

I really do wonder why it only errored for you when compiling twice, though. This wasn't the case for me -- the errors popped up right in the first compilation.

**Comment by ceeac** [comment]
I've investigated the "error after compiling twice" issue further and it seems to only happen when clearing the CMake cache due to a compiler change (e.g. `cmake -DCMAKE_C_COMPILER=clang`). For fresh clones the compiler flags are set correctly on the first CMake run for me, too. Sorry for the confusion.
