### ISSUE TITLE
kisyscall64

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#77]
![tim 20181115114700](https://user-images.githubusercontent.com/19886504/48529000-35e56a80-e8cc-11e8-947a-b941bd1ba995.jpg)
？why

**Comment by DiskGetor** [comment]
谢谢，是我的失误，用了offset+地址去了，源代码没毛病

**Comment by DiskGetor** [comment]
> 我不确定这里有什么问题。我想你问为什么你的司机（左手边）打印XXX91而右边的工具打印XXX90？在第2.X节中，使用传递给`ZydisDecoderDecodeBuffer`（`instructionPointer`参数）的地址计算此偏移量。这里需要更多信息（Zydis版本，您的代码，......）。

谢谢，是我的失误，用了偏移+地址去了，源代码没毛病

**Comment by athre0z** [comment]
I'm not entirely sure if Google translate got that right, but I think that means that your issue has been resolved? I'll close for now.

**Comment by DiskGetor** [comment]
yes thank again

**Comment by DiskGetor** [comment]
> 我不完全确定谷歌翻译是否正确，但我认为这意味着你的问题已经解决了？我现在要关门了。

yes thank again
