### ISSUE TITLE
length max is what of ZydisDecoderDecodeBuffer ?

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#78]
size_t length = 0x1000;
ZyanStatus ZydisDecoderDecodeBuffer(const ZydisDecoder* decoder, const void* buffer,
    ZyanUSize length, ZydisDecodedInstruction* instruction);

ps: i need length  size of 0x1000, and i set size_t length = 0x1000; ZydisDecoderDecodeBuffer count  retrn <0x1000. why?

typedef struct ZydisDecoderContext_
{
    /**
     * @brief   A pointer to the `ZydisDecoder` instance.
     */
    const ZydisDecoder* decoder;
    /**
     * @brief   The input buffer.
     */
    const ZyanU8* buffer;
    /**
     * @brief   The input buffer length.
     */
    ZyanUSize buffer_len;-----> what is the max size?
.
.
.

**Comment by flobernd** [comment]
`ZydisDecoderDecodeBuffer` only decodes a single instruction at a time. You have to loop over your complete buffer in order to decode all instructions inside. I recommend you having a look at the example in [README.md](https://github.com/zyantific/zydis/blob/master/README.md).

**Comment by flobernd** [comment]
```c
    ZyanUSize offset = 0;
    const ZyanUSize length = sizeof(buffer); // replace this with your buffer size of 0x1000
    ZydisDecodedInstruction instruction;
    while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, buffer + offset, length - offset,
        &instruction)))
    {
        // do something

        offset += instruction.length;
        runtime_address += instruction.length;
    }
```

**Comment by DiskGetor** [comment]
sorry again,i was set buffer size and decode len as 0x1000,but the decode buffer was not return "ret", can you test this thk hou very much.

> ```c
>     ZyanUSize offset = 0 ;
>     const ZyanUSize length = sizeof（buffer）; //用缓冲区大小0x1000替换它
>     ZydisDecodedInstruction指令;
>     while（ZYAN_SUCCESS（ZydisDecoderDecodeBuffer）和解码器，缓冲区+偏移量，长度 - 偏移量，
>         ＆指令）））
>     {
>         //做点什么
> 
>         偏移+ =指令。长度 ;
>         runtime_address + =指令。长度 ;
>     }
> ```

sorry again,i was set buffer size and decode len as 0x1000,but the decode buffer was not return "ret", can you test this thk hou very much.

**Comment by DiskGetor** [comment]
> ```c
>     ZyanUSize offset = 0 ;
>     const ZyanUSize length = sizeof（buffer）; //用缓冲区大小0x1000替换它
>     ZydisDecodedInstruction指令;
>     while（ZYAN_SUCCESS（ZydisDecoderDecodeBuffer）和解码器，缓冲区+偏移量，长度 - 偏移量，
>         ＆指令）））
>     {
>         //做点什么
> 
>         偏移+ =指令。长度 ;
>         runtime_address + =指令。长度 ;
>     }
> ```

		inline size_t length_asm = 0x1000;

		while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, MyArray + offset, length_asm - offset, &instruction)))
		{
			char buffer[0x1000];
			log_("%p [%u] ", (PVOID)runtime_address, instruction.length);
			ZydisFormatterFormatInstruction(&formatter, &instruction, buffer, sizeof(buffer), runtime_address);

			if (strcmp(buffer, "ret") == 0)
			{
				length_asm = offset + 1;
				log_("\n\nxxxxxxxxxxxxxxxx new length_asm-->0x%02X\n\n", length_asm);
			}

**Comment by DiskGetor** [comment]
inline size_t length_asm = 0x1000;

		while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, MyArray + offset, length_asm - offset, &instruction)))
		{
			char buffer[0x1000];
			log_("%p [%u] ", (PVOID)runtime_address, instruction.length);
			ZydisFormatterFormatInstruction(&formatter, &instruction, buffer, sizeof(buffer), runtime_address);

			if (strcmp(buffer, "ret") == 0)
			{
				length_asm = offset + 1;
				log_("\n\nxxxxxxxxxxxxxxxx new length_asm-->0x%02X\n\n", length_asm);
			}
////////////////////////////////////////////////////////////////////////////////
		PS:	i am sorry, i tested  the MyArray ==  __readmsr(0xc0000082)

**Comment by DiskGetor** [comment]
> ```c
>     ZyanUSize offset = 0 ;
>     const ZyanUSize length = sizeof（buffer）; //用缓冲区大小0x1000替换它
>     ZydisDecodedInstruction指令;
>     while（ZYAN_SUCCESS（ZydisDecoderDecodeBuffer）和解码器，缓冲区+偏移量，长度 - 偏移量，
>         ＆指令）））
>     {
>         //做点什么
> 
>         偏移+ =指令。长度 ;
>         runtime_address + =指令。长度 ;
>     }
> ```

		inline size_t length_asm = 0x1000;

		while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, MyArray + offset, length_asm - offset, &instruction)))
		{
			char buffer[0x1000];
			log_("%p [%u] ", (PVOID)runtime_address, instruction.length);
			ZydisFormatterFormatInstruction(&formatter, &instruction, buffer, sizeof(buffer), runtime_address);

			if (strcmp(buffer, "ret") == 0)
			{
				length_asm = offset + 1;
				log_("\n\nxxxxxxxxxxxxxxxx new length_asm-->0x%02X\n\n", length_asm);
			}
////////////////////////////////////////////////////////////////////////////////
		PS:	i am sorry, i tested  the MyArray ==  __readmsr(0xc0000082)

**Comment by DiskGetor** [comment]
debug one night left,i sure is my log function error,thk again.
