### ISSUE TITLE
error with instruction.length

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#80]
https://github.com/asmjit/asmjit/issues/217
![image](https://user-images.githubusercontent.com/19886504/48675990-4717cb00-eb9b-11e8-8e74-86233483bbea.png)

**Comment by athre0z** [comment]
That's correct behavior, the shown byte-code is actually 15 bytes long. It's a long nop with a lot of padding prefixes.
<img width="963" alt="ylup6arnwln4x6kw" src="https://user-images.githubusercontent.com/6553158/48676057-90e3bf80-eb61-11e8-90ac-3de6952c6ae3.png">

**Comment by DiskGetor** [comment]
![image](https://user-images.githubusercontent.com/19886504/48676048-12f0da00-eb9c-11e8-8ba7-f7dce991d2ab.png)
![image](https://user-images.githubusercontent.com/19886504/48676049-12f0da00-eb9c-11e8-982a-cd97cb201125.png)
you can test these coments or test this:

    found_oldIopXxxControlFile = TRUE;
    kGe::asm_::asm_ntapis((PUCHAR)oldIopXxxControlFile);
    found_oldIopXxxControlFile = FALSE;

    log_("found_Syscall64\n");
    found_Syscall64 = TRUE;
    kGe::asm_::asm_ntapis((PUCHAR)__readmsr(0xc0000082));//log_ buffer low，艹-->kLogpBufferSizeInPages
    found_Syscall64 = FALSE;

**Comment by DiskGetor** [comment]
i am sorry again
