### ISSUE TITLE
error with decode  cli comment

### ISSUE THREAD

**Issue by DiskGetor** [zyantific/zydis#81]
please check this msr read codes with zydis:

char data[]={
	0x0F,0x01,0xF8,                                                                 
	0x65,0x48,0x89,0x24,0x25,0x10,0x00,0x00,0x00,                                   
	0x65,0x48,0x8B,0x24,0x25,0xA8,0x01,0x00,0x00,                                   
	0x6A,0x2B,                                                                      
	0x65,0xFF,0x34,0x25,0x10,0x00,0x00,0x00,                                        
	0x41,0x53,                                                                      
	0x6A,0x33,                                                                      
	0x51,                                                                           
	0x49,0x8B,0xCA,                                                                 
	0x48,0x83,0xEC,0x08,                                                            
	0x55,                                                                           
	0x48,0x81,0xEC,0x58,0x01,0x00,0x00,                                             
	0x48,0x8D,0xAC,0x24,0x80,0x00,0x00,0x00,                                        
	0x48,0x89,0x9D,0xC0,0x00,0x00,0x00,                                             
	0x48,0x89,0xBD,0xC8,0x00,0x00,0x00,                                             
	0x48,0x89,0xB5,0xD0,0x00,0x00,0x00,                                             
	0xC6,0x45,0xAB,0x02,                                                            
	0x65,0x48,0x8B,0x1C,0x25,0x88,0x01,0x00,0x00,                                   
	0x0F,0x0D,0x8B,0xD8,0x01,0x00,0x00,                                             
	0x0F,0xAE,0x5D,0xAC,                                                            
	0x65,0x0F,0xAE,0x14,0x25,0x80,0x01,0x00,0x00,                                   
	0x80,0x7B,0x03,0x00,                                                            
	0x66,0xC7,0x85,0x80,0x00,0x00,0x00,0x00,0x00,                                   
	0x0F,0x84,0x8C,0x00,0x00,0x00,                                                  
	0x48,0x89,0x45,0xB0,                                                            
	0x48,0x89,0x4D,0xB8,                                                            
	0x48,0x89,0x55,0xC0,                                                            
	0xF6,0x43,0x03,0x03,                                                            
	0x4C,0x89,0x45,0xC8,                                                            
	0x4C,0x89,0x4D,0xD0,                                                            
	0x74,0x05,                                                                      
	0xE8,0x0D,0x14,0x00,0x00,                                                       
	0xF6,0x43,0x03,0x80,                                                            
	0x74,0x42,                                                                      
	0xB9,0x02,0x01,0x00,0xC0,                                                       
	0x0F,0x32,                                                                      
	0x48,0xC1,0xE2,0x20,                                                            
	0x48,0x0B,0xC2,                                                                 
	0x48,0x39,0x83,0xB8,0x00,0x00,0x00,                                             
	0x74,0x2B,                                                                      
	0x48,0x39,0x83,0xB0,0x01,0x00,0x00,                                             
	0x74,0x22,                                                                      
	0x48,0x8B,0x93,0xB8,0x01,0x00,0x00,                                             
	0x0F,0xBA,0x6B,0x4C,0x0B,                                                       
	0x66,0xFF,0x8B,0xC4,0x01,0x00,0x00,                                             
	0x48,0x89,0x82,0x80,0x00,0x00,0x00,                                             
	0xFB,                                                                           
	0xE8,0x17,0x0B,0x00,0x00,                                                       
	0xEB,0x0F,                                                                      
	0xF6,0x43,0x03,0x40,                                                            
	0x74,0x09,                                                                      
	0xF0,0x0F,0xBA,0xAB,0x00,0x01,0x00,0x00,0x08,                                   
	0x48,0x8B,0x45,0xB0,                                                            
	0x48,0x8B,0x4D,0xB8,                                                            
	0x48,0x8B,0x55,0xC0,                                                            
	0x4C,0x8B,0x45,0xC8,                                                            
	0x4C,0x8B,0x4D,0xD0,                                                            
	0x66,0x90,                                                                      
	0xFB,                                                                           
	0x48,0x89,0x8B,0xE0,0x01,0x00,0x00,                                             
	0x89,0x83,0xF8,0x01,0x00,0x00,                                                  
	0x48,0x89,0xA3,0xD8,0x01,0x00,0x00,                                             
	0x8B,0xF8,                                                                      
	0xC1,0xEF,0x07,                                                                 
	0x83,0xE7,0x20,                                                                 
	0x25,0xFF,0x0F,0x00,0x00,                                                       
	0x4C,0x8D,0x15,0xC7,0x20,0x23,0x00,                                             	
	0x4C,0x8D,0x1D,0x00,0x21,0x23,0x00,                                             
	0xF7,0x83,0x00,0x01,0x00,0x00,0x80,0x00,0x00,0x00,                              
	0x4D,0x0F,0x45,0xD3,                                                            
	0x42,0x3B,0x44,0x17,0x10,                                                       
	0x0F,0x83,0xE9,0x02,0x00,0x00,                                                  
	0x4E,0x8B,0x14,0x17,                                                            
	0x4D,0x63,0x1C,0x82,                                                            
	0x49,0x8B,0xC3,                                                                 
	0x49,0xC1,0xFB,0x04,                                                            
	0x4D,0x03,0xD3,                                                                 
	0x83,0xFF,0x20,                                                                 
	0x75,0x50,                                                                      
	0x4C,0x8B,0x9B,0xB8,0x00,0x00,0x00,                                             
	0x41,0x83,0xBB,0x40,0x17,0x00,0x00,0x00,                                        
	0x74,0x3F,                                                                      
	0x48,0x89,0x45,0xB0,                                                            
	0x48,0x89,0x4D,0xB8,                                                            
	0x48,0x89,0x55,0xC0,                                                            
	0x49,0x8B,0xD8,                                                                 
	0x49,0x8B,0xF9,                                                                 
	0x49,0x8B,0xF2,                                                                 
	0xFF,0x15,0x34,0x1F,0x23,0x00,                                                  
	0x48,0x8B,0x45,0xB0,                                                            
	0x48,0x8B,0x4D,0xB8,                                                            
	0x48,0x8B,0x55,0xC0,                                                            
	0x4C,0x8B,0xC3,                                                                 
	0x4C,0x8B,0xCF,                                                                 
	0x4C,0x8B,0xD6,                                                                 
	0x66,0x66,0x66,0x66,0x66,0x66,0x66,0x0F,0x1F,0x84,0x00,0x00,0x00,0x00,0x00,     
	0x83,0xE0,0x0F,                                                                 
	0x0F,0x84,0xB7,0x00,0x00,0x00,                                                  
	0xC1,0xE0,0x03,                                                                 
	0x48,0x8D,0x64,0x24,0x90,                                                       
	0x48,0x8D,0x7C,0x24,0x18,                                                       
	0x48,0x8B,0xB5,0x00,0x01,0x00,0x00,                                             
	0x48,0x8D,0x76,0x20,                                                            
	0xF6,0x85,0xF0,0x00,0x00,0x00,0x01,                                             
	0x74,0x16,                                                                      
	0x48,0x3B,0x35,0xCF,0x17,0x23,0x00,                                             
	0x48,0x0F,0x43,0x35,0xC7,0x17,0x23,0x00,                                        
	0x0F,0x1F,0x80,0x00,0x00,0x00,0x00,                                             
	0x4C,0x8D,0x1D,0x79,0x00,0x00,0x00,                                             
	0x4C,0x2B,0xD8,                                                                 
	0x41,0xFF,0xE3,                                                                 
	0x0F,0x1F,0x00,                                                                 
	0x48,0x8B,0x46,0x70,                                                            
	0x48,0x89,0x47,0x70,                                                            
	0x48,0x8B,0x46,0x68,                                                            
	0x48,0x89,0x47,0x68,                                                            
	0x48,0x8B,0x46,0x60,                                                            
	0x48,0x89,0x47,0x60,                                                            
	0x48,0x8B,0x46,0x58,                                                            
	0x48,0x89,0x47,0x58,                                                            
	0x48,0x8B,0x46,0x50,                                                            
	0x48,0x89,0x47,0x50,                                                            
	0x48,0x8B,0x46,0x48,                                                            
	0x48,0x89,0x47,0x48,                                                            
	0x48,0x8B,0x46,0x40,                                                            
	0x48,0x89,0x47,0x40,                                                            
	0x48,0x8B,0x46,0x38,                                                            
	0x48,0x89,0x47,0x38,                                                            
	0x48,0x8B,0x46,0x30,                                                            
	0x48,0x89,0x47,0x30,                                                            
	0x48,0x8B,0x46,0x28,                                                            
	0x48,0x89,0x47,0x28,                                                            
	0x48,0x8B,0x46,0x20,                                                            
	0x48,0x89,0x47,0x20,                                                            
	0x48,0x8B,0x46,0x18,                                                            
	0x48,0x89,0x47,0x18,                                                            
	0x48,0x8B,0x46,0x10,                                                            
	0x48,0x89,0x47,0x10,                                                            
	0x48,0x8B,0x46,0x08,                                                            
	0x48,0x89,0x47,0x08,                                                            
	0xF7,0x05,0xBE,0x7D,0x18,0x00,0x40,0x00,0x00,0x00,                              
	0x0F,0x85,0x50,0x02,0x00,0x00,                                                  
	0x41,0xFF,0xD2,                                                                 
	0x65,0xFF,0x04,0x25,0x38,0x22,0x00,0x00,                                        
	0x48,0x8B,0x9D,0xC0,0x00,0x00,0x00,                                             
	0x48,0x8B,0xBD,0xC8,0x00,0x00,0x00,                                             
	0x48,0x8B,0xB5,0xD0,0x00,0x00,0x00,                                             
	0x65,0x4C,0x8B,0x1C,0x25,0x88,0x01,0x00,0x00,                                   
	0xF6,0x85,0xF0,0x00,0x00,0x00,0x01,                                             
	0x0F,0x84,0x4F,0x01,0x00,0x00,                                                  
	0x44,0x0F,0x20,0xC1,                                                            
	0x41,0x0A,0x8B,0xF0,0x01,0x00,0x00,                                             
	0x41,0x0B,0x8B,0xC4,0x01,0x00,0x00,                                             
	0x0F,0x85,0xCE,0x01,0x00,0x00,                                                  
	0xFA,                                                                           
	0x65,0x48,0x8B,0x0C,0x25,0x88,0x01,0x00,0x00,                                   
	0x80,0x79,0x7A,0x00,                                                            
	0x74,0x57,                                                                      
	0x48,0x89,0x45,0xB0,                                                            
	0x33,0xC0,                                                                      
	0x48,0x89,0x45,0xB8,                                                            
	0x48,0x89,0x45,0xC0,                                                            
	0x48,0x89,0x45,0xC8,                                                            
	0x48,0x89,0x45,0xD0,                                                            
	0x48,0x89,0x45,0xD8,                                                            
	0x48,0x89,0x45,0xE0,                                                            
	0x66,0x0F,0xEF,0xC0,                                                            
	0x0F,0x29,0x45,0xF0,                                                            
	0x0F,0x29,0x45,0x00,                                                            
	0x0F,0x29,0x45,0x10,                                                            
	0x0F,0x29,0x45,0x20,                                                            
	0x0F,0x29,0x45,0x30,                                                            
	0x0F,0x29,0x45,0x40,                                                            
	0xB9,0x01,0x00,0x00,0x00,                                                       
	0x44,0x0F,0x22,0xC1,                                                            
	0xFB,                                                                           
	0xE8,0x59,0x47,0xFF,0xFF,                                                       
	0xFA,                                                                           
	0xB9,0x00,0x00,0x00,0x00,                                                       
	0x44,0x0F,0x22,0xC1,                                                            
	0x48,0x8B,0x45,0xB0,                                                            
	0x65,0x48,0x8B,0x0C,0x25,0x88,0x01,0x00,0x00,                                   
	0xF7,0x01,0x00,0x00,0x02,0x40,                                                  
	0x74,0x2E,                                                                      
	0x48,0x89,0x45,0xB0,                                                            
	0xF6,0x41,0x02,0x02,                                                            
	0x74,0x0E,                                                                      
	0xE8,0x7B,0x9F,0x09,0x00,                                                       
	0x65,0x48,0x8B,0x0C,0x25,0x88,0x01,0x00,0x00,                                   
	0xF6,0x41,0x03,0x40,                                                            
	0x74,0x0C,                                                                      
	0x48,0x8D,0x65,0x80,                                                            
	0x48,0x33,0xC9,                                                                 
	0xE8,0x00,0x0B,0x00,0x00,                                                       
	0x48,0x8B,0x45,0xB0,                                                            
	0x0F,0xAE,0x55,0xAC,                                                            
	0x4D,0x33,0xD2,                                                                 
	0x66,0x83,0xBD,0x80,0x00,0x00,0x00,0x00,                                        
	0x74,0x3E,                                                                      
	0x48,0x89,0x45,0xB0,                                                            
	0xE8,0xA2,0x10,0x00,0x00,                                                       
	0x65,0x48,0x8B,0x04,0x25,0x88,0x01,0x00,0x00,                                   
	0x48,0x8B,0x40,0x70,                                                            
	0x48,0x8B,0x80,0x00,0x01,0x00,0x00,                                             
	0x48,0x0B,0xC0,                                                                 
	0x74,0x18,                                                                      
	0x66,0x83,0xBD,0xF0,0x00,0x00,0x00,0x33,                                        
	0x75,0x0E,                                                                      
	0x4C,0x8B,0x95,0xE8,0x00,0x00,0x00,                                             
	0x48,0x89,0x85,0xE8,0x00,0x00,0x00,                                             
	0x48,0x8B,0x45,0xB0,                                                            
	0x4C,0x8B,0x85,0x00,0x01,0x00,0x00,                                             
	0x4C,0x8B,0x8D,0xD8,0x00,0x00,0x00,                                             
	0x33,0xD2,                                                                      
	0x66,0x0F,0xEF,0xC0,                                                            
	0x66,0x0F,0xEF,0xC9,                                                            
	0x66,0x0F,0xEF,0xD2,                                                            
	0x66,0x0F,0xEF,0xDB,                                                            
	0x66,0x0F,0xEF,0xE4,                                                            
	0x66,0x0F,0xEF,0xED,                                                            
	0x48,0x8B,0x8D,0xE8,0x00,0x00,0x00,                                             
	0x4C,0x8B,0x9D,0xF8,0x00,0x00,0x00,                                             
	0x49,0x8B,0xE9,                                                                 
	0x49,0x8B,0xE0,                                                                 
	0x0F,0x01,0xF8,                                                                 
	0x48,0x0F,0x07,                                                                 
	0x48,0x8B,0x95,0xB8,0x00,0x00,0x00,                                             
	0x49,0x89,0x93,0xD8,0x01,0x00,0x00,                                             
	0x8A,0x55,0xA8,                                                                 
	0x41,0x88,0x93,0xF6,0x01,0x00,0x00,                                             
	0xFA,                                                                           
	0x48,0x8B,0xE5,                                                                 
	0x48,0x8B,0xAD,0xD8,0x00,0x00,0x00,                                             
	0x48,0x8B,0xA4,0x24,0x00,0x01,0x00,0x00,                                        
	0xFB,                                                                           
	0xC3,   
};

post out log:

![image](https://user-images.githubusercontent.com/19886504/48755278-bbec2180-eccf-11e8-9a0f-36c13836031e.png)

![image](https://user-images.githubusercontent.com/19886504/48755285-c0b0d580-eccf-11e8-9e76-3d0f8284af31.png)

**Comment by athre0z** [comment]
The byte `0x00` certainly doesn't disassemble to `cli` with Zydis, neither does `0x89` disassemble to `sti`. There must be errors in your code causing this. Also, I'm running out of patience with your style of creating issues without verifying if it is actually an issue with the lib. This is an issue tracker, not a general purpose forum for coding help. Please stop flooding us with invalid issues, expecting us to understand Chinese error messages. Thank you.
