### ISSUE TITLE
ZydisFormatterFormatInstruction BUG

### ISSUE THREAD

**Issue by nblog** [zyantific/zydis#82]
// 例子代码
	ZyanU8 data[] =
	{
		0x44, 0x88, 0x3D, 0x67, 0xFF, 0x17, 0x00  // mov byte ptr ds:[0x00007FFA474BF21C], r15b
	};

	// Initialize decoder context
	ZydisDecoder decoder;
	ZydisDecoderInit(&decoder, ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_ADDRESS_WIDTH_64);

	// Initialize formatter. Only required when you actually plan to do instruction
	// formatting ("disassembling"), like we do here
	ZydisFormatter formatter;
	ZydisFormatterInit(&formatter, ZYDIS_FORMATTER_STYLE_INTEL);

	// Loop over the instructions in our buffer.
	// The runtime-address (instruction pointer) is chosen arbitrary here in order to better
	// visualize relative addressing

	ZyanU64 runtime_address = 0x00007FFA4733F2AE;

	ZyanUSize offset = 0;
	const ZyanUSize length = sizeof(data);
	ZydisDecodedInstruction instruction;
	while (ZYAN_SUCCESS(ZydisDecoderDecodeBuffer(&decoder, data + offset, length - offset,
		&instruction)))
	{
		// Print current instruction pointer.
		printf("%016" PRIX64 "  ", runtime_address);

		// Format & print the binary instruction structure to human readable format
		char buffer[256];
		ZydisFormatterFormatInstruction(&formatter, &instruction, buffer, sizeof(buffer),
			runtime_address);
		puts(buffer);

		offset += instruction.length;
		runtime_address += instruction.length;
	}

output:
00007FFA4733F2AE  mov [0x00007FFA474BF21C00000000474BF21C], r15b

Is it wrong here?

zydis\src\String.c (ZydisStringAppendHexU) line:346   

 if (value & 0xFFFFFFFF00000000)
    {
        ZYAN_CHECK(ZydisStringAppendHexU64(string, value, padding_length, uppercase));
    }
else
{
    ZYAN_CHECK(ZydisStringAppendHexU32(string, (ZyanU32)value, padding_length, uppercase));
}

forgive my poor english :p

**Comment by athre0z** [comment]
Hm, that's not happening for me. Are you perhaps on a 32-bit machine? What Zydis version is this? Platform?

**Comment by athre0z** [comment]
Yes indeed, I can confirm this is bugged when targeting 32 bit. Thanks for letting us know!

**Comment by athre0z** [comment]
That was indeed the code causing the issue. The second call obviously had to go into an else clause. Thanks again!
