### ISSUE TITLE
Error compiling Debug Kernel code sample

### ISSUE THREAD

**Issue by blaquee** [zyantific/zydis#84]
An error occurs in the Formatter.c:359 (C4189) due to pedantic warnings (Warnings treated as errors) when compiling for kernel code.

A possible workaround is to add
```#pragma warning(disable:4189)```
and
```#pragma warning(default:4189)```

around that #ifdef 

> Error:
 Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4189	 'test': local variable is initialized but not referenced
    const ZyanUPointer* test = (ZyanUPointer*)(&formatter->func_pre_instruction + type);
                        ^	Zydis	c:\code\zydis\src\formatter.c	359

**Comment by flobernd** [comment]
Thanks for reporting that. This is a strange bug tho ... Seems like `ZYAN_DEBUG` is true, but `ZYAN_ASSERT` is defined as no-op which should not happen at all. Can you confirm this?

**Comment by athre0z** [comment]
I think this is due to the kernel sample being `ZYAN_NO_LIBC`, resulting in disabled asserts. Working on a fix.

**Comment by athre0z** [comment]
Can you check out the branch `fix/debug-windows-kernel-sample` and check whether it actually resolves the issue?

**Comment by blaquee** [comment]
Prelim test shows the error still exists in that branch @athre0z. You just removed the Defines.h file for that configuration?

**Comment by athre0z** [comment]
Nah, I added a `(void)condition` cast in the no-libc variant of `ZYAN_ASSERT` (in the zycore submodule).

**Comment by athre0z** [comment]
Excellent, rebased into master!
