### ISSUE TITLE
ZydisCalcAbsoluteAddress

### ISSUE THREAD

**Issue by sidyhe** [zyantific/zydis#85]
hope that take an optional parameter to calc address
like this:
```
typedef struct _REGISTERS
{
	UINT64 R15;
	UINT64 R14;
	UINT64 R13;
	UINT64 R12;
	UINT64 R11;
	UINT64 R10;
	UINT64 R9;
	UINT64 R8;
	UINT64 Rdi;
	UINT64 Rsi;
	UINT64 Rbp;
	UINT64 Rsp;
	UINT64 Rbx;
	UINT64 Rdx;
	UINT64 Rcx;
	UINT64 Rax;
} REGISTERS, *PREGISTERS;

ZyanStatus ZydisCalcAbsoluteAddress(..., PREGISTERS regs);
```
so it can calc address like ```mov rax, [rsi+4]```
if rsi == 00401000, the api can get address is 00401004

**Comment by flobernd** [comment]
Looks good. I'll try out some things in the next few days to hopefully come up with the most convenient implementation.

**Comment by flobernd** [comment]
@sidyhe Take a look at my latest [commit](https://github.com/zyantific/zydis/commit/ae9d7a6baea48b28e133e53343c02c3120b26501) and let me know, if the new function is sufficient for your usecase :)

**Comment by sidyhe** [comment]
thanks! i will try later.

**Comment by sidyhe** [comment]
the second suggestion
is it better way to do via template C++11 ?
it is not necessary, just a thinking

**Comment by flobernd** [comment]
1. The instruction `mov rax, [edx+0x100]` is totally fine. Not sure what "support flags" you want us to add. Could you give me a valid example please?

2. Let me discuss this with @athre0z . Maybe a `struct` with `unions` might be a different solution for this issue. We decided to use an array to avoid copy&paste / maintenance work in the first place and to keep the helper function small and performant (using the struct from your first comment would force us to map our `ZydisRegister` enum values to the struct members - which would be a mess).

3. We can't use C++ templates as Zydis is a pure C project.

**Comment by sidyhe** [comment]
i see the enum at ```EnumRegister.h``` , there is a lot of value
in my code, the asm only for ```mov rax, [r64+xxx]``` , r64 is the base that one of ```rax ~ r15```
so maybe a flag can do this
the code maybe is
```
int calc_address(..., int flags)
{
  int base_reg = xxx;
  if (base_reg is 64bit)
  {
    if (flags & REGISTER_64WIDTH) // 0x01 for this
    {
      // calc address
      return OK;
    }
    else
    {
      return NOT_ACCEPT_BY_FLAGS;
    }
  }
}
```
in others words
i can specified scope of the base register
some i want, others is not

**Comment by sidyhe** [comment]
it is only for my work
check the register before call api can do the same things
there is already has ```ZydisCalcAbsoluteAddressEx``` to help me, already meet my needs
however, thanks for your help !

**Comment by flobernd** [comment]
Alright, no problem. I'll close this for now.
