### ISSUE TITLE
Visual Studio 2017 - linking error

### ISSUE THREAD

**Issue by 1982Dmitry** [zyantific/zydis#87]
Done everything according to instruction, use cmake to generate sln project and so on.
But getting MSVCRT lib conflict error:
![image](https://user-images.githubusercontent.com/10502637/52349258-161e9800-2a1e-11e9-99c9-d5d83dbb6e23.png)

**Comment by flobernd** [comment]
I just generated a clean solution using CMake myself two days ago and everything was working fine. Can recheck this when I'm home ... or maybe @athre0z has time to have a look.
