### ISSUE TITLE
Decode instructions

### ISSUE THREAD

**Issue by 1982Dmitry** [zyantific/zydis#88]
`	ZyanU8 data[] =
	{
		0x51, 0x8D, 0x45, 0xFF, 0x50, 0xFF, 0x75, 0x0C, 0xFF, 0x75,
		0x08, 0xFF, 0x15, 0xA0, 0xA5, 0x48, 0x76, 0x85, 0xC0, 0x0F,
		0x88, 0xFC, 0xDA, 0x02, 0x00
	};
`

I'm decoding it using `ZydisDecoderDecodeBuffer` exactly as in the example code in the main page and printing opcodes for each instruction.

but the last instr (JS) is decoded as `88`  instead of `0F 88` (value of instr.opcode)

![image](https://user-images.githubusercontent.com/10502637/52352850-43bb0f80-2a25-11e9-9288-9d6a3940fc38.png)

![image](https://user-images.githubusercontent.com/10502637/52355558-6a2f7980-2a2a-11e9-9ab5-bb704d95fa79.png)

**Comment by insolor** [comment]
You decode this example as a 32-bit code, whereas on the main page it is decoded as a 64-bit code. The mode depends on which parameters you pass in the ZydisDecoderInit call:

`ZydisDecoderInit(&decoder, ZYDIS_MACHINE_MODE_LONG_64, ZYDIS_ADDRESS_WIDTH_64);`

**Comment by 1982Dmitry** [comment]
That's my error, thanks
