### ISSUE TITLE
Incorrent opcode for "movq" instruction

### ISSUE THREAD

**Issue by zExtraNo** [zyantific/zydis#89]
`	byte data[]
	{
		0x89, 0x11, 0xf3, 0x0f, 0x7e, 0x5, 0x30, 0xf2, 0x43, 0x00, 0x66, 0x0f, 0xd6, 0x41, 0x08
	};`
`ZydisDecoderInit(&decoder, ZYDIS_MACHINE_MODE_LEGACY_32, ZYDIS_ADDRESS_WIDTH_32);`

According to IDAPro opcodes are F3 0F 7E and 66 0F D6 for second and third instructions, but `opcode` values from `Zydis` are 0x7E and `D6`
![image](https://user-images.githubusercontent.com/6316023/52372811-ff456900-2a50-11e9-8ed4-8ab435b8f185.png)

**Comment by flobernd** [comment]
The `instr.opcode` field contains the significant (last) opcode. `F3`/`66` are mandatory prefixes which are traited as part of the opcode but technically they are no "real" opcodes. Same for `0F` which simply select the 2-byte opcode-map (this one can be checked, if you take a look at `instr.opcode_map`).

**Comment by zExtraNo** [comment]
Thank you for clarification

**Comment by flobernd** [comment]
No problem :) It should be sufficient to check against `instr.mnemonic` and `instr.opcode_map` to exactly identify a specific instruction. You can totally avoid opcode checks this way.

**Comment by zExtraNo** [comment]
Is .opcode size always 1 byte?

**Comment by flobernd** [comment]
> Is .opcode size always 1 byte and 3 zeros?

Where do you see 3 zeros? The `instr.opcode` field is defined as `ZyanU8` which is an alias for `uint8_t` = 1 byte.

**Comment by zExtraNo** [comment]
Sorry, my mistake

**Comment by flobernd** [comment]
The definition of "opcode" varies .. Zydis defines the actual opcode as the last byte. Some other libs precede the opcode sequence with the `0F`/`0F38`/`0F3A`/`0F0F` table-selector and there might be other libs which include the mandatory-prefix `F2`/`F3`/`66` as well. But even this is not the full identifying pattern of a single instructions. Many of them are using fields of the ModRM byte as well and for `XOP`/`VEX`/`EVEX`/`MVEX` encoded instruction it's even more complicated.

What exactly are you trying to archieve?

**Comment by zExtraNo** [comment]
Just saw Zydis and writing some "Hello world" examples and compare results, what I can say now is that Zydis feels much faster and easier to use than Capstone.
Do you plan to port Python3 (official) and Py2?

**Comment by flobernd** [comment]
> Just saw Zydis and writing some "Hello world" examples and compare results, what I can say now is that Zydis feels much faster and easier to use than Capstone.

Thanks! Nice to hear.

> Do you plan to port Python3 (official) and Py2?

There are no immediate plans as we are both a little bit short short on time at the moment, but we definitely planned to support some more languages with bindings in the future.
