### ISSUE TITLE
Wrong mnemonic for MOVSS

### ISSUE THREAD

**Issue by reliasn** [zyantific/zydis#9]
Tried to get the mnemonic for the following instruction (32-bit):

```
{0xF3, 0x0F, 0x10, 0x05, 0x58, 0xF4, 0xD0, 0x00}
```

Zydis gave me:

```
movsd xmm0, [D0F458]
```

But the correct mnemonic is:

```
movss xmm0, [D0F458]
```

**Comment by mrexodia** [comment]
This is in the development branch:

```bash
rasm2 -a x86.zyan -b 32 -d F30F100558F4D000
movss xmm0, dword ptr [0x00D0F458]
```

So it appears to have been fixed.

**Comment by athre0z** [comment]
Yup, that was fixed as a side-effect of the full rewrite of the whole library. We'll close the issue once v2 is on master.

**Comment by mrexodia** [comment]
Oh, is 2.0 on master?

**Comment by athre0z** [comment]
Yup, we're now in public alpha, requesting for final comments on the public interface before calling it stable. I pulled it to master only seconds ago.
