### ISSUE TITLE
Possible memory access violation

### ISSUE THREAD

**Issue by wonderzdh** [zyantific/zydis#90]
> 

        // Static broadcast-factor
        ZyanU8 index = def->has_element_granularity;
        ZYAN_ASSERT(!index || !def->broadcast);
        if (!index && def->broadcast)
        {
            instruction->avx.broadcast.is_static = ZYAN_TRUE;
            switch (def->broadcast)
            {
            case ZYDIS_MVEX_STATIC_BROADCAST_1_TO_8:
                instruction->avx.broadcast.mode = ZYDIS_BROADCAST_MODE_1_TO_8;
                index = 1;
                break;
            case ZYDIS_MVEX_STATIC_BROADCAST_1_TO_16:
                instruction->avx.broadcast.mode = ZYDIS_BROADCAST_MODE_1_TO_16;
                index = 1;
                break;
            case ZYDIS_MVEX_STATIC_BROADCAST_4_TO_8:
                instruction->avx.broadcast.mode = ZYDIS_BROADCAST_MODE_4_TO_8;
                index = 2;
                break;
            case ZYDIS_MVEX_STATIC_BROADCAST_4_TO_16:
                instruction->avx.broadcast.mode = ZYDIS_BROADCAST_MODE_4_TO_16;
                index = 2;
                break;
            default:
                ZYAN_UNREACHABLE;
            }
        }

> 

case ZYDIS_MVEX_FUNC_DI_32:
        {
            static const ZyanU8 lookup[2][8] =
            {
                { 64,  0,  0, 32, 16, 16, 32, 32 },
                {  4,  0,  0,  2,  1,  1,  2,  2 }
            };
            ZYAN_ASSERT(instruction->raw.mvex.SSS < ZYAN_ARRAY_LENGTH(lookup[index]));
            context->cd8_scale = lookup[index][instruction->raw.mvex.SSS];
            break;
        }

Should I add some code? like ZYAN_ASSERT(index<2)

**Comment by athre0z** [comment]
I don't really know a lot about MVEX, but suspect that these instructions with the shorter lookup tables just don't support broadcasting and thus an out-of-bounds access is impossible. @flobernd should take a second look here just to be sure.

Anyway, adding an ASSERT just to be sure can never hurt, feel free to drop a PR!

**Comment by flobernd** [comment]
Broadcasting is not supported for instructions of the `Di32/Df32/Di64/Df64` type according to the `Intel® Xeon Phi™ Coprocessor Instruction Set Architecture Reference Manual`.

Not sure if the definition editor checks for this constraint tho. Anyways .. I'll add the `ASSERT` to be on the safe side in case somebody tempers with the definitions at some point.
