### ISSUE TITLE
Instruction address removal from ZydisDecodedInstruction

### ISSUE THREAD

**Issue by gdbinit** [zyantific/zydis#92]
Hi,

A bit of a silly question but the address of the disassembled instruction was removed from the zydis instruction structure. Is there a rationale for that? Before you could set the base address on ZydisDecoderDecodeBuffer() and pass the instruction to other functions without keep tracking of the address. The API changes now require to keep track of that address and pass it to any other user implemented functions that deal with individual instructions. Just asking because I got a bunch of older code to refactor (since I want it to be up to date with Zydis and not in v2 branch) and it has always been useful to have the address stored internally.

best,
fG!

**Comment by flobernd** [comment]
Hi there,

sorry for the breaking change. The idea behind this is that the runtime-address just does not semantically belong to the decoder. Moving the runtime-address parameter from the decoder API to the formatter API, moves it more closely to the location of (internal) usage and makes the interface more consistent. It just made no sense to require the runtime-address in the `ZydisDecoderDecodeBuffer` without it even beeing used.

I agree with you that internally storing the address was usefull in some cases like if you want to store the `ZydisDecodedInstruction` but don't want to put a wrapper class/struct around it. Unfortunately, the latter is probably the only option I currently see to workaround this problem.

Best regards

**Comment by athre0z** [comment]
Also, this unlocked efficient implementation of a no-copy caching layer, as currently discussed in #113.

Since this issue is now over a month old, I'm going to close this for now, but feel free to either re-open or just continue this discussion in the closed issue!
