### ISSUE TITLE
As submodule *.vcxproj improvements

### ISSUE THREAD

**Issue by HoShiMin** [zyantific/zydis#97]
Hi, awesome guys!

Well, previous improvement with project-relative output paths is very useful, but I need a bit more to setup a complete submodule integration, alright?

First of all - yes - I need an /MT and /MTd support in *.vcxproj. For example, I build my dll without MSVCRTD dependencies, and it requires to make build statically too, but with existing compile regimes I can build only /MD lib. It's a problem, sure. So, what about 3 more regimes: LIBC+MT(d), LIBC+MD(d) and without LIBC. I think, it will be awesome to extend available regimes!

And next thing is - yes - release/debug output paths splitting. Because of this: Zydis is dependency of my dll, so it builds first, and my lib is last, right? Okay, let's build the debug build. All good. Switch to the release. As we already have a ready *.lib in the output dir, it will not rebuild to release version and release build will link debug version of Zydis. So yes, we need to split all available builds to their own dirs.

For this time it's all required to use Zydis as a git submodule in all types of projects.

**Comment by flobernd** [comment]
Hi there,

mhh you definitely got a point there .. this would result in a lot of different build configurations tho. What do you think @athre0z @Mattiwatti ?

**Comment by flobernd** [comment]
Just had a short talk with @athre0z and we would be fine with these changes. You could kindly ask @Mattiwatti if he has time to do it or just send us a pull request yourself.

**Comment by HoShiMin** [comment]
Well, good, I'll give you a pull request in about ~2 days

**Comment by HoShiMin** [comment]
Hm, I've add new build modes, but Zycore is unable to build with /MT or /MTd in DLL building mode, not debug nor release regimes due to unresolved external symbol "__imp__wassert". You can reproduce it by switching /MDd to the /MTd in the Debug DLL mode.

Any ideas to fix it?

**Comment by Mattiwatti** [comment]
Theory: you need to remove `_DLL` from the preprocessor definitions for builds using the static CRT, then it will work. For completeness' sake you can replace it with `_LIB` to indicate usage of the static CRT, but I don't think this macro actually does anything whereas `_DLL` does.

Practice: after testing this in MSVC it seems that at the very least `_DLL` is automatically inserted by the compiler if the CRT selection is `/MD` or `/MDd`. So I'd recommend simply removing both `_DLL` and `_LIB` from all build configurations to simplify things and leave it to the compiler to insert the right macros. Zycore and Zydis themselves don't use these.

**Comment by HoShiMin** [comment]
Well, thanx guys!
