### ISSUE TITLE
CMake doesn't install ZydisDisasm and ZydisInfo

### ISSUE THREAD

**Issue by nl5887** [zyantific/zydis#99]
The current CMake configuration doesn't install the tools ZydisDisasm, ZydisInfo and possibly ZydisFuzzIn. Don't know for sure if this is expected and wanted behaviour, but otherwise I have a change for it. Seems to me that both tools can (or will) have (future) value.

Homebrew/homebrew-core#37594

**Comment by athre0z** [comment]
These targets should indeed have been installed and have been forgotten in the CMake config. I fixed this on master. Thanks for letting us know and for putting Zydis into Homebrew!

**Comment by athre0z** [comment]
Oh, I just realized that you were submitting v2.0.2. In that case, I'll also backport that. Just give me a few minutes ...

**Comment by athre0z** [comment]
Alright, I pushed the fix to `maintenance/v2`. Please let me know if everything is working fine for you. Once this is the case, I'll put a tag on it and release `v2.0.3`.

**Comment by nl5887** [comment]
Check! Works fine with me.

**Comment by athre0z** [comment]
Alright, the release is published now. For some weird reason, GH is incorrectly displaying the tag on a different commit, but things are fine when you clone the repo. Perhaps a cache hick-up.
